import type { NotificationEventDefinition } from "@/lib/notifications/notification-event-catalog";

const adminOfficina = { admin: true, ufficio: false, officina: true, cliente: false } as const;
const adminOnly = { admin: true, ufficio: false, officina: false, cliente: false } as const;
const adminUfficio = { admin: true, ufficio: true, officina: false, cliente: false } as const;

/** Eventi aggiuntivi piattaforma notifiche v2 — merge in NOTIFICATION_EVENT_CATALOG. */
export const NOTIFICATION_EVENT_CATALOG_EXTENDED: readonly NotificationEventDefinition[] = [
  {
    notificationEventId: "fatturazione.overdue_digest",
    domainEvent: "invoice.overdue_digest",
    type: "fatture_scadute_digest",
    pageKey: "fatturazione",
    requiredAccess: "read",
    module: "fatturazione",
    scopeType: "role",
    scopeValue: "addetto_amministrativo",
    priority: "high",
    recipients: adminUfficio,
    trigger: "scheduled",
    dedupKeyPattern: "fatture-scadute:{dateBucket}",
    titleTemplate: "Fatture scadute",
    description: "Digest giornaliero fatture con residuo oltre scadenza",
    defaultEnabled: true,
    userConfigurable: true,
    notificationMode: "optional",
    notifyAuthor: false,
    severity: "warning",
  },
  {
    notificationEventId: "lavorazioni.overdue_digest",
    type: "lavorazioni_ritardo_digest",
    pageKey: "lavorazioni",
    requiredAccess: "read",
    module: "lavorazioni",
    scopeType: "global",
    scopeValue: null,
    priority: "high",
    recipients: adminOfficina,
    trigger: "scheduled",
    dedupKeyPattern: "lav-ritardo:{dateBucket}",
    titleTemplate: "Lavorazioni in ritardo",
    description: "Digest giornaliero lavorazioni oltre 14 giorni",
    defaultEnabled: true,
    userConfigurable: true,
    notificationMode: "optional",
    notifyAuthor: false,
    severity: "warning",
  },
  {
    notificationEventId: "preventivi.accepted",
    type: "preventivo_accettato",
    pageKey: "preventivi",
    requiredAccess: "read",
    module: "preventivi",
    scopeType: "role",
    scopeValue: "addetto_amministrativo",
    priority: "high",
    recipients: adminOnly,
    trigger: "db-trigger",
    dedupKeyPattern: "prev:accepted:{preventivoId}:{method}",
    titleTemplate: "Preventivo accettato",
    description: "Quando un preventivo viene accettato (cliente o timeout)",
    defaultEnabled: true,
    userConfigurable: true,
    notificationMode: "optional",
    notifyAuthor: false,
    severity: "info",
  },
  {
    notificationEventId: "preventivi.approved",
    type: "preventivo_approvato",
    pageKey: "preventivi",
    requiredAccess: "read",
    module: "preventivi",
    scopeType: "role",
    scopeValue: "addetto_amministrativo",
    priority: "high",
    recipients: adminUfficio,
    trigger: "db-trigger",
    dedupKeyPattern: "prev:approved:{preventivoId}",
    titleTemplate: "Preventivo approvato",
    description: "Quando un preventivo viene approvato",
    defaultEnabled: true,
    userConfigurable: true,
    notificationMode: "optional",
    notifyAuthor: false,
    severity: "info",
  },
  {
    notificationEventId: "dashboard.reminder",
    type: "dashboard_promemoria_reminder",
    pageKey: "dashboard",
    requiredAccess: "read",
    module: null,
    scopeType: "user",
    scopeValue: null,
    priority: "medium",
    recipients: adminOnly,
    trigger: "scheduled",
    dedupKeyPattern: "dash-reminder:{reminderId}:{dateBucket}",
    titleTemplate: "Promemoria calendario",
    description: "Promemoria personale dalla dashboard",
    defaultEnabled: true,
    userConfigurable: true,
    notificationMode: "optional",
    notifyAuthor: true,
    severity: "info",
  },
  {
    notificationEventId: "lavorazioni.updated",
    domainEvent: "work_order.updated",
    type: "lavorazione_aggiornata",
    pageKey: "lavorazioni",
    requiredAccess: "read",
    module: "lavorazioni",
    scopeType: "role",
    scopeValue: "operatore",
    priority: "medium",
    recipients: adminOfficina,
    trigger: "db-trigger",
    dedupKeyPattern: "lav:upd:{lavorazioneId}:{rev}",
    titleTemplate: "Lavorazione aggiornata",
    description: "Modifica significativa su una lavorazione",
    defaultEnabled: true,
    userConfigurable: true,
    notificationMode: "optional",
    notifyAuthor: false,
    severity: "info",
  },
  {
    notificationEventId: "lavorazioni.deleted",
    type: "lavorazione_eliminata",
    pageKey: "lavorazioni",
    requiredAccess: "read",
    module: "lavorazioni",
    scopeType: "role",
    scopeValue: "operatore",
    priority: "medium",
    recipients: adminOfficina,
    trigger: "db-trigger",
    dedupKeyPattern: "lav:del:{lavorazioneId}",
    titleTemplate: "Lavorazione eliminata",
    description: "Una lavorazione è stata eliminata",
    defaultEnabled: true,
    userConfigurable: true,
    notificationMode: "optional",
    notifyAuthor: false,
    severity: "warning",
  },
  {
    notificationEventId: "lavorazioni.archived",
    type: "lavorazione_archiviata",
    pageKey: "lavorazioni",
    requiredAccess: "read",
    module: "lavorazioni",
    scopeType: "role",
    scopeValue: "operatore",
    priority: "low",
    recipients: adminOfficina,
    trigger: "db-trigger",
    dedupKeyPattern: "lav:arch:{lavorazioneId}",
    titleTemplate: "Lavorazione archiviata",
    description: "Una lavorazione è stata archiviata",
    defaultEnabled: true,
    userConfigurable: true,
    notificationMode: "optional",
    notifyAuthor: false,
    severity: "info",
  },
  {
    notificationEventId: "preventivi.created",
    type: "preventivo_creato",
    pageKey: "preventivi",
    requiredAccess: "read",
    module: "preventivi",
    scopeType: "role",
    scopeValue: "addetto_amministrativo",
    priority: "medium",
    recipients: adminUfficio,
    trigger: "db-trigger",
    dedupKeyPattern: "prev:new:{preventivoId}",
    titleTemplate: "Nuovo preventivo",
    description: "È stato creato un nuovo preventivo",
    defaultEnabled: true,
    userConfigurable: true,
    notificationMode: "optional",
    notifyAuthor: false,
    severity: "info",
  },
  {
    notificationEventId: "preventivi.sent",
    type: "preventivo_inviato",
    pageKey: "preventivi",
    requiredAccess: "read",
    module: "preventivi",
    scopeType: "role",
    scopeValue: "addetto_amministrativo",
    priority: "medium",
    recipients: adminUfficio,
    trigger: "db-trigger",
    dedupKeyPattern: "prev:sent:{preventivoId}",
    titleTemplate: "Preventivo inviato",
    description: "Un preventivo è stato inviato al cliente",
    defaultEnabled: true,
    userConfigurable: true,
    notificationMode: "optional",
    notifyAuthor: false,
    severity: "info",
  },
  {
    notificationEventId: "preventivi.rejected",
    type: "preventivo_rifiutato",
    pageKey: "preventivi",
    requiredAccess: "read",
    module: "preventivi",
    scopeType: "role",
    scopeValue: "addetto_amministrativo",
    priority: "high",
    recipients: adminOnly,
    trigger: "db-trigger",
    dedupKeyPattern: "prev:rej:{preventivoId}",
    titleTemplate: "Preventivo rifiutato",
    description: "Un preventivo è stato rifiutato",
    defaultEnabled: true,
    userConfigurable: true,
    notificationMode: "optional",
    notifyAuthor: false,
    severity: "warning",
  },
  {
    notificationEventId: "preventivi.converted",
    type: "preventivo_convertito",
    pageKey: "preventivi",
    requiredAccess: "read",
    module: "preventivi",
    scopeType: "role",
    scopeValue: "addetto_amministrativo",
    priority: "medium",
    recipients: adminUfficio,
    trigger: "db-trigger",
    dedupKeyPattern: "prev:conv:{preventivoId}",
    titleTemplate: "Preventivo convertito",
    description: "Un preventivo è stato convertito in lavorazione",
    defaultEnabled: true,
    userConfigurable: true,
    notificationMode: "optional",
    notifyAuthor: false,
    severity: "info",
  },
  {
    notificationEventId: "magazzino.movement",
    type: "magazzino_movimento",
    pageKey: "magazzino",
    requiredAccess: "read",
    module: "magazzino",
    scopeType: "role",
    scopeValue: "operatore",
    priority: "low",
    recipients: adminOfficina,
    trigger: "db-trigger",
    dedupKeyPattern: "mag:mov:{movimentoId}",
    titleTemplate: "Movimento magazzino",
    description: "Carico o scarico magazzino",
    defaultEnabled: false,
    userConfigurable: true,
    notificationMode: "optional",
    notifyAuthor: false,
    severity: "info",
  },
  {
    notificationEventId: "magazzino.part_created",
    type: "magazzino_ricambio_creato",
    pageKey: "magazzino",
    requiredAccess: "read",
    module: "magazzino",
    scopeType: "role",
    scopeValue: "operatore",
    priority: "low",
    recipients: adminOfficina,
    trigger: "db-trigger",
    dedupKeyPattern: "mag:new:{ricambioId}",
    titleTemplate: "Nuovo ricambio",
    description: "Anagrafica ricambio creata",
    defaultEnabled: true,
    userConfigurable: true,
    notificationMode: "optional",
    notifyAuthor: false,
    severity: "info",
  },
  {
    notificationEventId: "magazzino.part_deleted",
    type: "magazzino_ricambio_eliminato",
    pageKey: "magazzino",
    requiredAccess: "read",
    module: "magazzino",
    scopeType: "role",
    scopeValue: "operatore",
    priority: "medium",
    recipients: adminOfficina,
    trigger: "db-trigger",
    dedupKeyPattern: "mag:del:{ricambioId}",
    titleTemplate: "Ricambio eliminato",
    description: "Anagrafica ricambio eliminata",
    defaultEnabled: true,
    userConfigurable: true,
    notificationMode: "optional",
    notifyAuthor: false,
    severity: "warning",
  },
  {
    notificationEventId: "fatturazione.invoice_issued",
    type: "fattura_emessa",
    pageKey: "fatturazione",
    requiredAccess: "read",
    module: "fatturazione",
    scopeType: "role",
    scopeValue: "addetto_amministrativo",
    priority: "medium",
    recipients: adminUfficio,
    trigger: "db-trigger",
    dedupKeyPattern: "fatt:issued:{fatturaId}",
    titleTemplate: "Fattura emessa",
    description: "Nuova fattura emessa",
    defaultEnabled: true,
    userConfigurable: true,
    notificationMode: "optional",
    notifyAuthor: false,
    severity: "info",
  },
  {
    notificationEventId: "fatturazione.invoice_paid",
    type: "fattura_pagata",
    pageKey: "fatturazione",
    requiredAccess: "read",
    module: "fatturazione",
    scopeType: "role",
    scopeValue: "addetto_amministrativo",
    priority: "medium",
    recipients: adminUfficio,
    trigger: "db-trigger",
    dedupKeyPattern: "fatt:paid:{fatturaId}",
    titleTemplate: "Fattura pagata",
    description: "Incasso fattura registrato",
    defaultEnabled: true,
    userConfigurable: true,
    notificationMode: "optional",
    notifyAuthor: false,
    severity: "info",
  },
  {
    notificationEventId: "fatturazione.invoice_overdue",
    type: "fattura_scaduta",
    pageKey: "fatturazione",
    requiredAccess: "read",
    module: "fatturazione",
    scopeType: "role",
    scopeValue: "addetto_amministrativo",
    priority: "high",
    recipients: adminUfficio,
    trigger: "db-trigger",
    dedupKeyPattern: "fatt:overdue:{fatturaId}",
    titleTemplate: "Fattura scaduta",
    description: "Singola fattura oltre scadenza",
    defaultEnabled: true,
    userConfigurable: true,
    notificationMode: "optional",
    notifyAuthor: false,
    severity: "critical",
  },
  {
    notificationEventId: "mezzi.created",
    type: "mezzo_creato",
    pageKey: "mezzi",
    requiredAccess: "read",
    module: "mezzi",
    scopeType: "role",
    scopeValue: "admin",
    priority: "low",
    recipients: adminOnly,
    trigger: "db-trigger",
    dedupKeyPattern: "mezzo:new:{mezzoId}",
    titleTemplate: "Nuovo mezzo",
    description: "Anagrafica mezzo creata",
    defaultEnabled: true,
    userConfigurable: true,
    notificationMode: "optional",
    notifyAuthor: false,
    severity: "info",
  },
  {
    notificationEventId: "mezzi.updated",
    type: "mezzo_aggiornato",
    pageKey: "mezzi",
    requiredAccess: "read",
    module: "mezzi",
    scopeType: "role",
    scopeValue: "admin",
    priority: "low",
    recipients: adminOnly,
    trigger: "db-trigger",
    dedupKeyPattern: "mezzo:upd:{mezzoId}",
    titleTemplate: "Mezzo aggiornato",
    description: "Anagrafica mezzo modificata",
    defaultEnabled: false,
    userConfigurable: true,
    notificationMode: "optional",
    notifyAuthor: false,
    severity: "info",
  },
  {
    notificationEventId: "clienti.created",
    type: "cliente_creato",
    pageKey: "fatturazione",
    requiredAccess: "read",
    module: "fatturazione",
    scopeType: "role",
    scopeValue: "addetto_amministrativo",
    priority: "low",
    recipients: adminUfficio,
    trigger: "db-trigger",
    dedupKeyPattern: "cliente:new:{clienteId}",
    titleTemplate: "Nuovo cliente",
    description: "Anagrafica cliente creata",
    defaultEnabled: true,
    userConfigurable: true,
    notificationMode: "optional",
    notifyAuthor: false,
    severity: "info",
  },
  {
    notificationEventId: "clienti.updated",
    type: "cliente_aggiornato",
    pageKey: "fatturazione",
    requiredAccess: "read",
    module: "fatturazione",
    scopeType: "role",
    scopeValue: "addetto_amministrativo",
    priority: "low",
    recipients: adminUfficio,
    trigger: "db-trigger",
    dedupKeyPattern: "cliente:upd:{clienteId}",
    titleTemplate: "Cliente aggiornato",
    description: "Anagrafica cliente modificata",
    defaultEnabled: false,
    userConfigurable: true,
    notificationMode: "optional",
    notifyAuthor: false,
    severity: "info",
  },
  {
    notificationEventId: "attrezzature.created",
    type: "attrezzatura_creata",
    pageKey: "mezzi",
    requiredAccess: "read",
    module: "mezzi",
    scopeType: "role",
    scopeValue: "admin",
    priority: "low",
    recipients: adminOnly,
    trigger: "db-trigger",
    dedupKeyPattern: "attr:new:{attrezzaturaId}",
    titleTemplate: "Nuova attrezzatura",
    description: "Anagrafica attrezzatura creata",
    defaultEnabled: true,
    userConfigurable: true,
    notificationMode: "optional",
    notifyAuthor: false,
    severity: "info",
  },
  {
    notificationEventId: "attrezzature.updated",
    type: "attrezzatura_aggiornata",
    pageKey: "mezzi",
    requiredAccess: "read",
    module: "mezzi",
    scopeType: "role",
    scopeValue: "admin",
    priority: "low",
    recipients: adminOnly,
    trigger: "db-trigger",
    dedupKeyPattern: "attr:upd:{attrezzaturaId}",
    titleTemplate: "Attrezzatura aggiornata",
    description: "Anagrafica attrezzatura modificata",
    defaultEnabled: false,
    userConfigurable: true,
    notificationMode: "optional",
    notifyAuthor: false,
    severity: "info",
  },
  {
    notificationEventId: "documenti.created",
    type: "documento_creato",
    pageKey: "documenti",
    requiredAccess: "read",
    module: "documenti",
    scopeType: "role",
    scopeValue: "admin",
    priority: "low",
    recipients: adminOnly,
    trigger: "db-trigger",
    dedupKeyPattern: "doc:new:{documentoId}",
    titleTemplate: "Nuovo documento",
    description: "Documento creato",
    defaultEnabled: true,
    userConfigurable: true,
    notificationMode: "optional",
    notifyAuthor: false,
    severity: "info",
  },
  {
    notificationEventId: "documenti.updated",
    type: "documento_aggiornato",
    pageKey: "documenti",
    requiredAccess: "read",
    module: "documenti",
    scopeType: "role",
    scopeValue: "admin",
    priority: "low",
    recipients: adminOnly,
    trigger: "db-trigger",
    dedupKeyPattern: "doc:upd:{documentoId}",
    titleTemplate: "Documento aggiornato",
    description: "Documento modificato",
    defaultEnabled: false,
    userConfigurable: true,
    notificationMode: "optional",
    notifyAuthor: false,
    severity: "info",
  },
  {
    notificationEventId: "compliance.due_soon",
    type: "compliance_in_scadenza",
    pageKey: "report",
    requiredAccess: "read",
    module: "report",
    scopeType: "role",
    scopeValue: "admin",
    priority: "high",
    recipients: adminOnly,
    trigger: "scheduled",
    dedupKeyPattern: "compliance:due:{assetId}:{dateBucket}",
    titleTemplate: "Revisione in scadenza",
    description: "Asset in scadenza compliance",
    defaultEnabled: true,
    userConfigurable: true,
    notificationMode: "optional",
    notifyAuthor: false,
    severity: "warning",
  },
  {
    notificationEventId: "compliance.overdue",
    type: "compliance_scaduta",
    pageKey: "report",
    requiredAccess: "read",
    module: "report",
    scopeType: "role",
    scopeValue: "admin",
    priority: "urgent",
    recipients: adminOnly,
    trigger: "scheduled",
    dedupKeyPattern: "compliance:over:{assetId}",
    titleTemplate: "Revisione scaduta",
    description: "Asset con compliance scaduta",
    defaultEnabled: true,
    userConfigurable: true,
    notificationMode: "mandatory",
    notifyAuthor: false,
    severity: "critical",
  },
  {
    notificationEventId: "ordini.created",
    type: "ordine_creato",
    pageKey: "magazzino",
    requiredAccess: "read",
    module: "magazzino",
    scopeType: "role",
    scopeValue: "operatore",
    priority: "medium",
    recipients: adminOfficina,
    trigger: "db-trigger",
    dedupKeyPattern: "ord:new:{ordineId}",
    titleTemplate: "Nuovo ordine fornitore",
    description: "Ordine fornitore creato",
    defaultEnabled: true,
    userConfigurable: true,
    notificationMode: "optional",
    notifyAuthor: false,
    severity: "info",
  },
  {
    notificationEventId: "ordini.updated",
    type: "ordine_aggiornato",
    pageKey: "magazzino",
    requiredAccess: "read",
    module: "magazzino",
    scopeType: "role",
    scopeValue: "operatore",
    priority: "low",
    recipients: adminOfficina,
    trigger: "db-trigger",
    dedupKeyPattern: "ord:upd:{ordineId}",
    titleTemplate: "Ordine fornitore aggiornato",
    description: "Stato ordine fornitore modificato",
    defaultEnabled: true,
    userConfigurable: true,
    notificationMode: "optional",
    notifyAuthor: false,
    severity: "info",
  },
  {
    notificationEventId: "system.error",
    type: "system_error",
    pageKey: "sicurezza",
    requiredAccess: "read",
    module: null,
    scopeType: "role",
    scopeValue: "admin",
    priority: "urgent",
    recipients: adminOnly,
    trigger: "scheduled",
    dedupKeyPattern: "sys:err:{errorId}",
    titleTemplate: "Errore di sistema",
    description: "Errore critico applicazione",
    defaultEnabled: true,
    userConfigurable: false,
    notificationMode: "mandatory",
    notifyAuthor: false,
    severity: "critical",
  },
];
