/** Valori iniziali liste mezzi (solo seed UI prima del sync con `app_settings`). */
export const MEZZI_LISTE_DEFAULTS = {
  clienti: [
    "ASM Monza Brianza",
    "A2A Ambiente",
    "Hera S.p.A.",
    "Contarina",
    "Alia Servizi",
    "IAS Latina",
    "AMSA Milano",
    "Suez Italia",
    "Veritas Venezia",
    "ACEA Pinerolese",
    "AMIU Bari",
    "Comune di Lecce",
    "AGER Puglia",
    "Navita Barletta",
  ],
  marche: ["Iveco", "Mercedes-Benz", "Isuzu", "Bucher", "Schmidt", "Piaggio", "Renault", "Volvo", "Scania", "MAN"],
  tipiAttrezzatura: [
    "Spazzatrice stradale",
    "Compattatore rifiuti",
    "Autospazzatrice cabinata",
    "Lavastrade",
    "Ape raccolta rifiuti",
    "Ape spazzatrice",
    "Scarrabile",
    "Porter elettrico",
    "Multicarro",
    "Semirimorchio",
    "Motrice 4 assi",
    "Officina mobile",
  ],
  stati: ["Operativo", "In manutenzione", "Fermo amministrativo", "Attesa ricambi", "In collaudo"],
} as const;
