import type { ChangeEvent } from "react";

/** Prefisso codice generato in passato quando l'OE non era compilato (legacy). */
export const RICAMBIO_AUTO_CODICE_PREFIX = "AUTO-";

const RICAMBIO_CODICE_PLACEHOLDER_DASHES = new Set(["—", "-", "–"]);

function trimCodiceRaw(value: string | null | undefined): string {
  return (value ?? "").trim();
}

/** Normalizza codice ricambio (OE o alternativo) in maiuscolo — non decide presente/assente. */
export function normalizeRicambioCodice(value: string | null | undefined): string {
  const trimmed = trimCodiceRaw(value);
  if (!trimmed) return "";
  if (RICAMBIO_CODICE_PLACEHOLDER_DASHES.has(trimmed)) return "";
  return trimmed.toLocaleUpperCase("it-IT");
}

export function isAutoGeneratedRicambioCodice(codice: string | null | undefined): boolean {
  const normalized = normalizeRicambioCodice(codice);
  return normalized.startsWith(RICAMBIO_AUTO_CODICE_PREFIX);
}

export function ricambioCodiceIsPresent(codice: string | null | undefined): boolean {
  const normalized = normalizeRicambioCodice(codice);
  if (!normalized) return false;
  if (isAutoGeneratedRicambioCodice(normalized)) return false;
  return true;
}

/** Codice per UI/domain live: normalizzato se presente, altrimenti "". */
export function ricambioCodiceForUi(codice: string | null | undefined): string {
  return ricambioCodiceIsPresent(codice) ? normalizeRicambioCodice(codice) : "";
}

/** Codice per celle testuali: valore UI o segnaposto "—". */
export function displayRicambioCodice(codice: string | null | undefined): string {
  const ui = ricambioCodiceForUi(codice);
  return ui || "—";
}

/** Strict: true se il codice è compilato (per `ricambioFromForm`). */
export function validateRicambioCodiceRequired(codiceRaw: string | null | undefined): boolean {
  return ricambioCodiceIsPresent(codiceRaw);
}

/** Codice persistito lenient: OE utente o "" se assente — mai AUTO. */
export function resolveRicambioCodiceForPersist(codiceRaw: string | null | undefined): string {
  return ricambioCodiceForUi(codiceRaw);
}

/** Input controllato: uppercase in tempo reale, cursore invariato se possibile. */
export function applyRicambioCodiceInputChange(
  event: ChangeEvent<HTMLInputElement>,
  onValue: (next: string) => void,
): void {
  const input = event.target;
  const start = input.selectionStart;
  const end = input.selectionEnd;
  const next = normalizeRicambioCodice(input.value);
  onValue(next);
  if (start === null || end === null) return;
  requestAnimationFrame(() => {
    try {
      input.setSelectionRange(start, end);
    } catch {
      /* ignore */
    }
  });
}
