import assert from "node:assert/strict";
import {
  displayRicambioCodice,
  isAutoGeneratedRicambioCodice,
  normalizeRicambioCodice,
  resolveRicambioCodiceForPersist,
  ricambioCodiceForUi,
  ricambioCodiceIsPresent,
  validateRicambioCodiceRequired,
} from "@/lib/magazzino/ricambio-codice";

assert.equal(normalizeRicambioCodice("abc123"), "ABC123");
assert.equal(normalizeRicambioCodice("AbC-12"), "ABC-12");
assert.equal(normalizeRicambioCodice(""), "");
assert.equal(normalizeRicambioCodice(null), "");
assert.equal(normalizeRicambioCodice(undefined), "");
assert.equal(normalizeRicambioCodice("  ABC123 "), "ABC123");
assert.equal(normalizeRicambioCodice("—"), "");
assert.equal(normalizeRicambioCodice(" - "), "");
assert.equal(normalizeRicambioCodice("AUTO-ABC"), "AUTO-ABC");
assert.equal(normalizeRicambioCodice("già"), "GIÀ");

assert.equal(resolveRicambioCodiceForPersist(" oe-99 "), "OE-99");
assert.equal(resolveRicambioCodiceForPersist(""), "");
assert.equal(resolveRicambioCodiceForPersist("—"), "");
assert.equal(resolveRicambioCodiceForPersist(" - "), "");
assert.equal(resolveRicambioCodiceForPersist(null), "");

assert.equal(ricambioCodiceIsPresent("ABC123"), true);
assert.equal(ricambioCodiceIsPresent(""), false);
assert.equal(ricambioCodiceIsPresent("—"), false);
assert.equal(ricambioCodiceIsPresent(" - "), false);
assert.equal(ricambioCodiceIsPresent("AUTO-123"), false);
assert.ok(isAutoGeneratedRicambioCodice("AUTO-123"));

assert.equal(ricambioCodiceForUi("AUTO-123"), "");
assert.equal(ricambioCodiceForUi("ABC123"), "ABC123");
assert.equal(displayRicambioCodice(""), "—");
assert.equal(displayRicambioCodice("AUTO-123"), "—");
assert.equal(displayRicambioCodice("ABC123"), "ABC123");

assert.equal(validateRicambioCodiceRequired("ABC"), true);
assert.equal(validateRicambioCodiceRequired(""), false);
assert.equal(validateRicambioCodiceRequired("AUTO-X"), false);

console.log("ricambio-codice.test.ts OK");
