import assert from "node:assert/strict";
import {
  isAutoGeneratedRicambioCodice,
  normalizeRicambioCodice,
  resolveRicambioCodiceForPersist,
  RICAMBIO_AUTO_CODICE_PREFIX,
} from "@/lib/magazzino/ricambio-codice";

assert.equal(normalizeRicambioCodice("abc123"), "ABC123");
assert.equal(normalizeRicambioCodice("AbC-12"), "ABC-12");
assert.equal(normalizeRicambioCodice(""), "");
assert.equal(normalizeRicambioCodice("già"), "GIÀ");

assert.equal(resolveRicambioCodiceForPersist(" oe-99 "), "OE-99");
assert.equal(
  resolveRicambioCodiceForPersist("", "a1b2c3d4-e5f6-7890-abcd-ef1234567890"),
  "AUTO-A1B2C3D4E5F6",
);
assert.equal(resolveRicambioCodiceForPersist("—", "a1b2c3d4-e5f6-7890-abcd-ef1234567890"), "AUTO-A1B2C3D4E5F6");
const autoA = resolveRicambioCodiceForPersist("", "a1b2c3d4-e5f6-7890-abcd-ef1234567890");
const autoB = resolveRicambioCodiceForPersist("", "b2c3d4e5-f6a7-8901-bcde-f12345678901");
assert.ok(isAutoGeneratedRicambioCodice(autoA));
assert.notEqual(autoA, autoB);

console.log("ricambio-codice.test.ts OK");
