import type { ChangeEvent } from "react";

/** Prefisso codice generato quando l'OE non è compilato (UNIQUE su `magazzino_ricambi.codice`). */
export const RICAMBIO_AUTO_CODICE_PREFIX = "AUTO-";

/** Normalizza codice ricambio (OE o alternativo) in maiuscolo — unica regola UI + persistenza. */
export function normalizeRicambioCodice(value: string): string {
  if (!value) return value;
  return value.toLocaleUpperCase("it-IT");
}

export function isAutoGeneratedRicambioCodice(codice: string): boolean {
  return normalizeRicambioCodice(codice.trim()).startsWith(RICAMBIO_AUTO_CODICE_PREFIX);
}

/** Codice persistito: OE utente, altrimenti AUTO-* univoco (mai il segnaposto «—» condiviso). */
export function resolveRicambioCodiceForPersist(codiceRaw: string, ricambioId?: string): string {
  const normalized = normalizeRicambioCodice(codiceRaw.trim());
  if (normalized && normalized !== "—") return normalized;
  const seed = (ricambioId ?? `r-${Date.now()}`).replace(/-/g, "").toUpperCase();
  return `${RICAMBIO_AUTO_CODICE_PREFIX}${seed.slice(0, 12)}`;
}

/** Input controllato: uppercase in tempo reale, cursore invariato se possibile. */
export function applyRicambioCodiceInputChange(
  event: ChangeEvent<HTMLInputElement>,
  onValue: (next: string) => void,
): void {
  const input = event.target;
  const start = input.selectionStart;
  const end = input.selectionEnd;
  const next = normalizeRicambioCodice(input.value);
  onValue(next);
  if (start === null || end === null) return;
  requestAnimationFrame(() => {
    try {
      input.setSelectionRange(start, end);
    } catch {
      /* ignore */
    }
  });
}
