export { debugSelectOptions, SELECT_OPTIONS_DEBUG } from "./debug-options-log";
export {
  addStatoFromLabel,
  buildStatiLavorazioniOptions,
  CLIENT_PORTAL_FALLBACK_STATO,
  DEFAULT_LAVORAZIONE_STATO_ID,
  DEFAULT_STATI_LAVORAZIONI_DB,
  DEFAULT_STATI_LAVORAZIONI_WORKFLOW,
  isDbStatoLavorazione,
  isQuerySafeStatoForSupabaseFilter,
  isStatoClosed,
  isStatoInConfig,
  migrateStatoConfigId,
  migrateStatiConfigList,
  normalizeStatiList,
  reorderStatiList,
  resolveDefaultLavorazioneStatoId,
  resolveStatoId,
  resolveStatoToDbEnum,
  slugifyStatoId,
  statiEnumDisponibiliDaAggiungere,
  statiLavorazioniChiusiOptions,
  statiLavorazioniInCorsoOptions,
  statiLavorazioniRapidiOptions,
  statoLavorazioneLabel,
  STATO_LAVORAZIONE_COMPLETATA_DB,
  STATO_LAVORAZIONE_COMPLETATA_ID,
} from "./lavorazioni-stati-db";
