export { debugSelectOptions, SELECT_OPTIONS_DEBUG } from "./debug-options-log";
export {
  ALL_DB_STATI_LAVORAZIONE,
  DEFAULT_STATI_LAVORAZIONI_DB,
  LEGACY_STATO_ID_TO_DB,
  buildStatiLavorazioniOptions,
  isDbStatoLavorazione,
  CLIENT_PORTAL_FALLBACK_STATO,
  isQuerySafeStatoForSupabaseFilter,
  OPTIONAL_CUSTOM_STATI_SLOTS,
  resolveStatoToDbEnum,
  UNIVERSAL_SAFE_STATI_LAVORAZIONE,
  migrateStatoConfigId,
  migrateStatiConfigList,
  statiLavorazioniChiusiOptions,
  statiLavorazioniInCorsoOptions,
  statiLavorazioniRapidiOptions,
  statoLavorazioneLabel,
  statiEnumDisponibiliDaAggiungere,
  STATO_LAVORAZIONE_COMPLETATA_DB,
} from "./lavorazioni-stati-db";
