/** Error codes SSOT — Document Capture telemetry/API. */

export const DOCUMENT_CAPTURE_ERROR_CODES = [
  "UPLOAD_FAILED",
  "STORAGE_PERMISSION_DENIED",
  "STORAGE_NOT_FOUND",
  "STORAGE_EMPTY",
  "ANALYZE_TIMEOUT",
  "ANALYZE_GEMINI_SCHEMA",
  "ANALYZE_GEMINI_FAIL",
  "ANALYZE_STORAGE",
  "ANALYZE_PREREQUISITES",
  "PLAN_STALE",
  "APPLY_FAILED",
  "APPLY_IN_PROGRESS",
  "UNAUTHORIZED",
  "TENANT_MISSING",
  "RATE_LIMITED",
  "NOT_CONFIGURED",
  "TIMEOUT_PHASE_VERIFY",
  "TIMEOUT_PHASE_READ",
  "TIMEOUT_PHASE_AI",
  "TIMEOUT_PHASE_PROJECTION",
  "TIMEOUT_PHASE_VALIDATE",
  "PIPELINE_VERSION_STALE",
  "STREAM_ENDED_WITHOUT_TERMINAL",
  "ANALYZE_IN_PROGRESS",
  "PIPELINE_PHASE_FAILED",
] as const;

export type DocumentCaptureErrorCode = (typeof DOCUMENT_CAPTURE_ERROR_CODES)[number];

export function isDocumentCaptureErrorCode(value: string): value is DocumentCaptureErrorCode {
  return (DOCUMENT_CAPTURE_ERROR_CODES as readonly string[]).includes(value);
}
