export const ASK_REPORT_MAX_TOOL_ROUNDS = 4;
export const ASK_REPORT_MAX_TOOLS_PER_ROUND = 3;
export const ASK_REPORT_MAX_SERIES_POINTS = 24;
export const ASK_REPORT_MAX_INSIGHTS = 8;
export const ASK_REPORT_MAX_DECISIONS = 12;
export const ASK_REPORT_MAX_DRILLDOWN_ROWS = 25;
export const ASK_REPORT_CONVERSATION_CACHE_TTL_MS = 30 * 60 * 1000;
