import type { ReportKpiTrust } from "@/lib/report/kpi-display-clusters";
import type { ReportSectionId } from "@/components/report/report-sections-config";
import type {
  ReportMetricApplicability,
  ReportMetricAggregation,
  ReportMetricCategory,
  ReportMetricKind,
  ReportMetricLifecycleStatus,
  ReportMetricRegistryEntry,
  ReportMetricTrendSemantics,
  ReportMetricUnit,
  ReportMetricConfidence,
} from "@/lib/report/metrics/report-metric-types";
import { unitToReportFormatter } from "@/lib/report/metrics/report-value-formatter";

function entry(
  e: {
    id: string;
    status?: ReportMetricLifecycleStatus;
    owner: ReportSectionId;
    category: ReportMetricCategory;
    label: string;
    description: string;
    unit: ReportMetricUnit;
    aggregation: ReportMetricAggregation;
    applicability: ReportMetricApplicability;
    trendSemantics: ReportMetricTrendSemantics;
    rendererKind?: ReportMetricKind;
    sourceModule: string;
    formula?: string;
    trust?: ReportKpiTrust;
    confidence?: ReportMetricConfidence;
  },
): ReportMetricRegistryEntry {
  const status = e.status ?? "active";
  return {
    status,
    rendererKind: e.rendererKind ?? "kpi",
    formatter: unitToReportFormatter(e.unit),
    ...e,
  };
}

export const REPORT_METRIC_REGISTRY: readonly ReportMetricRegistryEntry[] = [
  // — Panoramica —
  entry({
    id: "lav-periodo",
    owner: "panoramica",
    category: "operational",
    label: "Carico periodo",
    description: "Lavorazioni con data di ingresso nel periodo selezionato.",
    unit: "count",
    aggregation: "count",
    applicability: "period",
    trendSemantics: "neutral",
    sourceModule: "build-report-model",
    trust: "exact",
  }),
  entry({
    id: "lav-chiusi",
    owner: "panoramica",
    category: "operational",
    label: "Chiusure periodo",
    description: "Completate archiviate nel periodo (DB + override manuali).",
    unit: "count",
    aggregation: "count",
    applicability: "period",
    trendSemantics: "higher_is_better",
    sourceModule: "kpi-performance",
    trust: "exact",
  }),
  entry({
    id: "lav-saldo-periodo",
    owner: "panoramica",
    category: "operational",
    label: "Saldo backlog periodo",
    description: "Ingressi meno chiusure nel periodo (accumulo vs smaltimento).",
    unit: "count",
    aggregation: "derived",
    applicability: "period",
    trendSemantics: "positive_when_decreasing",
    sourceModule: "build-report-model",
    formula: "openedInPeriod - completedInPeriod",
    trust: "exact",
  }),
  entry({
    id: "lav-media-settimanale",
    owner: "panoramica",
    category: "operational",
    label: "Media chiusure/settimana",
    description: "Media chiusure archiviate per settimana nel filtro periodo.",
    unit: "ratio",
    aggregation: "avg",
    applicability: "period",
    trendSemantics: "higher_is_better",
    sourceModule: "report-semantic-index",
    trust: "exact",
  }),
  entry({
    id: "lav-aperti",
    owner: "panoramica",
    category: "operational",
    label: "Interventi aperti",
    description: "Lavorazioni non archiviate attualmente in gestione.",
    unit: "count",
    aggregation: "latest",
    applicability: "snapshot",
    trendSemantics: "neutral",
    sourceModule: "kpi-performance",
    trust: "exact",
  }),
  entry({
    id: "lav-tempo",
    owner: "panoramica",
    category: "operational",
    label: "Tempo medio chiusura",
    description: "Media giorni tra ingresso e chiusura delle archiviate nel periodo.",
    unit: "days",
    aggregation: "avg",
    applicability: "period",
    trendSemantics: "lower_is_better",
    sourceModule: "kpi-performance",
    trust: "exact",
  }),
  entry({
    id: "clienti",
    owner: "panoramica",
    category: "customer",
    label: "Clienti nel periodo",
    description: "Clienti con almeno un ingresso o una chiusura nel periodo.",
    unit: "count",
    aggregation: "count",
    applicability: "period",
    trendSemantics: "higher_is_better",
    sourceModule: "build-report-model",
    trust: "exact",
  }),
  entry({
    id: "cost-tot",
    owner: "panoramica",
    category: "economic",
    label: "Costi manutenzione",
    description: "Costo ricambi da log + manodopera da schede (se caricate).",
    unit: "currency",
    aggregation: "sum",
    applicability: "period",
    trendSemantics: "lower_is_better",
    sourceModule: "kpi-performance",
    trust: "partial",
  }),
  entry({
    id: "scorta",
    owner: "panoramica",
    category: "warehouse",
    label: "Ricambi sotto scorta",
    description: "Ricambi con quantità sotto la scorta minima.",
    unit: "count",
    aggregation: "count",
    applicability: "snapshot",
    trendSemantics: "lower_is_better",
    sourceModule: "kpi-performance",
    trust: "exact",
  }),
  // — Clienti e mezzi —
  entry({
    id: "cap",
    owner: "clienti_mezzi",
    category: "warehouse",
    label: "Capitale immobilizzato",
    description: "Valore magazzino a costo di acquisto (istantaneo).",
    unit: "currency",
    aggregation: "latest",
    applicability: "snapshot",
    trendSemantics: "neutral",
    sourceModule: "build-report-model",
    trust: "snapshot",
  }),
  entry({
    id: "ric-usati",
    owner: "clienti_mezzi",
    category: "warehouse",
    label: "Ricambi movimentati",
    description: "Somma uscite dai movimenti di magazzino nel periodo.",
    unit: "count",
    aggregation: "sum",
    applicability: "period",
    trendSemantics: "neutral",
    sourceModule: "build-report-model",
    trust: "exact",
  }),
  entry({
    id: "flotta-officina",
    owner: "clienti_mezzi",
    category: "fleet",
    label: "Mezzi in officina",
    description: "Mezzi con almeno una lavorazione non archiviata.",
    unit: "count",
    aggregation: "count",
    applicability: "snapshot",
    trendSemantics: "neutral",
    sourceModule: "kpi-performance",
    trust: "proxy",
  }),
  entry({
    id: "mezzi",
    owner: "clienti_mezzi",
    category: "fleet",
    label: "Mezzi in anagrafica",
    description: "Totale mezzi in anagrafica (non filtrato per periodo).",
    unit: "count",
    aggregation: "count",
    applicability: "snapshot",
    trendSemantics: "neutral",
    sourceModule: "build-report-model",
    trust: "snapshot",
  }),
  // — Lavorazioni domain —
  entry({
    id: "lav_open",
    owner: "lavorazioni",
    category: "operational",
    label: "Aperte",
    description: "Interventi aperti (istantaneo).",
    unit: "count",
    aggregation: "count",
    applicability: "snapshot",
    trendSemantics: "neutral",
    sourceModule: "kpi-performance-formulas",
    trust: "exact",
  }),
  entry({
    id: "lav_completed",
    status: "deprecated",
    owner: "lavorazioni",
    category: "operational",
    label: "Completate",
    description: "Usare lav-chiusi in panoramica. Mantenuto per adapter domain.",
    unit: "count",
    aggregation: "count",
    applicability: "period",
    trendSemantics: "higher_is_better",
    sourceModule: "lavorazioni-report-selectors",
    trust: "exact",
  }),
  entry({
    id: "lav_archived",
    owner: "lavorazioni",
    category: "operational",
    label: "Archiviate",
    description: "Totale archiviate in anagrafica.",
    unit: "count",
    aggregation: "count",
    applicability: "snapshot",
    trendSemantics: "neutral",
    sourceModule: "lavorazioni-report-adapter",
    trust: "exact",
  }),
  entry({
    id: "lav_cancelled",
    owner: "lavorazioni",
    category: "operational",
    label: "Annullate",
    description: "Lavorazioni annullate nel periodo.",
    unit: "count",
    aggregation: "count",
    applicability: "period",
    trendSemantics: "lower_is_better",
    sourceModule: "lavorazioni-report-selectors",
    trust: "exact",
  }),
  entry({
    id: "lav_backlog",
    owner: "lavorazioni",
    category: "operational",
    label: "Backlog",
    description: "Interventi aperti non archiviati.",
    unit: "count",
    aggregation: "count",
    applicability: "snapshot",
    trendSemantics: "lower_is_better",
    sourceModule: "kpi-performance-formulas",
    trust: "exact",
  }),
  entry({
    id: "lav_avg_close",
    status: "deprecated",
    owner: "lavorazioni",
    category: "operational",
    label: "Tempo medio chiusura",
    description: "Usare lav-tempo in panoramica.",
    unit: "days",
    aggregation: "avg",
    applicability: "period",
    trendSemantics: "lower_is_better",
    sourceModule: "lavorazioni-report-selectors",
    trust: "exact",
  }),
  entry({
    id: "lav_late_sla",
    owner: "lavorazioni",
    category: "operational",
    label: "Oltre SLA",
    description: "Interventi oltre SLA (istantaneo).",
    unit: "count",
    aggregation: "count",
    applicability: "snapshot",
    trendSemantics: "lower_is_better",
    sourceModule: "kpi-performance-formulas",
    trust: "exact",
  }),
  entry({
    id: "lav_clients",
    status: "deprecated",
    owner: "lavorazioni",
    category: "customer",
    label: "Clienti serviti",
    description: "Usare clienti in panoramica.",
    unit: "count",
    aggregation: "count",
    applicability: "period",
    trendSemantics: "higher_is_better",
    sourceModule: "lavorazioni-report-selectors",
    trust: "exact",
  }),
  // — Magazzino —
  entry({
    id: "mag_parts_qty",
    owner: "magazzino_ricambi",
    category: "warehouse",
    label: "Ricambi utilizzati",
    description: "Quantità uscite nel periodo.",
    unit: "count",
    aggregation: "sum",
    applicability: "period",
    trendSemantics: "neutral",
    sourceModule: "magazzino-period-aggregate",
    trust: "exact",
  }),
  entry({
    id: "mag_movement_value",
    owner: "magazzino_ricambi",
    category: "warehouse",
    label: "Valore movimentato",
    description: "Valore costo movimenti ricambi nel periodo.",
    unit: "currency",
    aggregation: "sum",
    applicability: "period",
    trendSemantics: "neutral",
    sourceModule: "kpi-performance-formulas",
    trust: "partial",
  }),
  entry({
    id: "mag_critical",
    owner: "magazzino_ricambi",
    category: "warehouse",
    label: "Sotto scorta",
    description: "Ricambi sotto scorta minima.",
    unit: "count",
    aggregation: "count",
    applicability: "snapshot",
    trendSemantics: "lower_is_better",
    sourceModule: "kpi-performance-formulas",
    trust: "exact",
  }),
  entry({
    id: "mag_orders",
    owner: "magazzino_ricambi",
    category: "warehouse",
    label: "Ordini fornitori",
    description: "Ordini fornitori nel periodo.",
    unit: "count",
    aggregation: "count",
    applicability: "period",
    trendSemantics: "neutral",
    sourceModule: "ordini-fornitori",
    trust: "exact",
  }),
  // — Ore —
  entry({
    id: "ore_total",
    owner: "ore_lavorate",
    category: "operational",
    label: "Ore totali",
    description: "Ore lavorate dal timesheet nel periodo.",
    unit: "hours",
    aggregation: "sum",
    applicability: "period",
    trendSemantics: "higher_is_better",
    sourceModule: "timesheet-totals",
    trust: "exact",
  }),
  entry({
    id: "ore_per_job",
    owner: "ore_lavorate",
    category: "operational",
    label: "Media ore/intervento",
    description: "Ore totali diviso lavorazioni completate nel periodo.",
    unit: "hours",
    aggregation: "derived",
    applicability: "derived",
    trendSemantics: "neutral",
    sourceModule: "report-domain-analytics",
    formula: "totalHours / completedJobs",
    trust: "partial",
  }),
  // — Economici —
  entry({
    id: "eco_preventivi",
    owner: "dati_economici",
    category: "economic",
    label: "Preventivi",
    description: "Preventivi non bozza nel periodo.",
    unit: "count",
    aggregation: "count",
    applicability: "period",
    trendSemantics: "higher_is_better",
    sourceModule: "preventivi-records",
    trust: "exact",
  }),
  entry({
    id: "eco_preventivi_approvati",
    owner: "dati_economici",
    category: "economic",
    label: "Preventivi approvati",
    description: "Preventivi approvati o convertiti nel periodo.",
    unit: "count",
    aggregation: "count",
    applicability: "period",
    trendSemantics: "higher_is_better",
    sourceModule: "preventivi-records",
    trust: "exact",
  }),
  entry({
    id: "eco_invoices",
    owner: "dati_economici",
    category: "economic",
    label: "Fatturato periodo",
    description: "Fatture emesse nel periodo (escl. bozza/da verificare).",
    unit: "currency",
    aggregation: "sum",
    applicability: "period",
    trendSemantics: "higher_is_better",
    sourceModule: "invoice-calculations",
    trust: "exact",
  }),
  entry({
    id: "eco_ddt",
    owner: "dati_economici",
    category: "economic",
    label: "DDT",
    description: "Documenti di trasporto nel periodo.",
    unit: "count",
    aggregation: "count",
    applicability: "period",
    trendSemantics: "higher_is_better",
    sourceModule: "ddt-calculations",
    trust: "exact",
  }),
  entry({
    id: "eco_valore_medio_intervento",
    owner: "dati_economici",
    category: "economic",
    label: "Valore medio intervento",
    description: "Fatturato periodo diviso chiusure nel periodo.",
    unit: "currency",
    aggregation: "derived",
    applicability: "derived",
    trendSemantics: "higher_is_better",
    sourceModule: "report-derived-engine",
    formula: "fatturato / completedInPeriod",
    trust: "partial",
    confidence: "partial",
  }),
  entry({
    id: "eco_margine_operativo_stimato",
    owner: "dati_economici",
    category: "economic",
    label: "Margine operativo stimato",
    description: "Fatturato meno costo ricambi movimentati e manodopera da schede. DDT esclusi. Stima gestionale.",
    unit: "currency",
    aggregation: "derived",
    applicability: "derived",
    trendSemantics: "higher_is_better",
    sourceModule: "report-derived-engine",
    formula: "fatturato - (manodoperaCost + movementValue)",
    trust: "partial",
    confidence: "partial",
  }),
  // — Cross (internal) —
  entry({
    id: "cross_efficiency",
    status: "internal",
    owner: "analisi_incrociate",
    category: "operational",
    label: "Efficienza officina",
    description: "Lavorazioni chiuse per ora lavorata nel periodo.",
    unit: "ratio",
    aggregation: "derived",
    applicability: "derived",
    trendSemantics: "higher_is_better",
    sourceModule: "report-domain-analytics",
    formula: "completedInPeriod / totalHours",
    trust: "partial",
  }),
  entry({
    id: "cross_cost_job",
    status: "internal",
    owner: "analisi_incrociate",
    category: "economic",
    label: "Costo medio lavorazione",
    description: "Costo ricambi + manodopera per lavorazione completata.",
    unit: "currency",
    aggregation: "derived",
    applicability: "derived",
    trendSemantics: "lower_is_better",
    sourceModule: "report-domain-analytics",
    formula: "(movementValue + manodoperaCost) / completedInPeriod",
    trust: "partial",
  }),
  entry({
    id: "cross_value_hour",
    status: "internal",
    owner: "analisi_incrociate",
    category: "economic",
    label: "Valore/ora",
    description: "Fatturato diviso ore lavorate nel periodo.",
    unit: "currency",
    aggregation: "derived",
    applicability: "derived",
    trendSemantics: "higher_is_better",
    sourceModule: "report-domain-analytics",
    formula: "invoicesBilled / totalHours",
    trust: "partial",
  }),
  entry({
    id: "cross_parts_job",
    status: "internal",
    owner: "analisi_incrociate",
    category: "warehouse",
    label: "Ricambi/intervento",
    description: "Ricambi utilizzati diviso chiusure nel periodo.",
    unit: "ratio",
    aggregation: "derived",
    applicability: "derived",
    trendSemantics: "neutral",
    sourceModule: "report-domain-analytics",
    formula: "partsUsedQty / completedInPeriod",
    trust: "exact",
  }),
] as const;

const REGISTRY_BY_ID = new Map(REPORT_METRIC_REGISTRY.map((e) => [e.id, e]));

export function getRegistryEntry(id: string): ReportMetricRegistryEntry | undefined {
  return REGISTRY_BY_ID.get(id);
}

export function assertRegistryUnique(): void {
  const ids = new Set<string>();
  for (const e of REPORT_METRIC_REGISTRY) {
    if (ids.has(e.id)) throw new Error(`Duplicate registry id: ${e.id}`);
    ids.add(e.id);
  }
}

export function activeUiMetricIds(): string[] {
  return REPORT_METRIC_REGISTRY.filter((e) => e.status === "active").map((e) => e.id);
}

export function assertActiveOwnerUnique(): void {
  const owners = new Map<string, string>();
  for (const e of REPORT_METRIC_REGISTRY) {
    if (e.status !== "active") continue;
    const prev = owners.get(e.id);
    if (prev) throw new Error(`Duplicate active id: ${e.id}`);
    owners.set(e.id, e.owner);
  }
}

/** Legacy compat: domain KPI ids per section (esclude deprecated dalla UI). */
export function reportMetricIdsForSection(section: ReportSectionId): string[] {
  return REPORT_METRIC_REGISTRY.filter(
    (e) => e.owner === section && e.status === "active" && e.rendererKind === "kpi",
  ).map((e) => e.id);
}
