import type { ControlDefinition } from "./types";

/**
 * Governance metadata only — no test lists, no script imports.
 * Keep human-readable; target <200 lines.
 */
export const CONTROL_REGISTRY: readonly ControlDefinition[] = [
  // —— Security ——
  {
    id: "security.rbac.matrix",
    implementation: { type: "test-suite", reference: "security-rbac" },
    domain: "security",
    tier: "pr",
    severity: "blocker",
    status: "active",
    owner: "security",
    sourceOfTruth: "src/lib/rbac/resolve-page-access.ts",
    impact: ["all-users", "tenant-isolation", "customer-data"],
  },
  {
    id: "security.rbac.hardening",
    implementation: { type: "test-suite", reference: "security-rbac-hardening" },
    domain: "security",
    tier: "pr",
    severity: "blocker",
    status: "active",
    owner: "security",
    sourceOfTruth: "src/lib/auth/server-permission-guards.ts",
    impact: ["all-users", "tenant-isolation"],
    dependsOn: ["security.rbac.matrix"],
  },
  {
    id: "security.remediation",
    implementation: { type: "test-suite", reference: "security-remediation" },
    domain: "security",
    tier: "pr",
    severity: "blocker",
    status: "active",
    owner: "security",
    sourceOfTruth: "docs/security/rpc-access-manifest.json",
    impact: ["all-users", "tenant-isolation", "customer-data", "compliance-audit"],
    dependsOn: ["security.rbac.hardening"],
  },
  {
    id: "security.typescript.compile",
    implementation: { type: "npm", reference: "ci:tsc" },
    domain: "security",
    tier: "pr",
    severity: "blocker",
    status: "active",
    owner: "platform",
    sourceOfTruth: "tsconfig.json",
    impact: ["developer-experience", "compliance-audit"],
  },
  // —— Data ——
  {
    id: "data.production.readiness",
    implementation: { type: "npm", reference: "production:check" },
    domain: "data",
    tier: "pr",
    severity: "blocker",
    status: "active",
    owner: "database",
    sourceOfTruth: "lib/production/production-readiness.ts",
    impact: ["all-users", "customer-data", "compliance-audit"],
    dependsOn: ["data.supabase.connection"],
  },
  {
    id: "data.supabase.connection",
    implementation: { type: "script", reference: "verify-supabase-ci-env" },
    domain: "data",
    tier: "pr",
    severity: "blocker",
    status: "active",
    owner: "database",
    sourceOfTruth: "scripts/verify-supabase-ci-env.ts",
    impact: ["all-users", "operations"],
  },
  {
    id: "data.publication.sanity",
    implementation: { type: "npm", reference: "ci:supabase:publication" },
    domain: "data",
    tier: "pr",
    severity: "blocker",
    status: "active",
    owner: "database",
    sourceOfTruth: "lib/production/expected-realtime-publication.ts",
    impact: ["operations"],
  },
  {
    id: "data.publication.full",
    implementation: { type: "npm", reference: "ci:supabase:publication:full" },
    domain: "data",
    tier: "cert",
    severity: "blocker",
    status: "active",
    owner: "database",
    sourceOfTruth: "scripts/verify-supabase-publication.ts",
    impact: ["operations", "compliance-audit"],
    dependsOn: ["data.publication.sanity"],
  },
  {
    id: "data.migration.parity",
    implementation: { type: "npm", reference: "ci:supabase:migrations" },
    domain: "data",
    tier: "staging",
    severity: "blocker",
    status: "active",
    owner: "database",
    sourceOfTruth: "scripts/verify-supabase-migration-parity.ts",
    impact: ["all-users", "customer-data"],
  },
  {
    id: "data.release-v2.audit",
    implementation: { type: "npm", reference: "audit:release-v2-db" },
    domain: "data",
    tier: "cert",
    severity: "warning",
    status: "active",
    owner: "database",
    sourceOfTruth: "scripts/audit-release-v2-db.ts",
    impact: ["compliance-audit"],
  },
  {
    id: "governance.audit.write-coverage",
    implementation: { type: "npm", reference: "audit:write-coverage" },
    domain: "data",
    tier: "pr",
    severity: "blocker",
    status: "active",
    owner: "platform",
    sourceOfTruth: "scripts/audit-write-coverage-scan.ts",
    impact: ["compliance-audit", "all-users"],
  },
  // —— Design ——
  {
    id: "design.ux.enforce",
    implementation: { type: "npm", reference: "ux:enforce" },
    domain: "design",
    tier: "pr",
    severity: "blocker",
    status: "active",
    owner: "frontend",
    sourceOfTruth: "scripts/ux-enforcement-check.ts",
    impact: ["developer-experience"],
  },
  {
    id: "design.ui.consistency",
    implementation: { type: "npm", reference: "audit:ui" },
    domain: "design",
    tier: "pr",
    severity: "blocker",
    status: "active",
    owner: "frontend",
    sourceOfTruth: "lib/ui/ui-consistency-audit.ts",
    impact: ["all-users", "developer-experience"],
  },
  {
    id: "design.mobile.gate",
    implementation: { type: "npm", reference: "ux:mobile-gate" },
    domain: "design",
    tier: "pr",
    severity: "blocker",
    status: "active",
    owner: "frontend",
    sourceOfTruth: "scripts/ux-mobile-regression-gate.ts",
    impact: ["all-users"],
  },
  {
    id: "design.ios.static",
    implementation: { type: "npm", reference: "ios:check" },
    domain: "design",
    tier: "pr",
    severity: "blocker",
    status: "active",
    owner: "frontend",
    sourceOfTruth: "scripts/mobile-ios-regression-check.ts",
    impact: ["all-users"],
  },
  {
    id: "design.flex.eslint",
    implementation: { type: "npm", reference: "flex:eslint:gate" },
    domain: "design",
    tier: "pr",
    severity: "blocker",
    status: "active",
    owner: "frontend",
    sourceOfTruth: "lib/ui/flex-system-freeze.ts",
    impact: ["developer-experience"],
  },
  {
    id: "design.flex.freeze",
    implementation: { type: "npm", reference: "flex:freeze:gate" },
    domain: "design",
    tier: "pr",
    severity: "blocker",
    status: "active",
    owner: "frontend",
    sourceOfTruth: "lib/ui/flex-freeze-manifest.ts",
    impact: ["developer-experience"],
    dependsOn: ["design.flex.eslint"],
  },
  {
    id: "design.structural.smoke",
    implementation: { type: "npm", reference: "smoke:structural" },
    domain: "design",
    tier: "pr",
    severity: "blocker",
    status: "active",
    owner: "frontend",
    sourceOfTruth: "lib/ui/modal-size-system.ts",
    impact: ["developer-experience"],
  },
  // —— Domain / build ——
  {
    id: "domain.build.production",
    implementation: { type: "npm", reference: "ci:build" },
    domain: "domain",
    tier: "pr",
    severity: "blocker",
    status: "active",
    owner: "platform",
    sourceOfTruth: "next.config.ts",
    impact: ["all-users", "operations"],
    dependsOn: ["security.typescript.compile"],
  },
  // —— Runtime ——
  {
    id: "runtime.regression.p0",
    implementation: { type: "test-suite", reference: "regression-p0" },
    domain: "runtime",
    tier: "pr",
    severity: "blocker",
    status: "active",
    owner: "platform",
    sourceOfTruth: "lib/control/suites/regression-p0.suite.ts",
    impact: ["all-users", "customer-data", "billing"],
    runtimeCategory: "correctness",
  },
  {
    id: "runtime.regression.p1",
    implementation: { type: "test-suite", reference: "regression-p1" },
    domain: "runtime",
    tier: "cert",
    severity: "blocker",
    status: "active",
    owner: "platform",
    sourceOfTruth: "lib/control/suites/regression-p1.suite.ts",
    impact: ["operations", "billing"],
    runtimeCategory: "correctness",
    dependsOn: ["runtime.regression.p0"],
  },
  {
    id: "runtime.regression.p2",
    implementation: { type: "test-suite", reference: "regression-p2" },
    domain: "runtime",
    tier: "cert",
    severity: "warning",
    status: "active",
    owner: "frontend",
    sourceOfTruth: "lib/control/suites/regression-p2.suite.ts",
    impact: ["developer-experience"],
    runtimeCategory: "correctness",
  },
  {
    id: "runtime.regression.p3",
    implementation: { type: "test-suite", reference: "regression-p3" },
    domain: "runtime",
    tier: "observe",
    severity: "info",
    status: "active",
    owner: "platform",
    sourceOfTruth: "lib/control/suites/regression-p3.suite.ts",
    impact: ["developer-experience"],
    runtimeCategory: "correctness",
  },
  {
    id: "runtime.e2e.smoke",
    implementation: { type: "npm", reference: "smoke:playwright" },
    domain: "runtime",
    tier: "pr",
    severity: "blocker",
    status: "active",
    owner: "platform",
    sourceOfTruth: "e2e/playwright.config.ts",
    impact: ["all-users", "operations"],
    runtimeCategory: "correctness",
    dependsOn: ["runtime.smoke.preflight"],
  },
  {
    id: "runtime.e2e.cert.mobile",
    implementation: { type: "npm", reference: "smoke:playwright:cert" },
    domain: "runtime",
    tier: "cert",
    severity: "blocker",
    status: "active",
    owner: "frontend",
    sourceOfTruth: "e2e/playwright.mobile-cert.config.ts",
    impact: ["all-users"],
    runtimeCategory: "correctness",
  },
  {
    id: "runtime.e2e.cert.scheda",
    implementation: { type: "npm", reference: "smoke:playwright:scheda-smoke" },
    domain: "runtime",
    tier: "cert",
    severity: "blocker",
    status: "active",
    owner: "frontend",
    sourceOfTruth: "e2e/playwright.mobile-cert.config.ts",
    impact: ["operations"],
    runtimeCategory: "correctness",
  },
  {
    id: "runtime.e2e.cert.ricambio",
    implementation: { type: "npm", reference: "smoke:playwright:ricambio:cert" },
    domain: "runtime",
    tier: "cert",
    severity: "blocker",
    status: "active",
    owner: "domain-owner",
    sourceOfTruth: "e2e/playwright.ricambio-cert.config.ts",
    impact: ["operations"],
    runtimeCategory: "correctness",
  },
  {
    id: "runtime.smoke.preflight",
    implementation: { type: "script", reference: "ci-smoke-preflight-pr" },
    domain: "runtime",
    tier: "pr",
    severity: "blocker",
    status: "active",
    owner: "devops",
    sourceOfTruth: "scripts/ci-smoke-preflight.ts",
    impact: ["operations"],
    runtimeCategory: "reliability",
  },
  {
    id: "runtime.smoke.cleanup",
    implementation: { type: "npm", reference: "smoke:cleanup:apply" },
    domain: "runtime",
    tier: "cert",
    severity: "blocker",
    status: "active",
    owner: "devops",
    sourceOfTruth: "scripts/cleanup-smoke-data.ts",
    impact: ["customer-data", "operations"],
    runtimeCategory: "reliability",
  },
  {
    id: "runtime.smoke.residues",
    implementation: { type: "npm", reference: "audit:smoke:residues" },
    domain: "runtime",
    tier: "cert",
    severity: "warning",
    status: "active",
    owner: "devops",
    sourceOfTruth: "lib/smoke/smoke-data-markers.ts",
    impact: ["customer-data"],
    runtimeCategory: "reliability",
  },
  {
    id: "runtime.session.soak",
    implementation: { type: "npm", reference: "ops:long-session-soak:threshold" },
    domain: "runtime",
    tier: "cert",
    severity: "blocker",
    status: "active",
    owner: "platform",
    sourceOfTruth: "scripts/long-session-soak-audit.ts",
    impact: ["operations"],
    runtimeCategory: "reliability",
  },
  {
    id: "runtime.performance.policy",
    implementation: { type: "test-suite", reference: "performance-governance" },
    domain: "runtime",
    tier: "pr",
    severity: "blocker",
    status: "active",
    owner: "platform",
    sourceOfTruth: "lib/control/suites/performance-governance.suite.ts",
    impact: ["developer-experience", "operations"],
    runtimeCategory: "performance",
    dependsOn: ["domain.build.production"],
  },
  {
    id: "runtime.performance.build-budget",
    implementation: { type: "npm", reference: "ops:build-budget-gate" },
    domain: "runtime",
    tier: "pr",
    severity: "blocker",
    status: "active",
    owner: "platform",
    sourceOfTruth: "scripts/ops/extract-build-budgets.mjs",
    impact: ["operations"],
    runtimeCategory: "performance",
    dependsOn: ["domain.build.production"],
  },
  {
    id: "runtime.performance.lint",
    implementation: { type: "npm", reference: "lint" },
    domain: "runtime",
    tier: "pr",
    severity: "blocker",
    status: "active",
    owner: "platform",
    sourceOfTruth: "eslint.config.mjs",
    impact: ["developer-experience"],
    runtimeCategory: "performance",
  },
  {
    id: "runtime.lint.full",
    implementation: { type: "npm", reference: "lint" },
    domain: "runtime",
    tier: "observe",
    severity: "info",
    status: "active",
    owner: "platform",
    sourceOfTruth: "eslint.config.mjs",
    impact: ["developer-experience"],
    runtimeCategory: "performance",
  },
  {
    id: "runtime.performance.regression",
    implementation: { type: "npm", reference: "ops:performance-regression-check" },
    domain: "runtime",
    tier: "cert",
    severity: "blocker",
    status: "active",
    owner: "platform",
    sourceOfTruth: "scripts/ops/performance-regression-check.mjs",
    impact: ["operations"],
    runtimeCategory: "performance",
  },
  {
    id: "runtime.performance.lighthouse",
    implementation: { type: "npm", reference: "ops:lighthouse-budget" },
    domain: "runtime",
    tier: "cert",
    severity: "warning",
    status: "active",
    owner: "platform",
    sourceOfTruth: "scripts/ops/lighthouse-budget.mjs",
    impact: ["operations"],
    runtimeCategory: "performance",
  },
  {
    id: "runtime.performance.browser-profile",
    implementation: { type: "npm", reference: "ops:performance-trend-report" },
    domain: "runtime",
    tier: "observe",
    severity: "info",
    status: "active",
    owner: "platform",
    sourceOfTruth: "e2e/perf/browser-page-profile.spec.ts",
    impact: ["operations"],
    runtimeCategory: "performance",
  },
  {
    id: "runtime.soak.extended",
    implementation: { type: "npm", reference: "ops:long-session-soak" },
    domain: "runtime",
    tier: "observe",
    severity: "info",
    status: "active",
    owner: "platform",
    sourceOfTruth: "scripts/long-session-soak-audit.ts",
    impact: ["operations"],
    runtimeCategory: "reliability",
  },
  // —— Governance ——
  {
    id: "governance.control.review",
    implementation: { type: "test-suite", reference: "control-review" },
    domain: "governance",
    tier: "pr",
    severity: "blocker",
    status: "active",
    owner: "platform",
    sourceOfTruth: "lib/control/registry.ts",
    impact: ["compliance-audit", "developer-experience"],
  },
  {
    id: "governance.release.contract",
    implementation: { type: "test-suite", reference: "release-ready-contract" },
    domain: "governance",
    tier: "pr",
    severity: "blocker",
    status: "active",
    owner: "platform",
    sourceOfTruth: "docs/release-gate-contract.json",
    impact: ["compliance-audit"],
    dependsOn: ["governance.control.review"],
  },
  {
    id: "governance.regression.classification",
    implementation: { type: "test-suite", reference: "regression-classification" },
    domain: "governance",
    tier: "pr",
    severity: "blocker",
    status: "active",
    owner: "platform",
    sourceOfTruth: "lib/regression/smoke-regression-lists.ts",
    impact: ["compliance-audit"],
  },
  {
    id: "governance.production.certification",
    implementation: { type: "script", reference: "control-certify" },
    domain: "governance",
    tier: "production",
    severity: "blocker",
    status: "active",
    owner: "platform",
    sourceOfTruth: "lib/control/contract.ts",
    impact: ["compliance-audit"],
    dependsOn: ["data.production.readiness", "data.publication.full"],
  },
  {
    id: "governance.rbac.sync-check",
    implementation: { type: "test-suite", reference: "rbac-sync-check" },
    domain: "governance",
    tier: "observe",
    severity: "warning",
    status: "experimental",
    owner: "security",
    sourceOfTruth: "src/lib/rbac/resolve-page-access.ts",
    impact: ["tenant-isolation", "compliance-audit"],
  },
  {
    id: "governance.control.coverage",
    implementation: { type: "test-suite", reference: "control-coverage" },
    domain: "governance",
    tier: "pr",
    severity: "warning",
    status: "active",
    owner: "platform",
    sourceOfTruth: "lib/control/coverage-map.ts",
    impact: ["compliance-audit", "developer-experience"],
  },
  {
    id: "governance.control.owner",
    implementation: { type: "test-suite", reference: "control-owner" },
    domain: "governance",
    tier: "observe",
    severity: "warning",
    status: "active",
    owner: "platform",
    sourceOfTruth: "lib/control/owners.ts",
    impact: ["compliance-audit"],
  },
  {
    id: "governance.notification.ssot",
    implementation: { type: "test-suite", reference: "notification-ssot" },
    domain: "governance",
    tier: "pr",
    severity: "blocker",
    status: "active",
    owner: "platform",
    sourceOfTruth: "lib/notifications/application/notification-service.ts",
    impact: ["all-users", "operations"],
  },
  {
    id: "governance.notification.catalog",
    implementation: { type: "test-suite", reference: "notification-catalog-completeness" },
    domain: "governance",
    tier: "pr",
    severity: "blocker",
    status: "active",
    owner: "platform",
    sourceOfTruth: "lib/notifications/notification-event-catalog.ts",
    impact: ["all-users", "operations"],
  },
  {
    id: "governance.registry.size",
    implementation: { type: "test-suite", reference: "registry-lifecycle" },
    domain: "governance",
    tier: "observe",
    severity: "warning",
    status: "active",
    owner: "platform",
    sourceOfTruth: "lib/control/registry.ts",
    impact: ["developer-experience", "compliance-audit"],
  },
  {
    id: "governance.ai.runtime",
    implementation: { type: "test-suite", reference: "ai-runtime" },
    domain: "governance",
    tier: "pr",
    severity: "blocker",
    status: "active",
    owner: "platform",
    sourceOfTruth: "lib/ai/runtime/service.ts",
    impact: ["customer-data", "operations", "compliance-audit", "developer-experience"],
  },
  {
    id: "governance.lifecycle.deprecated",
    implementation: { type: "test-suite", reference: "registry-lifecycle" },
    domain: "governance",
    tier: "observe",
    severity: "warning",
    status: "active",
    owner: "platform",
    sourceOfTruth: "lib/control/registry.ts",
    impact: ["compliance-audit"],
  },
  {
    id: "governance.report.v2.contracts",
    implementation: { type: "test-suite", reference: "report-v2-contracts" },
    domain: "governance",
    tier: "pr",
    severity: "blocker",
    status: "active",
    owner: "platform",
    sourceOfTruth: "lib/report/contracts/index.ts",
    impact: ["compliance-audit", "developer-experience"],
  },
  {
    id: "governance.report.v2.datasets",
    implementation: { type: "test-suite", reference: "report-v2-datasets" },
    domain: "governance",
    tier: "pr",
    severity: "blocker",
    status: "active",
    owner: "platform",
    sourceOfTruth: "lib/report/datasets/index.ts",
    impact: ["compliance-audit", "developer-experience", "customer-data"],
  },
  {
    id: "governance.report.v2.semantic-contract",
    implementation: { type: "test-suite", reference: "report-v2-semantic-contract" },
    domain: "governance",
    tier: "pr",
    severity: "blocker",
    status: "active",
    owner: "platform",
    sourceOfTruth: "lib/report/datasets/index.ts",
    impact: ["compliance-audit", "developer-experience"],
  },
  {
    id: "governance.report.v2.executive-contract",
    implementation: { type: "test-suite", reference: "report-v2-executive-contract" },
    domain: "governance",
    tier: "pr",
    severity: "blocker",
    status: "active",
    owner: "platform",
    sourceOfTruth: "lib/report/executive/index.ts",
    impact: ["compliance-audit", "developer-experience"],
  },
  {
    id: "governance.report.v2.executive-boundary",
    implementation: { type: "test-suite", reference: "report-v2-executive-boundary" },
    domain: "governance",
    tier: "pr",
    severity: "blocker",
    status: "active",
    owner: "platform",
    sourceOfTruth: "components/report/executive",
    impact: ["compliance-audit", "developer-experience"],
  },
  {
    id: "governance.report.v2.executive-hardening",
    implementation: { type: "test-suite", reference: "report-v2-executive-hardening" },
    domain: "governance",
    tier: "pr",
    severity: "blocker",
    status: "active",
    owner: "platform",
    sourceOfTruth: "lib/report/executive/index.ts",
    impact: ["compliance-audit", "developer-experience"],
    dependsOn: [
      "governance.report.v2.semantic-contract",
      "governance.report.v2.datasets",
      "governance.report.v2.executive-contract",
      "governance.report.v2.executive-boundary",
    ],
  },
  {
    id: "governance.report.v2.executive",
    implementation: { type: "test-suite", reference: "report-v2-executive" },
    domain: "governance",
    tier: "pr",
    severity: "blocker",
    status: "active",
    owner: "platform",
    sourceOfTruth: "lib/report/executive/index.ts",
    impact: ["compliance-audit", "developer-experience", "customer-data"],
  },
  {
    id: "governance.report.v2.cross-contract",
    implementation: { type: "test-suite", reference: "report-v2-cross-contract" },
    domain: "governance",
    tier: "pr",
    severity: "blocker",
    status: "active",
    owner: "platform",
    sourceOfTruth: "lib/report/cross-analysis/index.ts",
    impact: ["compliance-audit", "developer-experience"],
  },
  {
    id: "governance.report.v2.cross-parity",
    implementation: { type: "test-suite", reference: "report-v2-cross-parity" },
    domain: "governance",
    tier: "pr",
    severity: "blocker",
    status: "active",
    owner: "platform",
    sourceOfTruth: "lib/report/cross-analysis/index.ts",
    impact: ["compliance-audit", "developer-experience"],
    dependsOn: ["governance.report.v2.cross-contract"],
  },
  {
    id: "governance.report.v2.cross-analysis",
    implementation: { type: "test-suite", reference: "report-v2-cross-analysis" },
    domain: "governance",
    tier: "pr",
    severity: "blocker",
    status: "active",
    owner: "platform",
    sourceOfTruth: "lib/report/cross-analysis/index.ts",
    impact: ["compliance-audit", "developer-experience", "customer-data"],
    dependsOn: [
      "governance.report.v2.semantic-contract",
      "governance.report.v2.datasets",
      "governance.report.v2.executive-hardening",
      "governance.report.v2.cross-contract",
      "governance.report.v2.cross-parity",
    ],
  },
  {
    id: "governance.report.v2.insight-contract",
    implementation: { type: "test-suite", reference: "report-v2-insight-contract" },
    domain: "governance",
    tier: "pr",
    severity: "blocker",
    status: "active",
    owner: "platform",
    sourceOfTruth: "lib/report/insights/index.ts",
    impact: ["compliance-audit", "developer-experience"],
  },
  {
    id: "governance.report.v2.insight-rules",
    implementation: { type: "test-suite", reference: "report-v2-insight-rules" },
    domain: "governance",
    tier: "pr",
    severity: "blocker",
    status: "active",
    owner: "platform",
    sourceOfTruth: "lib/report/insights/index.ts",
    impact: ["compliance-audit", "developer-experience"],
    dependsOn: ["governance.report.v2.insight-contract"],
  },
  {
    id: "governance.report.v2.insight-engine",
    implementation: { type: "test-suite", reference: "report-v2-insight-engine" },
    domain: "governance",
    tier: "pr",
    severity: "blocker",
    status: "active",
    owner: "platform",
    sourceOfTruth: "lib/report/insights/index.ts",
    impact: ["compliance-audit", "developer-experience"],
    dependsOn: ["governance.report.v2.insight-contract", "governance.report.v2.insight-rules"],
  },
  {
    id: "governance.report.v2.insight-analysis",
    implementation: { type: "test-suite", reference: "report-v2-insight-analysis" },
    domain: "governance",
    tier: "pr",
    severity: "blocker",
    status: "active",
    owner: "platform",
    sourceOfTruth: "lib/report/insights/index.ts",
    impact: ["compliance-audit", "developer-experience", "customer-data"],
    dependsOn: [
      "governance.report.v2.semantic-contract",
      "governance.report.v2.datasets",
      "governance.report.v2.cross-analysis",
      "governance.report.v2.insight-contract",
      "governance.report.v2.insight-rules",
      "governance.report.v2.insight-engine",
    ],
  },
  {
    id: "governance.report.v2.insight-hardening",
    implementation: { type: "test-suite", reference: "report-v2-insight-hardening" },
    domain: "governance",
    tier: "pr",
    severity: "blocker",
    status: "active",
    owner: "platform",
    sourceOfTruth: "lib/report/insights/index.ts",
    impact: ["compliance-audit", "developer-experience"],
    dependsOn: [
      "governance.report.v2.insight-contract",
      "governance.report.v2.insight-engine",
      "governance.report.v2.insight-analysis",
    ],
  },
  {
    id: "governance.report.v2.ai-context",
    implementation: { type: "test-suite", reference: "report-v2-ai-context" },
    domain: "governance",
    tier: "pr",
    severity: "blocker",
    status: "active",
    owner: "platform",
    sourceOfTruth: "lib/report/ai-context/index.ts",
    impact: ["compliance-audit", "developer-experience"],
    dependsOn: ["governance.report.v2.insight-hardening"],
  },
  {
    id: "governance.report.v2.narrative-contract",
    implementation: { type: "test-suite", reference: "report-v2-narrative-contract" },
    domain: "governance",
    tier: "pr",
    severity: "blocker",
    status: "active",
    owner: "platform",
    sourceOfTruth: "lib/report/narrative/index.ts",
    impact: ["compliance-audit", "developer-experience"],
    dependsOn: ["governance.report.v2.ai-context"],
  },
  {
    id: "governance.report.v2.narrative-provider",
    implementation: { type: "test-suite", reference: "report-v2-narrative-provider" },
    domain: "governance",
    tier: "pr",
    severity: "blocker",
    status: "active",
    owner: "platform",
    sourceOfTruth: "lib/report/narrative/providers/gemini-adapter.ts",
    impact: ["compliance-audit", "developer-experience"],
    dependsOn: ["governance.report.v2.narrative-contract"],
  },
  {
    id: "governance.report.v2.narrative-quality",
    implementation: { type: "test-suite", reference: "report-v2-narrative-quality" },
    domain: "governance",
    tier: "pr",
    severity: "blocker",
    status: "active",
    owner: "platform",
    sourceOfTruth: "lib/report/narrative/quality/validate-narrative-quality.ts",
    impact: ["compliance-audit", "developer-experience"],
    dependsOn: [
      "governance.report.v2.narrative-contract",
      "governance.report.v2.narrative-provider",
    ],
  },
  {
    id: "governance.report.v2.narrative-consumer",
    implementation: { type: "test-suite", reference: "report-v2-narrative-consumer" },
    domain: "governance",
    tier: "pr",
    severity: "blocker",
    status: "active",
    owner: "platform",
    sourceOfTruth: "lib/report/narrative/api/report-narrative-api.ts",
    impact: ["compliance-audit", "developer-experience"],
    dependsOn: [
      "governance.report.v2.narrative-provider",
      "governance.report.v2.narrative-quality",
    ],
  },
  {
    id: "governance.report.v2.narrative-preflight",
    implementation: { type: "test-suite", reference: "report-v2-narrative-preflight" },
    domain: "governance",
    tier: "pr",
    severity: "blocker",
    status: "active",
    owner: "platform",
    sourceOfTruth: "lib/feature-flags/report-v2-flag.ts",
    impact: ["compliance-audit", "developer-experience"],
    dependsOn: ["governance.report.v2.narrative-consumer"],
  },
  {
    id: "governance.report.v2.narrative-rollout",
    implementation: { type: "test-suite", reference: "report-v2-narrative-rollout" },
    domain: "governance",
    tier: "pr",
    severity: "blocker",
    status: "active",
    owner: "platform",
    sourceOfTruth: "lib/feature-flags/report-v2-flag.ts",
    impact: ["compliance-audit", "developer-experience"],
    dependsOn: ["governance.report.v2.narrative-preflight"],
  },
  {
    id: "governance.report.p4.business-report",
    implementation: { type: "test-suite", reference: "report-p4-business-report" },
    domain: "governance",
    tier: "pr",
    severity: "blocker",
    status: "active",
    owner: "platform",
    sourceOfTruth: "lib/report/business-report/pipeline/generate-business-report.ts",
    impact: ["compliance-audit", "developer-experience"],
    dependsOn: ["governance.report.v2.narrative-rollout"],
  },
  {
    id: "governance.report.p5.operational-context",
    implementation: { type: "test-suite", reference: "report-p5-operational-context" },
    domain: "governance",
    tier: "pr",
    severity: "blocker",
    status: "active",
    owner: "platform",
    sourceOfTruth: "lib/report/operational-context/build-report-operational-context.server.ts",
    impact: ["compliance-audit", "developer-experience"],
    dependsOn: ["governance.report.p4.business-report"],
  },
  {
    id: "governance.report.p6.advanced-bi",
    implementation: { type: "test-suite", reference: "report-p6-advanced-bi" },
    domain: "governance",
    tier: "pr",
    severity: "blocker",
    status: "active",
    owner: "platform",
    sourceOfTruth: "components/report/report-hub-view.tsx",
    impact: ["compliance-audit", "developer-experience"],
    dependsOn: ["governance.report.p5.operational-context"],
  },
  {
    id: "governance.report.p7.decision-center",
    implementation: { type: "test-suite", reference: "report-p7-decision-center" },
    domain: "governance",
    tier: "pr",
    severity: "blocker",
    status: "active",
    owner: "platform",
    sourceOfTruth: "lib/report/decision-center/api/report-decision-center-api.server.ts",
    impact: ["compliance-audit", "developer-experience"],
    dependsOn: ["governance.report.p6.advanced-bi"],
  },
  {
    id: "governance.report.p8.ask-report",
    implementation: { type: "test-suite", reference: "report-p8-ask-report" },
    domain: "governance",
    tier: "pr",
    severity: "blocker",
    status: "active",
    owner: "platform",
    sourceOfTruth: "lib/report/ask-report/api/report-ask-report-api.server.ts",
    impact: ["compliance-audit", "developer-experience"],
    dependsOn: ["governance.report.p7.decision-center"],
  },
  {
    id: "governance.report.data-integration",
    implementation: { type: "test-suite", reference: "report-data-integration" },
    domain: "governance",
    tier: "pr",
    severity: "blocker",
    status: "active",
    owner: "platform",
    sourceOfTruth: "docs/report-data-inventory.md",
    impact: ["compliance-audit", "developer-experience"],
    dependsOn: ["governance.report.p8.ask-report"],
  },
  {
    id: "governance.report.data-completion",
    implementation: { type: "test-suite", reference: "report-data-completion" },
    domain: "governance",
    tier: "pr",
    severity: "blocker",
    status: "active",
    owner: "platform",
    sourceOfTruth: "docs/report-data-completion-completion-report.md",
    impact: ["compliance-audit", "developer-experience"],
    dependsOn: ["governance.report.data-integration"],
  },
  {
    id: "governance.report.legacy-consolidation",
    implementation: { type: "test-suite", reference: "report-legacy-consolidation" },
    domain: "governance",
    tier: "pr",
    severity: "blocker",
    status: "active",
    owner: "platform",
    sourceOfTruth: "docs/report-legacy-consolidation-completion-report.md",
    impact: ["compliance-audit", "developer-experience"],
    dependsOn: ["governance.report.data-completion"],
  },
  {
    id: "governance.report.p9.legacy-elimination",
    implementation: { type: "test-suite", reference: "report-p9-legacy-elimination" },
    domain: "governance",
    tier: "pr",
    severity: "blocker",
    status: "active",
    owner: "platform",
    sourceOfTruth: "docs/report-p9-completion-report.md",
    impact: ["compliance-audit", "developer-experience"],
    dependsOn: ["governance.report.legacy-consolidation"],
  },
  {
    id: "governance.report.p10.data-ux",
    implementation: { type: "test-suite", reference: "report-p10-data-ux" },
    domain: "governance",
    tier: "pr",
    severity: "blocker",
    status: "active",
    owner: "platform",
    sourceOfTruth: "docs/report-p10-completion-report.md",
    impact: ["compliance-audit", "developer-experience"],
    dependsOn: ["governance.report.p9.legacy-elimination"],
  },
  // —— Deprecated ——
  {
    id: "formux.promotion.gate",
    implementation: { type: "test-suite", reference: "formux-promotion" },
    domain: "governance",
    tier: "observe",
    severity: "info",
    status: "deprecated",
    owner: "platform",
    sourceOfTruth: "lib/form-ux-migration/form-ux-promotion-gates.ts",
    impact: ["developer-experience"],
    sunsetDate: "2026-09-01",
  },
] as const;

export function getControlById(id: string): ControlDefinition | undefined {
  return CONTROL_REGISTRY.find((c) => c.id === id);
}

export function controlsForTier(tier: ControlDefinition["tier"]): ControlDefinition[] {
  return CONTROL_REGISTRY.filter((c) => c.tier === tier && c.status !== "sunset" && c.status !== "disabled");
}
