import type { ControlDefinition } from "./types";

/**
 * Governance metadata only — no test lists, no script imports.
 * Keep human-readable; target <200 lines.
 */
export const CONTROL_REGISTRY: readonly ControlDefinition[] = [
  // —— Security ——
  {
    id: "security.rbac.matrix",
    implementation: { type: "test-suite", reference: "security-rbac" },
    domain: "security",
    tier: "pr",
    severity: "blocker",
    status: "active",
    owner: "security",
    sourceOfTruth: "src/lib/rbac/resolve-page-access.ts",
    impact: ["all-users", "tenant-isolation", "customer-data"],
  },
  {
    id: "security.rbac.hardening",
    implementation: { type: "test-suite", reference: "security-rbac-hardening" },
    domain: "security",
    tier: "pr",
    severity: "blocker",
    status: "active",
    owner: "security",
    sourceOfTruth: "src/lib/auth/server-permission-guards.ts",
    impact: ["all-users", "tenant-isolation"],
    dependsOn: ["security.rbac.matrix"],
  },
  {
    id: "security.typescript.compile",
    implementation: { type: "npm", reference: "ci:tsc" },
    domain: "security",
    tier: "pr",
    severity: "blocker",
    status: "active",
    owner: "platform",
    sourceOfTruth: "tsconfig.json",
    impact: ["developer-experience", "compliance-audit"],
  },
  // —— Data ——
  {
    id: "data.production.readiness",
    implementation: { type: "npm", reference: "production:check" },
    domain: "data",
    tier: "pr",
    severity: "blocker",
    status: "active",
    owner: "database",
    sourceOfTruth: "lib/production/production-readiness.ts",
    impact: ["all-users", "customer-data", "compliance-audit"],
    dependsOn: ["data.supabase.connection"],
  },
  {
    id: "data.supabase.connection",
    implementation: { type: "script", reference: "verify-supabase-ci-env" },
    domain: "data",
    tier: "pr",
    severity: "blocker",
    status: "active",
    owner: "database",
    sourceOfTruth: "scripts/verify-supabase-ci-env.ts",
    impact: ["all-users", "operations"],
  },
  {
    id: "data.publication.sanity",
    implementation: { type: "npm", reference: "ci:supabase:publication" },
    domain: "data",
    tier: "pr",
    severity: "blocker",
    status: "active",
    owner: "database",
    sourceOfTruth: "lib/production/expected-realtime-publication.ts",
    impact: ["operations"],
  },
  {
    id: "data.publication.full",
    implementation: { type: "npm", reference: "ci:supabase:publication:full" },
    domain: "data",
    tier: "cert",
    severity: "blocker",
    status: "active",
    owner: "database",
    sourceOfTruth: "scripts/verify-supabase-publication.ts",
    impact: ["operations", "compliance-audit"],
    dependsOn: ["data.publication.sanity"],
  },
  {
    id: "data.migration.parity",
    implementation: { type: "npm", reference: "ci:supabase:migrations" },
    domain: "data",
    tier: "staging",
    severity: "blocker",
    status: "active",
    owner: "database",
    sourceOfTruth: "scripts/verify-supabase-migration-parity.ts",
    impact: ["all-users", "customer-data"],
  },
  {
    id: "data.release-v2.audit",
    implementation: { type: "npm", reference: "audit:release-v2-db" },
    domain: "data",
    tier: "cert",
    severity: "warning",
    status: "active",
    owner: "database",
    sourceOfTruth: "scripts/audit-release-v2-db.ts",
    impact: ["compliance-audit"],
  },
  // —— Design ——
  {
    id: "design.ux.enforce",
    implementation: { type: "npm", reference: "ux:enforce" },
    domain: "design",
    tier: "pr",
    severity: "blocker",
    status: "active",
    owner: "frontend",
    sourceOfTruth: "scripts/ux-enforcement-check.ts",
    impact: ["developer-experience"],
  },
  {
    id: "design.ui.consistency",
    implementation: { type: "npm", reference: "audit:ui" },
    domain: "design",
    tier: "pr",
    severity: "blocker",
    status: "active",
    owner: "frontend",
    sourceOfTruth: "lib/ui/ui-consistency-audit.ts",
    impact: ["all-users", "developer-experience"],
  },
  {
    id: "design.mobile.gate",
    implementation: { type: "npm", reference: "ux:mobile-gate" },
    domain: "design",
    tier: "pr",
    severity: "blocker",
    status: "active",
    owner: "frontend",
    sourceOfTruth: "scripts/ux-mobile-regression-gate.ts",
    impact: ["all-users"],
  },
  {
    id: "design.ios.static",
    implementation: { type: "npm", reference: "ios:check" },
    domain: "design",
    tier: "pr",
    severity: "blocker",
    status: "active",
    owner: "frontend",
    sourceOfTruth: "scripts/mobile-ios-regression-check.ts",
    impact: ["all-users"],
  },
  {
    id: "design.flex.eslint",
    implementation: { type: "npm", reference: "flex:eslint:gate" },
    domain: "design",
    tier: "pr",
    severity: "blocker",
    status: "active",
    owner: "frontend",
    sourceOfTruth: "lib/ui/flex-system-freeze.ts",
    impact: ["developer-experience"],
  },
  {
    id: "design.flex.freeze",
    implementation: { type: "npm", reference: "flex:freeze:gate" },
    domain: "design",
    tier: "pr",
    severity: "blocker",
    status: "active",
    owner: "frontend",
    sourceOfTruth: "lib/ui/flex-freeze-manifest.ts",
    impact: ["developer-experience"],
    dependsOn: ["design.flex.eslint"],
  },
  {
    id: "design.structural.smoke",
    implementation: { type: "npm", reference: "smoke:structural" },
    domain: "design",
    tier: "pr",
    severity: "blocker",
    status: "active",
    owner: "frontend",
    sourceOfTruth: "lib/ui/modal-size-system.ts",
    impact: ["developer-experience"],
  },
  // —— Domain / build ——
  {
    id: "domain.build.production",
    implementation: { type: "npm", reference: "ci:build" },
    domain: "domain",
    tier: "pr",
    severity: "blocker",
    status: "active",
    owner: "platform",
    sourceOfTruth: "next.config.ts",
    impact: ["all-users", "operations"],
    dependsOn: ["security.typescript.compile"],
  },
  // —— Runtime ——
  {
    id: "runtime.regression.p0",
    implementation: { type: "test-suite", reference: "regression-p0" },
    domain: "runtime",
    tier: "pr",
    severity: "blocker",
    status: "active",
    owner: "platform",
    sourceOfTruth: "lib/control/suites/regression-p0.suite.ts",
    impact: ["all-users", "customer-data", "billing"],
    runtimeCategory: "correctness",
  },
  {
    id: "runtime.regression.p1",
    implementation: { type: "test-suite", reference: "regression-p1" },
    domain: "runtime",
    tier: "cert",
    severity: "blocker",
    status: "active",
    owner: "platform",
    sourceOfTruth: "lib/control/suites/regression-p1.suite.ts",
    impact: ["operations", "billing"],
    runtimeCategory: "correctness",
    dependsOn: ["runtime.regression.p0"],
  },
  {
    id: "runtime.regression.p2",
    implementation: { type: "test-suite", reference: "regression-p2" },
    domain: "runtime",
    tier: "cert",
    severity: "warning",
    status: "active",
    owner: "frontend",
    sourceOfTruth: "lib/control/suites/regression-p2.suite.ts",
    impact: ["developer-experience"],
    runtimeCategory: "correctness",
  },
  {
    id: "runtime.regression.p3",
    implementation: { type: "test-suite", reference: "regression-p3" },
    domain: "runtime",
    tier: "observe",
    severity: "info",
    status: "active",
    owner: "platform",
    sourceOfTruth: "lib/control/suites/regression-p3.suite.ts",
    impact: ["developer-experience"],
    runtimeCategory: "correctness",
  },
  {
    id: "runtime.e2e.smoke",
    implementation: { type: "npm", reference: "smoke:playwright" },
    domain: "runtime",
    tier: "pr",
    severity: "blocker",
    status: "active",
    owner: "platform",
    sourceOfTruth: "e2e/playwright.config.ts",
    impact: ["all-users", "operations"],
    runtimeCategory: "correctness",
    dependsOn: ["runtime.smoke.preflight"],
  },
  {
    id: "runtime.e2e.cert.mobile",
    implementation: { type: "npm", reference: "smoke:playwright:cert" },
    domain: "runtime",
    tier: "cert",
    severity: "blocker",
    status: "active",
    owner: "frontend",
    sourceOfTruth: "e2e/playwright.mobile-cert.config.ts",
    impact: ["all-users"],
    runtimeCategory: "correctness",
  },
  {
    id: "runtime.e2e.cert.scheda",
    implementation: { type: "npm", reference: "smoke:playwright:scheda-smoke" },
    domain: "runtime",
    tier: "cert",
    severity: "blocker",
    status: "active",
    owner: "frontend",
    sourceOfTruth: "e2e/playwright.mobile-cert.config.ts",
    impact: ["operations"],
    runtimeCategory: "correctness",
  },
  {
    id: "runtime.e2e.cert.ricambio",
    implementation: { type: "npm", reference: "smoke:playwright:ricambio:cert" },
    domain: "runtime",
    tier: "cert",
    severity: "blocker",
    status: "active",
    owner: "domain-owner",
    sourceOfTruth: "e2e/playwright.ricambio-cert.config.ts",
    impact: ["operations"],
    runtimeCategory: "correctness",
  },
  {
    id: "runtime.smoke.preflight",
    implementation: { type: "script", reference: "ci-smoke-preflight-pr" },
    domain: "runtime",
    tier: "pr",
    severity: "blocker",
    status: "active",
    owner: "devops",
    sourceOfTruth: "scripts/ci-smoke-preflight.ts",
    impact: ["operations"],
    runtimeCategory: "reliability",
  },
  {
    id: "runtime.smoke.cleanup",
    implementation: { type: "npm", reference: "smoke:cleanup:apply" },
    domain: "runtime",
    tier: "cert",
    severity: "blocker",
    status: "active",
    owner: "devops",
    sourceOfTruth: "scripts/cleanup-smoke-data.ts",
    impact: ["customer-data", "operations"],
    runtimeCategory: "reliability",
  },
  {
    id: "runtime.smoke.residues",
    implementation: { type: "npm", reference: "audit:smoke:residues" },
    domain: "runtime",
    tier: "cert",
    severity: "warning",
    status: "active",
    owner: "devops",
    sourceOfTruth: "lib/smoke/smoke-data-markers.ts",
    impact: ["customer-data"],
    runtimeCategory: "reliability",
  },
  {
    id: "runtime.session.soak",
    implementation: { type: "npm", reference: "ops:long-session-soak:threshold" },
    domain: "runtime",
    tier: "cert",
    severity: "blocker",
    status: "active",
    owner: "platform",
    sourceOfTruth: "scripts/long-session-soak-audit.ts",
    impact: ["operations"],
    runtimeCategory: "reliability",
  },
  {
    id: "runtime.performance.policy",
    implementation: { type: "test-suite", reference: "performance-governance" },
    domain: "runtime",
    tier: "pr",
    severity: "blocker",
    status: "active",
    owner: "platform",
    sourceOfTruth: "lib/control/suites/performance-governance.suite.ts",
    impact: ["developer-experience", "operations"],
    runtimeCategory: "performance",
    dependsOn: ["domain.build.production"],
  },
  {
    id: "runtime.performance.build-budget",
    implementation: { type: "npm", reference: "ops:build-budget-gate" },
    domain: "runtime",
    tier: "pr",
    severity: "blocker",
    status: "active",
    owner: "platform",
    sourceOfTruth: "scripts/ops/extract-build-budgets.mjs",
    impact: ["operations"],
    runtimeCategory: "performance",
    dependsOn: ["domain.build.production"],
  },
  {
    id: "runtime.performance.lint",
    implementation: { type: "npm", reference: "lint" },
    domain: "runtime",
    tier: "pr",
    severity: "blocker",
    status: "active",
    owner: "platform",
    sourceOfTruth: "eslint.config.mjs",
    impact: ["developer-experience"],
    runtimeCategory: "performance",
  },
  {
    id: "runtime.lint.full",
    implementation: { type: "npm", reference: "lint" },
    domain: "runtime",
    tier: "observe",
    severity: "info",
    status: "active",
    owner: "platform",
    sourceOfTruth: "eslint.config.mjs",
    impact: ["developer-experience"],
    runtimeCategory: "performance",
  },
  {
    id: "runtime.performance.regression",
    implementation: { type: "npm", reference: "ops:performance-regression-check" },
    domain: "runtime",
    tier: "cert",
    severity: "blocker",
    status: "active",
    owner: "platform",
    sourceOfTruth: "scripts/ops/performance-regression-check.mjs",
    impact: ["operations"],
    runtimeCategory: "performance",
  },
  {
    id: "runtime.performance.lighthouse",
    implementation: { type: "npm", reference: "ops:lighthouse-budget" },
    domain: "runtime",
    tier: "cert",
    severity: "warning",
    status: "active",
    owner: "platform",
    sourceOfTruth: "scripts/ops/lighthouse-budget.mjs",
    impact: ["operations"],
    runtimeCategory: "performance",
  },
  {
    id: "runtime.performance.browser-profile",
    implementation: { type: "npm", reference: "ops:performance-trend-report" },
    domain: "runtime",
    tier: "observe",
    severity: "info",
    status: "active",
    owner: "platform",
    sourceOfTruth: "e2e/perf/browser-page-profile.spec.ts",
    impact: ["operations"],
    runtimeCategory: "performance",
  },
  {
    id: "runtime.soak.extended",
    implementation: { type: "npm", reference: "ops:long-session-soak" },
    domain: "runtime",
    tier: "observe",
    severity: "info",
    status: "active",
    owner: "platform",
    sourceOfTruth: "scripts/long-session-soak-audit.ts",
    impact: ["operations"],
    runtimeCategory: "reliability",
  },
  // —— Governance ——
  {
    id: "governance.control.review",
    implementation: { type: "test-suite", reference: "control-review" },
    domain: "governance",
    tier: "pr",
    severity: "blocker",
    status: "active",
    owner: "platform",
    sourceOfTruth: "lib/control/registry.ts",
    impact: ["compliance-audit", "developer-experience"],
  },
  {
    id: "governance.regression.classification",
    implementation: { type: "test-suite", reference: "regression-classification" },
    domain: "governance",
    tier: "pr",
    severity: "blocker",
    status: "active",
    owner: "platform",
    sourceOfTruth: "lib/regression/smoke-regression-lists.ts",
    impact: ["compliance-audit"],
  },
  {
    id: "governance.production.certification",
    implementation: { type: "script", reference: "control-certify" },
    domain: "governance",
    tier: "production",
    severity: "blocker",
    status: "active",
    owner: "platform",
    sourceOfTruth: "lib/control/contract.ts",
    impact: ["compliance-audit"],
    dependsOn: ["data.production.readiness", "data.publication.full"],
  },
  {
    id: "governance.rbac.sync-check",
    implementation: { type: "test-suite", reference: "rbac-sync-check" },
    domain: "governance",
    tier: "observe",
    severity: "warning",
    status: "experimental",
    owner: "security",
    sourceOfTruth: "src/lib/rbac/resolve-page-access.ts",
    impact: ["tenant-isolation", "compliance-audit"],
  },
  {
    id: "governance.control.coverage",
    implementation: { type: "test-suite", reference: "control-coverage" },
    domain: "governance",
    tier: "pr",
    severity: "warning",
    status: "active",
    owner: "platform",
    sourceOfTruth: "lib/control/coverage-map.ts",
    impact: ["compliance-audit", "developer-experience"],
  },
  {
    id: "governance.control.owner",
    implementation: { type: "test-suite", reference: "control-owner" },
    domain: "governance",
    tier: "observe",
    severity: "warning",
    status: "active",
    owner: "platform",
    sourceOfTruth: "lib/control/owners.ts",
    impact: ["compliance-audit"],
  },
  {
    id: "governance.registry.size",
    implementation: { type: "test-suite", reference: "registry-lifecycle" },
    domain: "governance",
    tier: "observe",
    severity: "warning",
    status: "active",
    owner: "platform",
    sourceOfTruth: "lib/control/registry.ts",
    impact: ["developer-experience", "compliance-audit"],
  },
  {
    id: "governance.lifecycle.deprecated",
    implementation: { type: "test-suite", reference: "registry-lifecycle" },
    domain: "governance",
    tier: "observe",
    severity: "warning",
    status: "active",
    owner: "platform",
    sourceOfTruth: "lib/control/registry.ts",
    impact: ["compliance-audit"],
  },
  // —— Deprecated ——
  {
    id: "formux.promotion.gate",
    implementation: { type: "test-suite", reference: "formux-promotion" },
    domain: "governance",
    tier: "observe",
    severity: "info",
    status: "deprecated",
    owner: "platform",
    sourceOfTruth: "lib/form-ux-migration/form-ux-promotion-gates.ts",
    impact: ["developer-experience"],
    sunsetDate: "2026-09-01",
  },
] as const;

export function getControlById(id: string): ControlDefinition | undefined {
  return CONTROL_REGISTRY.find((c) => c.id === id);
}

export function controlsForTier(tier: ControlDefinition["tier"]): ControlDefinition[] {
  return CONTROL_REGISTRY.filter((c) => c.tier === tier && c.status !== "sunset" && c.status !== "disabled");
}
