/** Performance governance v6 — static policy suite (PR blocking). */
export const PERFORMANCE_GOVERNANCE_SUITE: readonly string[] = [
  "lib/regression/performance-policy.test.ts",
  "lib/regression/performance-budget-registry.test.ts",
  "lib/regression/performance-regression-guard.test.ts",
  "lib/regression/performance-lint-policy.test.ts",
  "lib/regression/performance-score.test.ts",
  "lib/regression/agenda-perf-policy.test.ts",
  "lib/regression/client-portal-perf-policy.test.ts",
  "lib/regression/dashboard-perf-policy.test.ts",
  "lib/regression/dipendenti-perf-policy.test.ts",
  "lib/regression/documenti-perf-policy.test.ts",
  "lib/regression/fatturazione-perf-policy.test.ts",
  "lib/regression/impostazioni-perf-policy.test.ts",
  "lib/regression/lavorazioni-perf-policy.test.ts",
  "lib/regression/magazzino-perf-policy.test.ts",
  "lib/regression/mezzi-perf-policy.test.ts",
  "lib/regression/preventivi-perf-policy.test.ts",
  "lib/regression/public-surfaces-perf-policy.test.ts",
  "lib/regression/report-perf-policy.test.ts",
  "lib/regression/sicurezza-perf-policy.test.ts",
  "lib/regression/shared-components-perf-policy.test.ts",
  "lib/regression/performance-closure-audit.test.ts",
];
