/**
 * Generate explicit REVOKE/GRANT SQL from docs/security/rpc-access-manifest.json (SSOT).
 * Run: npx tsx scripts/generate-rpc-grants-sql.ts
 * Output: supabase/migrations/20261226120201_security_definer_grants_from_manifest.sql
 */
import fs from "node:fs";
import path from "node:path";

const ROOT = process.cwd();
const MANIFEST_PATH = path.join(ROOT, "docs/security/rpc-access-manifest.json");
const OUT_PATH = path.join(
  ROOT,
  "supabase/migrations/20261226120201_security_definer_grants_from_manifest.sql",
);

type ManifestEntry = {
  classification: string;
  grants: ("anon" | "authenticated" | "service_role")[];
};

function parseFnKey(key: string): { name: string; args: string } {
  const open = key.indexOf("(");
  if (open === -1) return { name: key, args: "" };
  const name = key.slice(0, open);
  const args = key.slice(open + 1, key.lastIndexOf(")"));
  return { name, args };
}

function main(): void {
  const manifest = JSON.parse(fs.readFileSync(MANIFEST_PATH, "utf8")) as {
    entries: Record<string, ManifestEntry>;
  };

  const lines: string[] = [
    "-- GENERATED by scripts/generate-rpc-grants-sql.ts — do not edit by hand.",
    "-- SSOT: docs/security/rpc-access-manifest.json",
    "-- Re-run generator after manifest changes; security-migration-gate enforces sync.",
    "",
  ];

  const keys = Object.keys(manifest.entries).sort();
  for (const key of keys) {
    const entry = manifest.entries[key]!;
    const { name, args } = parseFnKey(key);
    const argsSql = args; // identity args as in pg_get_function_identity_arguments

    lines.push(`-- ${key} [${entry.classification}]`);
    lines.push(
      `revoke all on function public.${name}(${argsSql}) from public, anon, authenticated, service_role;`,
    );

    const grants = [...new Set(entry.grants)];
    if (grants.length === 0) {
      lines.push(`-- ponytail: no EXECUTE grant (internal definer-only caller)`);
    } else {
      for (const role of grants) {
        if (role === "anon") {
          lines.push(`-- security-allowlist: PUBLIC_SAFE manifest entry`);
        }
        lines.push(`grant execute on function public.${name}(${argsSql}) to ${role};`);
      }
    }
    lines.push("");
  }

  lines.push("notify pgrst, 'reload schema';");
  lines.push("");

  fs.writeFileSync(OUT_PATH, lines.join("\n"));
  console.log(`generated ${keys.length} function grants → ${OUT_PATH}`);
}

main();
