/**
 * Template PDF unificato gestionale — layout condiviso (preventivi, consuntivi, schede).
 * Implementazione master: `lib/pdf/preventivo-pdf-layout.ts`.
 */
export {
  PDF_MARGIN_L,
  PDF_MARGIN_R,
  PDF_MARGIN_TOP,
  PDF_FOOTER_Y,
  PDF_SECTION_GAP,
  PDF_SECTION_CONTENT_GAP,
  PDF_COMPANY_NAME,
  PDF_HEADER_BRAND_BLOCK_MM,
  PDF_HEADER_BRAND_MAX_MM,
  PDF_HEADER_BRAND_TITLE_GAP_MM,
  PDF_HEADER_CONTENT_GAP_MM,
  PDF_HEADER_TO_CONTENT_GAP_MM,
  PDF_PREVENTIVO_IVA_PERCENT,
  pdfContentWidth,
  fmtEuroPdf,
  fmtDateIt,
  drawPdfHorizontalRule,
  pdfAdvanceSection,
  pdfAdvanceAfterDocumentHeader,
  drawPdfBrandBlock,
  drawPreventivoPdfHeader,
  drawPreventivoPdfHeader as drawGestionalePdfHeader,
  measureGestionalePdfHeaderEndY,
  drawPdfSectionTitle,
  drawPdfFieldGrid,
  drawPdfLabeledParagraph,
  drawPdfSectionPanelGrid,
  drawPdfSectionPanelParagraphs,
  drawPdfIdentificationBlock,
  pdfTableDefaults,
  pdfPreventivoVoceTableColumns,
  getAutoTableFinalY,
  ensurePdfSpace,
  drawPdfTotalsSummary,
  drawPdfPageFooters,
  buildAnagraficaPdfFields,
  buildAttrezzaturaPdfFields,
  buildPreventivoAttrezzaturaPdfFields,
  buildPreventivoMezzoPdfFields,
  buildPreventivoOggettoInterventoPdfFields,
  buildPreventivoTelaioMezzoPdfFields,
  buildTelaioPdfFields,
  buildIdentificazioneDocumentoPdfFields,
  inferTipoAttrezzaturaPdf,
} from "@/lib/pdf/preventivo-pdf-layout";

export type { PdfField, PreventivoPdfHeaderMeta, PreventivoPdfHeaderMeta as GestionalePdfHeaderMeta } from "@/lib/pdf/preventivo-pdf-layout";

export {
  PDF_DS_SECTION_GAP,
  PDF_DS_ROW_PAD,
  PDF_DS_ROW_PAD_COMPACT,
  PDF_DS_ROW_PAD_MULTILINE,
  PDF_DS_HEAD_PAD_V,
  PDF_DS_HEAD_PAD_V_COMPACT,
  PDF_DS_HEAD_PAD_H,
  PDF_DS_MULTILINE_MIN_H,
  PDF_DS_COL_LABEL_RATIO,
  cleanPdfFieldValue,
  pdfFieldFromValue,
  pdfFieldsToBody,
  pdfFieldsToCompactBody,
  compactFieldRowCount,
  drawGestionaleFieldSectionTable,
  drawGestionaleCompactFieldSectionTable,
  drawGestionaleDataSectionTable,
  headRowCellsForPdf,
  drawGestionaleSideBySideFieldSections,
  drawGestionaleSideBySideMetricBoxes,
  padPdfFieldsToEqualRows,
  gestionaleSectionTableHooks,
  drawAutoTableHeadBottomBorder,
  drawGestionaleTableHeadBorders,
  PDF_GESTIONALE_MUTED_FILL,
} from "@/lib/pdf/gestionale-section-table";

export type {
  GestionaleFieldSectionOpts,
  GestionaleDataSectionTotal,
  GestionaleDataSectionTableLayout,
  GestionaleSideBySidePanel,
  GestionaleMetricBox,
} from "@/lib/pdf/gestionale-section-table";
