-- GENERATED by scripts/generate-rpc-grants-sql.ts — do not edit by hand.
-- SSOT: docs/security/rpc-access-manifest.json
-- Re-run generator after manifest changes; security-migration-gate enforces sync.

-- ai_provider_key_record_failure(p_key_id uuid, p_error_code text, p_cooldown_seconds integer) [SERVER_ONLY]
revoke all on function public.ai_provider_key_record_failure(p_key_id uuid, p_error_code text, p_cooldown_seconds integer) from public, anon, authenticated, service_role;
grant execute on function public.ai_provider_key_record_failure(p_key_id uuid, p_error_code text, p_cooldown_seconds integer) to service_role;

-- ai_provider_key_record_success(p_key_id uuid, p_latency_ms integer) [SERVER_ONLY]
revoke all on function public.ai_provider_key_record_success(p_key_id uuid, p_latency_ms integer) from public, anon, authenticated, service_role;
grant execute on function public.ai_provider_key_record_success(p_key_id uuid, p_latency_ms integer) to service_role;

-- allocate_invoice_number(p_document_type text, p_series text, p_year integer) [AUTHENTICATED_CLIENT_CALLABLE]
revoke all on function public.allocate_invoice_number(p_document_type text, p_series text, p_year integer) from public, anon, authenticated, service_role;
grant execute on function public.allocate_invoice_number(p_document_type text, p_series text, p_year integer) to authenticated;
grant execute on function public.allocate_invoice_number(p_document_type text, p_series text, p_year integer) to service_role;

-- annulla_ordine_fornitore(p_id uuid) [AUTHENTICATED_CLIENT_CALLABLE]
revoke all on function public.annulla_ordine_fornitore(p_id uuid) from public, anon, authenticated, service_role;
grant execute on function public.annulla_ordine_fornitore(p_id uuid) to authenticated;
grant execute on function public.annulla_ordine_fornitore(p_id uuid) to service_role;

-- append_billing_event(p_entity_type text, p_entity_id uuid, p_aggregate_type text, p_aggregate_id uuid, p_invoice_id uuid, p_event_category text, p_event_type text, p_correlation_id uuid, p_causation_id uuid, p_payload jsonb) [AUTHENTICATED_CLIENT_CALLABLE]
revoke all on function public.append_billing_event(p_entity_type text, p_entity_id uuid, p_aggregate_type text, p_aggregate_id uuid, p_invoice_id uuid, p_event_category text, p_event_type text, p_correlation_id uuid, p_causation_id uuid, p_payload jsonb) from public, anon, authenticated, service_role;
grant execute on function public.append_billing_event(p_entity_type text, p_entity_id uuid, p_aggregate_type text, p_aggregate_id uuid, p_invoice_id uuid, p_event_category text, p_event_type text, p_correlation_id uuid, p_causation_id uuid, p_payload jsonb) to authenticated;
grant execute on function public.append_billing_event(p_entity_type text, p_entity_id uuid, p_aggregate_type text, p_aggregate_id uuid, p_invoice_id uuid, p_event_category text, p_event_type text, p_correlation_id uuid, p_causation_id uuid, p_payload jsonb) to service_role;

-- append_preventivo_event(p_preventivo_id uuid, p_event_type text, p_actor_type text, p_actor_id uuid, p_payload jsonb, p_snapshot jsonb) [AUTHENTICATED_CLIENT_CALLABLE]
revoke all on function public.append_preventivo_event(p_preventivo_id uuid, p_event_type text, p_actor_type text, p_actor_id uuid, p_payload jsonb, p_snapshot jsonb) from public, anon, authenticated, service_role;
grant execute on function public.append_preventivo_event(p_preventivo_id uuid, p_event_type text, p_actor_type text, p_actor_id uuid, p_payload jsonb, p_snapshot jsonb) to authenticated;

-- apply_invoice_status_backfill() [AUTHENTICATED_CLIENT_CALLABLE]
revoke all on function public.apply_invoice_status_backfill() from public, anon, authenticated, service_role;
grant execute on function public.apply_invoice_status_backfill() to authenticated;

-- archive_lavorazione_client_portal(p_lavorazione_id uuid) [PORTALE_CLIENT_CALLABLE]
revoke all on function public.archive_lavorazione_client_portal(p_lavorazione_id uuid) from public, anon, authenticated, service_role;
grant execute on function public.archive_lavorazione_client_portal(p_lavorazione_id uuid) to authenticated;

-- assert_ddt_preventivo_row_allocations(p_ddt_id uuid) [SERVER_ONLY]
revoke all on function public.assert_ddt_preventivo_row_allocations(p_ddt_id uuid) from public, anon, authenticated, service_role;
grant execute on function public.assert_ddt_preventivo_row_allocations(p_ddt_id uuid) to service_role;

-- assert_invoice_preventivo_allocations(p_invoice_id uuid) [SERVER_ONLY]
revoke all on function public.assert_invoice_preventivo_allocations(p_invoice_id uuid) from public, anon, authenticated, service_role;
grant execute on function public.assert_invoice_preventivo_allocations(p_invoice_id uuid) to service_role;

-- asset_lifecycle_v1_db_enabled() [AUTHENTICATED_CLIENT_CALLABLE]
revoke all on function public.asset_lifecycle_v1_db_enabled() from public, anon, authenticated, service_role;
grant execute on function public.asset_lifecycle_v1_db_enabled() to authenticated;
grant execute on function public.asset_lifecycle_v1_db_enabled() to service_role;

-- assign_ddt_numero(p_anno integer, p_serie text) [SERVER_ONLY]
revoke all on function public.assign_ddt_numero(p_anno integer, p_serie text) from public, anon, authenticated, service_role;
grant execute on function public.assign_ddt_numero(p_anno integer, p_serie text) to service_role;

-- assign_lavorazione_codice(p_created_at timestamp with time zone) [SERVER_ONLY]
revoke all on function public.assign_lavorazione_codice(p_created_at timestamp with time zone) from public, anon, authenticated, service_role;
grant execute on function public.assign_lavorazione_codice(p_created_at timestamp with time zone) to service_role;

-- assign_ordine_fornitore_numero(p_data_ordine date) [SERVER_ONLY]
revoke all on function public.assign_ordine_fornitore_numero(p_data_ordine date) from public, anon, authenticated, service_role;
grant execute on function public.assign_ordine_fornitore_numero(p_data_ordine date) to service_role;

-- assign_preventivo_numero_lavorazione(p_lavorazione_id uuid) [SERVER_ONLY]
revoke all on function public.assign_preventivo_numero_lavorazione(p_lavorazione_id uuid) from public, anon, authenticated, service_role;
grant execute on function public.assign_preventivo_numero_lavorazione(p_lavorazione_id uuid) to service_role;

-- assign_preventivo_numero_manuale(p_created_at timestamp with time zone) [SERVER_ONLY]
revoke all on function public.assign_preventivo_numero_manuale(p_created_at timestamp with time zone) from public, anon, authenticated, service_role;
grant execute on function public.assign_preventivo_numero_manuale(p_created_at timestamp with time zone) to service_role;

-- audit_entity_retention_limit(p_entita text) [AUTHENTICATED_CLIENT_CALLABLE]
revoke all on function public.audit_entity_retention_limit(p_entita text) from public, anon, authenticated, service_role;
grant execute on function public.audit_entity_retention_limit(p_entita text) to authenticated;
grant execute on function public.audit_entity_retention_limit(p_entita text) to service_role;

-- bulk_upsert_app_settings(p_items jsonb) [AUTHENTICATED_CLIENT_CALLABLE]
revoke all on function public.bulk_upsert_app_settings(p_items jsonb) from public, anon, authenticated, service_role;
grant execute on function public.bulk_upsert_app_settings(p_items jsonb) to authenticated;
grant execute on function public.bulk_upsert_app_settings(p_items jsonb) to service_role;

-- cab_claim_communication_outbox_batch(p_limit integer) [SERVER_ONLY]
revoke all on function public.cab_claim_communication_outbox_batch(p_limit integer) from public, anon, authenticated, service_role;
grant execute on function public.cab_claim_communication_outbox_batch(p_limit integer) to service_role;

-- cab_claim_communication_send_batch(p_limit integer) [SERVER_ONLY]
revoke all on function public.cab_claim_communication_send_batch(p_limit integer) from public, anon, authenticated, service_role;
grant execute on function public.cab_claim_communication_send_batch(p_limit integer) to service_role;

-- cab_claim_delivery_queue_batch(p_job_phase text, p_limit integer) [SERVER_ONLY]
revoke all on function public.cab_claim_delivery_queue_batch(p_job_phase text, p_limit integer) from public, anon, authenticated, service_role;
grant execute on function public.cab_claim_delivery_queue_batch(p_job_phase text, p_limit integer) to service_role;

-- cab_claim_notification_outbox_batch(p_limit integer) [SERVER_ONLY]
revoke all on function public.cab_claim_notification_outbox_batch(p_limit integer) from public, anon, authenticated, service_role;
grant execute on function public.cab_claim_notification_outbox_batch(p_limit integer) to service_role;

-- cab_complete_communication_outbox(p_outbox_id uuid, p_status text, p_error text) [SERVER_ONLY]
revoke all on function public.cab_complete_communication_outbox(p_outbox_id uuid, p_status text, p_error text) from public, anon, authenticated, service_role;
grant execute on function public.cab_complete_communication_outbox(p_outbox_id uuid, p_status text, p_error text) to service_role;

-- cab_complete_communication_send(p_queue_id uuid, p_status text, p_error text, p_next_attempt_at timestamp with time zone) [SERVER_ONLY]
revoke all on function public.cab_complete_communication_send(p_queue_id uuid, p_status text, p_error text, p_next_attempt_at timestamp with time zone) from public, anon, authenticated, service_role;
grant execute on function public.cab_complete_communication_send(p_queue_id uuid, p_status text, p_error text, p_next_attempt_at timestamp with time zone) to service_role;

-- cab_complete_delivery_queue(p_queue_id uuid, p_success boolean, p_error text, p_retry_delay_seconds integer) [SERVER_ONLY]
revoke all on function public.cab_complete_delivery_queue(p_queue_id uuid, p_success boolean, p_error text, p_retry_delay_seconds integer) from public, anon, authenticated, service_role;
grant execute on function public.cab_complete_delivery_queue(p_queue_id uuid, p_success boolean, p_error text, p_retry_delay_seconds integer) to service_role;

-- cab_complete_notification_outbox(p_outbox_id uuid, p_status text, p_error text) [SERVER_ONLY]
revoke all on function public.cab_complete_notification_outbox(p_outbox_id uuid, p_status text, p_error text) from public, anon, authenticated, service_role;
grant execute on function public.cab_complete_notification_outbox(p_outbox_id uuid, p_status text, p_error text) to service_role;

-- cab_count_unread_notifications() [AUTHENTICATED_CLIENT_CALLABLE]
revoke all on function public.cab_count_unread_notifications() from public, anon, authenticated, service_role;
grant execute on function public.cab_count_unread_notifications() to authenticated;

-- cab_create_notification(p_type text, p_title text, p_body text, p_href text, p_entity_type text, p_entity_id uuid, p_dedup_key text) [AUTHENTICATED_CLIENT_CALLABLE]
revoke all on function public.cab_create_notification(p_type text, p_title text, p_body text, p_href text, p_entity_type text, p_entity_id uuid, p_dedup_key text) from public, anon, authenticated, service_role;
grant execute on function public.cab_create_notification(p_type text, p_title text, p_body text, p_href text, p_entity_type text, p_entity_id uuid, p_dedup_key text) to authenticated;

-- cab_detect_schedule_conflicts(p_start timestamp with time zone, p_end timestamp with time zone, p_work_order_id uuid, p_exclude_id uuid) [AUTHENTICATED_CLIENT_CALLABLE]
revoke all on function public.cab_detect_schedule_conflicts(p_start timestamp with time zone, p_end timestamp with time zone, p_work_order_id uuid, p_exclude_id uuid) from public, anon, authenticated, service_role;
grant execute on function public.cab_detect_schedule_conflicts(p_start timestamp with time zone, p_end timestamp with time zone, p_work_order_id uuid, p_exclude_id uuid) to authenticated;

-- cab_dismiss_notification(p_notification_id uuid) [AUTHENTICATED_CLIENT_CALLABLE]
revoke all on function public.cab_dismiss_notification(p_notification_id uuid) from public, anon, authenticated, service_role;
grant execute on function public.cab_dismiss_notification(p_notification_id uuid) to authenticated;

-- cab_dispatch_notifications_bulk(p_company_id uuid, p_dispatch_notification_event_id text, p_dispatch_idempotency_key text, p_actor_id uuid, p_items jsonb) [SERVER_ONLY]
revoke all on function public.cab_dispatch_notifications_bulk(p_company_id uuid, p_dispatch_notification_event_id text, p_dispatch_idempotency_key text, p_actor_id uuid, p_items jsonb) from public, anon, authenticated, service_role;
grant execute on function public.cab_dispatch_notifications_bulk(p_company_id uuid, p_dispatch_notification_event_id text, p_dispatch_idempotency_key text, p_actor_id uuid, p_items jsonb) to service_role;

-- cab_enqueue_communication_outbox(p_domain_event_type text, p_entity_type text, p_entity_id uuid, p_idempotency_key text, p_actor_id uuid, p_payload jsonb, p_company_id uuid) [SERVER_ONLY]
revoke all on function public.cab_enqueue_communication_outbox(p_domain_event_type text, p_entity_type text, p_entity_id uuid, p_idempotency_key text, p_actor_id uuid, p_payload jsonb, p_company_id uuid) from public, anon, authenticated, service_role;
grant execute on function public.cab_enqueue_communication_outbox(p_domain_event_type text, p_entity_type text, p_entity_id uuid, p_idempotency_key text, p_actor_id uuid, p_payload jsonb, p_company_id uuid) to service_role;

-- cab_enqueue_notification_outbox(p_notification_event_id text, p_entity_type text, p_entity_id uuid, p_idempotency_key text, p_actor_id uuid, p_payload jsonb, p_company_id uuid) [SERVER_ONLY]
revoke all on function public.cab_enqueue_notification_outbox(p_notification_event_id text, p_entity_type text, p_entity_id uuid, p_idempotency_key text, p_actor_id uuid, p_payload jsonb, p_company_id uuid) from public, anon, authenticated, service_role;
grant execute on function public.cab_enqueue_notification_outbox(p_notification_event_id text, p_entity_type text, p_entity_id uuid, p_idempotency_key text, p_actor_id uuid, p_payload jsonb, p_company_id uuid) to service_role;

-- cab_enqueue_raw_delivery(p_notification_id uuid) [SERVER_ONLY]
revoke all on function public.cab_enqueue_raw_delivery(p_notification_id uuid) from public, anon, authenticated, service_role;
grant execute on function public.cab_enqueue_raw_delivery(p_notification_id uuid) to service_role;

-- cab_fanout_client_portal_lavorazione_notification(p_event text, p_lavorazione_id uuid) [SERVER_ONLY]
revoke all on function public.cab_fanout_client_portal_lavorazione_notification(p_event text, p_lavorazione_id uuid) from public, anon, authenticated, service_role;
grant execute on function public.cab_fanout_client_portal_lavorazione_notification(p_event text, p_lavorazione_id uuid) to service_role;

-- cab_fanout_client_portal_lavorazione_notification_core(p_event text, p_lavorazione_id uuid, p_created_by uuid) [SERVER_ONLY]
revoke all on function public.cab_fanout_client_portal_lavorazione_notification_core(p_event text, p_lavorazione_id uuid, p_created_by uuid) from public, anon, authenticated, service_role;
grant execute on function public.cab_fanout_client_portal_lavorazione_notification_core(p_event text, p_lavorazione_id uuid, p_created_by uuid) to service_role;

-- cab_fanout_enqueue_raw_after_notification() [SERVER_ONLY]
revoke all on function public.cab_fanout_enqueue_raw_after_notification() from public, anon, authenticated, service_role;
grant execute on function public.cab_fanout_enqueue_raw_after_notification() to service_role;

-- cab_invoke_communication_outbox_worker() [CRON_ONLY]
revoke all on function public.cab_invoke_communication_outbox_worker() from public, anon, authenticated, service_role;
grant execute on function public.cab_invoke_communication_outbox_worker() to service_role;

-- cab_invoke_communication_send_worker() [CRON_ONLY]
revoke all on function public.cab_invoke_communication_send_worker() from public, anon, authenticated, service_role;
grant execute on function public.cab_invoke_communication_send_worker() to service_role;

-- cab_invoke_fatturazione_overdue_digest_worker() [CRON_ONLY]
revoke all on function public.cab_invoke_fatturazione_overdue_digest_worker() from public, anon, authenticated, service_role;
grant execute on function public.cab_invoke_fatturazione_overdue_digest_worker() to service_role;

-- cab_invoke_lavorazioni_overdue_digest_worker() [CRON_ONLY]
revoke all on function public.cab_invoke_lavorazioni_overdue_digest_worker() from public, anon, authenticated, service_role;
grant execute on function public.cab_invoke_lavorazioni_overdue_digest_worker() to service_role;

-- cab_invoke_notification_outbox_worker() [CRON_ONLY]
revoke all on function public.cab_invoke_notification_outbox_worker() from public, anon, authenticated, service_role;
grant execute on function public.cab_invoke_notification_outbox_worker() to service_role;

-- cab_invoke_push_delivery_worker() [CRON_ONLY]
revoke all on function public.cab_invoke_push_delivery_worker() from public, anon, authenticated, service_role;
grant execute on function public.cab_invoke_push_delivery_worker() to service_role;

-- cab_invoke_push_subscription_cleanup_worker() [CRON_ONLY]
revoke all on function public.cab_invoke_push_subscription_cleanup_worker() from public, anon, authenticated, service_role;
grant execute on function public.cab_invoke_push_subscription_cleanup_worker() to service_role;

-- cab_invoke_spare_parts_document_index_worker() [CRON_ONLY]
revoke all on function public.cab_invoke_spare_parts_document_index_worker() from public, anon, authenticated, service_role;
grant execute on function public.cab_invoke_spare_parts_document_index_worker() to service_role;

-- cab_invoke_spare_parts_part_search_worker() [CRON_ONLY]
revoke all on function public.cab_invoke_spare_parts_part_search_worker() from public, anon, authenticated, service_role;
grant execute on function public.cab_invoke_spare_parts_part_search_worker() to service_role;

-- cab_list_notifications_inbox(p_limit integer, p_cursor_priority_rank integer, p_cursor_created_at timestamp with time zone, p_cursor_id uuid) [AUTHENTICATED_CLIENT_CALLABLE]
revoke all on function public.cab_list_notifications_inbox(p_limit integer, p_cursor_priority_rank integer, p_cursor_created_at timestamp with time zone, p_cursor_id uuid) from public, anon, authenticated, service_role;
grant execute on function public.cab_list_notifications_inbox(p_limit integer, p_cursor_priority_rank integer, p_cursor_created_at timestamp with time zone, p_cursor_id uuid) to authenticated;

-- cab_list_workshop_schedule_by_work_order(p_work_order_id uuid) [AUTHENTICATED_CLIENT_CALLABLE]
revoke all on function public.cab_list_workshop_schedule_by_work_order(p_work_order_id uuid) from public, anon, authenticated, service_role;
grant execute on function public.cab_list_workshop_schedule_by_work_order(p_work_order_id uuid) to authenticated;

-- cab_list_workshop_schedule_events(p_start timestamp with time zone, p_end timestamp with time zone, p_filters jsonb) [AUTHENTICATED_CLIENT_CALLABLE]
revoke all on function public.cab_list_workshop_schedule_events(p_start timestamp with time zone, p_end timestamp with time zone, p_filters jsonb) from public, anon, authenticated, service_role;
grant execute on function public.cab_list_workshop_schedule_events(p_start timestamp with time zone, p_end timestamp with time zone, p_filters jsonb) to authenticated;

-- cab_log_notification_pipeline_trace(p_trace_id uuid, p_stage text, p_entity_id uuid, p_notification_event_id text, p_recipient_count integer, p_notifications_created integer, p_realtime_delivered boolean, p_client_received boolean, p_error text, p_meta jsonb) [SERVER_ONLY]
revoke all on function public.cab_log_notification_pipeline_trace(p_trace_id uuid, p_stage text, p_entity_id uuid, p_notification_event_id text, p_recipient_count integer, p_notifications_created integer, p_realtime_delivered boolean, p_client_received boolean, p_error text, p_meta jsonb) from public, anon, authenticated, service_role;
grant execute on function public.cab_log_notification_pipeline_trace(p_trace_id uuid, p_stage text, p_entity_id uuid, p_notification_event_id text, p_recipient_count integer, p_notifications_created integer, p_realtime_delivered boolean, p_client_received boolean, p_error text, p_meta jsonb) to service_role;

-- cab_mark_all_notifications_read(p_max integer) [AUTHENTICATED_CLIENT_CALLABLE]
revoke all on function public.cab_mark_all_notifications_read(p_max integer) from public, anon, authenticated, service_role;
grant execute on function public.cab_mark_all_notifications_read(p_max integer) to authenticated;

-- cab_mark_notification_read(p_notification_id uuid) [AUTHENTICATED_CLIENT_CALLABLE]
revoke all on function public.cab_mark_notification_read(p_notification_id uuid) from public, anon, authenticated, service_role;
grant execute on function public.cab_mark_notification_read(p_notification_id uuid) to authenticated;

-- cab_migrate_dashboard_promemoria_to_schedule() [AUTHENTICATED_CLIENT_CALLABLE]
revoke all on function public.cab_migrate_dashboard_promemoria_to_schedule() from public, anon, authenticated, service_role;
grant execute on function public.cab_migrate_dashboard_promemoria_to_schedule() to authenticated;

-- cab_patch_workshop_schedule_times(p_id uuid, p_start_at timestamp with time zone, p_end_at timestamp with time zone) [AUTHENTICATED_CLIENT_CALLABLE]
revoke all on function public.cab_patch_workshop_schedule_times(p_id uuid, p_start_at timestamp with time zone, p_end_at timestamp with time zone) from public, anon, authenticated, service_role;
grant execute on function public.cab_patch_workshop_schedule_times(p_id uuid, p_start_at timestamp with time zone, p_end_at timestamp with time zone) to authenticated;

-- cab_publish_notification(p_type text, p_title text, p_body text, p_href text, p_entity_type text, p_entity_id uuid, p_dedup_key text, p_idempotency_key text, p_translation_key text, p_translation_params jsonb, p_snapshot jsonb, p_actions jsonb, p_payload_version text, p_expires_at timestamp with time zone, p_source_domain_event text, p_actor_id uuid, p_priority text) [AUTHENTICATED_CLIENT_CALLABLE]
revoke all on function public.cab_publish_notification(p_type text, p_title text, p_body text, p_href text, p_entity_type text, p_entity_id uuid, p_dedup_key text, p_idempotency_key text, p_translation_key text, p_translation_params jsonb, p_snapshot jsonb, p_actions jsonb, p_payload_version text, p_expires_at timestamp with time zone, p_source_domain_event text, p_actor_id uuid, p_priority text) from public, anon, authenticated, service_role;
grant execute on function public.cab_publish_notification(p_type text, p_title text, p_body text, p_href text, p_entity_type text, p_entity_id uuid, p_dedup_key text, p_idempotency_key text, p_translation_key text, p_translation_params jsonb, p_snapshot jsonb, p_actions jsonb, p_payload_version text, p_expires_at timestamp with time zone, p_source_domain_event text, p_actor_id uuid, p_priority text) to authenticated;

-- cab_release_communication_outbox(p_outbox_id uuid, p_error text) [SERVER_ONLY]
revoke all on function public.cab_release_communication_outbox(p_outbox_id uuid, p_error text) from public, anon, authenticated, service_role;
grant execute on function public.cab_release_communication_outbox(p_outbox_id uuid, p_error text) to service_role;

-- cab_release_notification_outbox(p_outbox_id uuid, p_error text) [SERVER_ONLY]
revoke all on function public.cab_release_notification_outbox(p_outbox_id uuid, p_error text) from public, anon, authenticated, service_role;
grant execute on function public.cab_release_notification_outbox(p_outbox_id uuid, p_error text) to service_role;

-- cab_revoke_push_subscription(p_endpoint text) [AUTHENTICATED_CLIENT_CALLABLE]
revoke all on function public.cab_revoke_push_subscription(p_endpoint text) from public, anon, authenticated, service_role;
grant execute on function public.cab_revoke_push_subscription(p_endpoint text) to authenticated;

-- cab_sync_lavorazione_actual_labor_hours_safety_net() [SERVER_ONLY]
revoke all on function public.cab_sync_lavorazione_actual_labor_hours_safety_net() from public, anon, authenticated, service_role;
grant execute on function public.cab_sync_lavorazione_actual_labor_hours_safety_net() to service_role;

-- cab_touch_push_presence(p_endpoint text, p_presence_status text) [AUTHENTICATED_CLIENT_CALLABLE]
revoke all on function public.cab_touch_push_presence(p_endpoint text, p_presence_status text) from public, anon, authenticated, service_role;
grant execute on function public.cab_touch_push_presence(p_endpoint text, p_presence_status text) to authenticated;

-- cab_upsert_push_subscription(p_endpoint text, p_p256dh text, p_auth text, p_user_agent text) [AUTHENTICATED_CLIENT_CALLABLE]
revoke all on function public.cab_upsert_push_subscription(p_endpoint text, p_p256dh text, p_auth text, p_user_agent text) from public, anon, authenticated, service_role;
grant execute on function public.cab_upsert_push_subscription(p_endpoint text, p_p256dh text, p_auth text, p_user_agent text) to authenticated;

-- cab_upsert_workshop_schedule_event(p_id uuid, p_title text, p_description text, p_event_type text, p_block_type text, p_start_at timestamp with time zone, p_end_at timestamp with time zone, p_planning_status text, p_priority text, p_work_order_id uuid, p_series_id uuid, p_recurrence_frequency text, p_recurrence_interval integer, p_recurrence_until date) [AUTHENTICATED_CLIENT_CALLABLE]
revoke all on function public.cab_upsert_workshop_schedule_event(p_id uuid, p_title text, p_description text, p_event_type text, p_block_type text, p_start_at timestamp with time zone, p_end_at timestamp with time zone, p_planning_status text, p_priority text, p_work_order_id uuid, p_series_id uuid, p_recurrence_frequency text, p_recurrence_interval integer, p_recurrence_until date) from public, anon, authenticated, service_role;
grant execute on function public.cab_upsert_workshop_schedule_event(p_id uuid, p_title text, p_description text, p_event_type text, p_block_type text, p_start_at timestamp with time zone, p_end_at timestamp with time zone, p_planning_status text, p_priority text, p_work_order_id uuid, p_series_id uuid, p_recurrence_frequency text, p_recurrence_interval integer, p_recurrence_until date) to authenticated;

-- cancel_ddt(p_ddt_id uuid) [AUTHENTICATED_CLIENT_CALLABLE]
revoke all on function public.cancel_ddt(p_ddt_id uuid) from public, anon, authenticated, service_role;
grant execute on function public.cancel_ddt(p_ddt_id uuid) to authenticated;
grant execute on function public.cancel_ddt(p_ddt_id uuid) to service_role;

-- cancel_invoice(p_invoice_id uuid, p_reason text) [AUTHENTICATED_CLIENT_CALLABLE]
revoke all on function public.cancel_invoice(p_invoice_id uuid, p_reason text) from public, anon, authenticated, service_role;
grant execute on function public.cancel_invoice(p_invoice_id uuid, p_reason text) to authenticated;
grant execute on function public.cancel_invoice(p_invoice_id uuid, p_reason text) to service_role;

-- check_username_available(p_username text, p_exclude_user_id uuid) [AUTHENTICATED_CLIENT_CALLABLE]
revoke all on function public.check_username_available(p_username text, p_exclude_user_id uuid) from public, anon, authenticated, service_role;
grant execute on function public.check_username_available(p_username text, p_exclude_user_id uuid) to authenticated;
grant execute on function public.check_username_available(p_username text, p_exclude_user_id uuid) to service_role;

-- cleanup_import_storage(p_batch_size integer) [SERVER_ONLY]
revoke all on function public.cleanup_import_storage(p_batch_size integer) from public, anon, authenticated, service_role;
grant execute on function public.cleanup_import_storage(p_batch_size integer) to service_role;

-- close_attrezzatura_assignment(p_attrezzatura_id uuid, p_change_reason assignment_change_reason, p_note text) [AUTHENTICATED_CLIENT_CALLABLE]
revoke all on function public.close_attrezzatura_assignment(p_attrezzatura_id uuid, p_change_reason assignment_change_reason, p_note text) from public, anon, authenticated, service_role;
grant execute on function public.close_attrezzatura_assignment(p_attrezzatura_id uuid, p_change_reason assignment_change_reason, p_note text) to authenticated;
grant execute on function public.close_attrezzatura_assignment(p_attrezzatura_id uuid, p_change_reason assignment_change_reason, p_note text) to service_role;

-- commit_ddt_pdf_artifact(p_ddt_id uuid, p_storage_path text, p_hash text) [AUTHENTICATED_CLIENT_CALLABLE]
revoke all on function public.commit_ddt_pdf_artifact(p_ddt_id uuid, p_storage_path text, p_hash text) from public, anon, authenticated, service_role;
grant execute on function public.commit_ddt_pdf_artifact(p_ddt_id uuid, p_storage_path text, p_hash text) to authenticated;
grant execute on function public.commit_ddt_pdf_artifact(p_ddt_id uuid, p_storage_path text, p_hash text) to service_role;

-- commit_preventivo_status_transition(p_preventivo_id uuid, p_to_stato text, p_artifact jsonb, p_confermato_by uuid) [AUTHENTICATED_CLIENT_CALLABLE]
revoke all on function public.commit_preventivo_status_transition(p_preventivo_id uuid, p_to_stato text, p_artifact jsonb, p_confermato_by uuid) from public, anon, authenticated, service_role;
grant execute on function public.commit_preventivo_status_transition(p_preventivo_id uuid, p_to_stato text, p_artifact jsonb, p_confermato_by uuid) to authenticated;
grant execute on function public.commit_preventivo_status_transition(p_preventivo_id uuid, p_to_stato text, p_artifact jsonb, p_confermato_by uuid) to service_role;

-- complete_lavorazione_tagliando(p_lavorazione_id uuid, p_mezzo_id uuid, p_config_id uuid, p_plan_id uuid, p_performed_at date, p_ore_at_service numeric, p_km_at_service numeric, p_mezzo_ore_snapshot numeric, p_note text, p_preset_version_id uuid, p_interval_type maintenance_interval_type, p_interval_value_at_execution numeric, p_execution_type maintenance_execution_type, p_preset_snapshot jsonb, p_compliance_auto numeric, p_compliance_diff_json jsonb, p_compliance_algorithm_version text, p_snapshot_schema_version text, p_parts jsonb, p_checklist jsonb, p_forecast jsonb, p_skip_forecast boolean, p_no_preset_reason text) [AUTHENTICATED_CLIENT_CALLABLE]
revoke all on function public.complete_lavorazione_tagliando(p_lavorazione_id uuid, p_mezzo_id uuid, p_config_id uuid, p_plan_id uuid, p_performed_at date, p_ore_at_service numeric, p_km_at_service numeric, p_mezzo_ore_snapshot numeric, p_note text, p_preset_version_id uuid, p_interval_type maintenance_interval_type, p_interval_value_at_execution numeric, p_execution_type maintenance_execution_type, p_preset_snapshot jsonb, p_compliance_auto numeric, p_compliance_diff_json jsonb, p_compliance_algorithm_version text, p_snapshot_schema_version text, p_parts jsonb, p_checklist jsonb, p_forecast jsonb, p_skip_forecast boolean, p_no_preset_reason text) from public, anon, authenticated, service_role;
grant execute on function public.complete_lavorazione_tagliando(p_lavorazione_id uuid, p_mezzo_id uuid, p_config_id uuid, p_plan_id uuid, p_performed_at date, p_ore_at_service numeric, p_km_at_service numeric, p_mezzo_ore_snapshot numeric, p_note text, p_preset_version_id uuid, p_interval_type maintenance_interval_type, p_interval_value_at_execution numeric, p_execution_type maintenance_execution_type, p_preset_snapshot jsonb, p_compliance_auto numeric, p_compliance_diff_json jsonb, p_compliance_algorithm_version text, p_snapshot_schema_version text, p_parts jsonb, p_checklist jsonb, p_forecast jsonb, p_skip_forecast boolean, p_no_preset_reason text) to authenticated;
grant execute on function public.complete_lavorazione_tagliando(p_lavorazione_id uuid, p_mezzo_id uuid, p_config_id uuid, p_plan_id uuid, p_performed_at date, p_ore_at_service numeric, p_km_at_service numeric, p_mezzo_ore_snapshot numeric, p_note text, p_preset_version_id uuid, p_interval_type maintenance_interval_type, p_interval_value_at_execution numeric, p_execution_type maintenance_execution_type, p_preset_snapshot jsonb, p_compliance_auto numeric, p_compliance_diff_json jsonb, p_compliance_algorithm_version text, p_snapshot_schema_version text, p_parts jsonb, p_checklist jsonb, p_forecast jsonb, p_skip_forecast boolean, p_no_preset_reason text) to service_role;

-- confirm_ddt(p_ddt_id uuid) [AUTHENTICATED_CLIENT_CALLABLE]
revoke all on function public.confirm_ddt(p_ddt_id uuid) from public, anon, authenticated, service_role;
grant execute on function public.confirm_ddt(p_ddt_id uuid) to authenticated;
grant execute on function public.confirm_ddt(p_ddt_id uuid) to service_role;

-- count_mezzo_dependencies(p_mezzo_id uuid) [AUTHENTICATED_CLIENT_CALLABLE]
revoke all on function public.count_mezzo_dependencies(p_mezzo_id uuid) from public, anon, authenticated, service_role;
grant execute on function public.count_mezzo_dependencies(p_mezzo_id uuid) to authenticated;
grant execute on function public.count_mezzo_dependencies(p_mezzo_id uuid) to service_role;

-- create_credit_note_from_invoice(p_invoice_id uuid, p_amount numeric, p_reason text) [AUTHENTICATED_CLIENT_CALLABLE]
revoke all on function public.create_credit_note_from_invoice(p_invoice_id uuid, p_amount numeric, p_reason text) from public, anon, authenticated, service_role;
grant execute on function public.create_credit_note_from_invoice(p_invoice_id uuid, p_amount numeric, p_reason text) to authenticated;
grant execute on function public.create_credit_note_from_invoice(p_invoice_id uuid, p_amount numeric, p_reason text) to service_role;

-- create_ddt_with_rows(p_payload jsonb) [AUTHENTICATED_CLIENT_CALLABLE]
revoke all on function public.create_ddt_with_rows(p_payload jsonb) from public, anon, authenticated, service_role;
grant execute on function public.create_ddt_with_rows(p_payload jsonb) to authenticated;
grant execute on function public.create_ddt_with_rows(p_payload jsonb) to service_role;

-- create_invoice_with_rows_and_links(p_payload jsonb) [AUTHENTICATED_CLIENT_CALLABLE]
revoke all on function public.create_invoice_with_rows_and_links(p_payload jsonb) from public, anon, authenticated, service_role;
grant execute on function public.create_invoice_with_rows_and_links(p_payload jsonb) to authenticated;
grant execute on function public.create_invoice_with_rows_and_links(p_payload jsonb) to service_role;

-- create_ordine_fornitore_with_righe(p_payload jsonb) [AUTHENTICATED_CLIENT_CALLABLE]
revoke all on function public.create_ordine_fornitore_with_righe(p_payload jsonb) from public, anon, authenticated, service_role;
grant execute on function public.create_ordine_fornitore_with_righe(p_payload jsonb) to authenticated;
grant execute on function public.create_ordine_fornitore_with_righe(p_payload jsonb) to service_role;

-- current_profile_role() [AUTHENTICATED_CLIENT_CALLABLE]
revoke all on function public.current_profile_role() from public, anon, authenticated, service_role;
grant execute on function public.current_profile_role() to authenticated;

-- customer_balance_reconciliation_report() [AUTHENTICATED_CLIENT_CALLABLE]
revoke all on function public.customer_balance_reconciliation_report() from public, anon, authenticated, service_role;
grant execute on function public.customer_balance_reconciliation_report() to authenticated;

-- ddt_preventivo_row_delivered_qty(p_preventivo_id uuid, p_source_ref text, p_exclude_ddt_id uuid) [SERVER_ONLY]
revoke all on function public.ddt_preventivo_row_delivered_qty(p_preventivo_id uuid, p_source_ref text, p_exclude_ddt_id uuid) from public, anon, authenticated, service_role;
grant execute on function public.ddt_preventivo_row_delivered_qty(p_preventivo_id uuid, p_source_ref text, p_exclude_ddt_id uuid) to service_role;

-- delete_mezzo(p_mezzo_id uuid) [AUTHENTICATED_CLIENT_CALLABLE]
revoke all on function public.delete_mezzo(p_mezzo_id uuid) from public, anon, authenticated, service_role;
grant execute on function public.delete_mezzo(p_mezzo_id uuid) to authenticated;
grant execute on function public.delete_mezzo(p_mezzo_id uuid) to service_role;

-- document_ai_index_is_usable(p_index_id uuid) [SERVER_ONLY]
revoke all on function public.document_ai_index_is_usable(p_index_id uuid) from public, anon, authenticated, service_role;
grant execute on function public.document_ai_index_is_usable(p_index_id uuid) to service_role;

-- document_capture_abort_apply(p_capture_id uuid, p_application_id uuid, p_reason text) [AUTHENTICATED_CLIENT_CALLABLE]
revoke all on function public.document_capture_abort_apply(p_capture_id uuid, p_application_id uuid, p_reason text) from public, anon, authenticated, service_role;
grant execute on function public.document_capture_abort_apply(p_capture_id uuid, p_application_id uuid, p_reason text) to authenticated;

-- document_capture_begin_apply(p_capture_id uuid, p_application_id uuid, p_resume boolean) [AUTHENTICATED_CLIENT_CALLABLE]
revoke all on function public.document_capture_begin_apply(p_capture_id uuid, p_application_id uuid, p_resume boolean) from public, anon, authenticated, service_role;
grant execute on function public.document_capture_begin_apply(p_capture_id uuid, p_application_id uuid, p_resume boolean) to authenticated;

-- document_capture_complete_apply(p_capture_id uuid, p_application_id uuid, p_success boolean, p_event_type text, p_lavorazione_id uuid, p_mezzo_id uuid, p_payload jsonb) [AUTHENTICATED_CLIENT_CALLABLE]
revoke all on function public.document_capture_complete_apply(p_capture_id uuid, p_application_id uuid, p_success boolean, p_event_type text, p_lavorazione_id uuid, p_mezzo_id uuid, p_payload jsonb) from public, anon, authenticated, service_role;
grant execute on function public.document_capture_complete_apply(p_capture_id uuid, p_application_id uuid, p_success boolean, p_event_type text, p_lavorazione_id uuid, p_mezzo_id uuid, p_payload jsonb) to authenticated;

-- document_capture_create_upload_policy(p_capture_id uuid, p_file_name text, p_expected_mime text, p_expected_size_bytes bigint, p_source text, p_document_category text, p_scheda_tipo text, p_lavorazione_id uuid) [AUTHENTICATED_CLIENT_CALLABLE]
revoke all on function public.document_capture_create_upload_policy(p_capture_id uuid, p_file_name text, p_expected_mime text, p_expected_size_bytes bigint, p_source text, p_document_category text, p_scheda_tipo text, p_lavorazione_id uuid) from public, anon, authenticated, service_role;
grant execute on function public.document_capture_create_upload_policy(p_capture_id uuid, p_file_name text, p_expected_mime text, p_expected_size_bytes bigint, p_source text, p_document_category text, p_scheda_tipo text, p_lavorazione_id uuid) to authenticated;

-- document_capture_finalize(p_capture_id uuid, p_sha256 text, p_mime text, p_file_size_bytes bigint, p_storage_version text, p_storage_etag text) [AUTHENTICATED_CLIENT_CALLABLE]
revoke all on function public.document_capture_finalize(p_capture_id uuid, p_sha256 text, p_mime text, p_file_size_bytes bigint, p_storage_version text, p_storage_etag text) from public, anon, authenticated, service_role;
grant execute on function public.document_capture_finalize(p_capture_id uuid, p_sha256 text, p_mime text, p_file_size_bytes bigint, p_storage_version text, p_storage_etag text) to authenticated;

-- document_capture_mutate_with_event(p_capture_id uuid, p_event_type text, p_idempotency_key text, p_payload jsonb, p_new_status text, p_lavorazione_id uuid, p_mezzo_id uuid, p_attrezzatura_id uuid) [AUTHENTICATED_CLIENT_CALLABLE]
revoke all on function public.document_capture_mutate_with_event(p_capture_id uuid, p_event_type text, p_idempotency_key text, p_payload jsonb, p_new_status text, p_lavorazione_id uuid, p_mezzo_id uuid, p_attrezzatura_id uuid) from public, anon, authenticated, service_role;
grant execute on function public.document_capture_mutate_with_event(p_capture_id uuid, p_event_type text, p_idempotency_key text, p_payload jsonb, p_new_status text, p_lavorazione_id uuid, p_mezzo_id uuid, p_attrezzatura_id uuid) to authenticated;

-- document_capture_patch(p_capture_id uuid, p_status text, p_document_category text, p_scheda_tipo text, p_lavorazione_id uuid, p_mezzo_id uuid, p_attrezzatura_id uuid, p_soft_delete boolean, p_deletion_reason text) [AUTHENTICATED_CLIENT_CALLABLE]
revoke all on function public.document_capture_patch(p_capture_id uuid, p_status text, p_document_category text, p_scheda_tipo text, p_lavorazione_id uuid, p_mezzo_id uuid, p_attrezzatura_id uuid, p_soft_delete boolean, p_deletion_reason text) from public, anon, authenticated, service_role;
grant execute on function public.document_capture_patch(p_capture_id uuid, p_status text, p_document_category text, p_scheda_tipo text, p_lavorazione_id uuid, p_mezzo_id uuid, p_attrezzatura_id uuid, p_soft_delete boolean, p_deletion_reason text) to authenticated;

-- document_capture_rate_limit_check(p_operation text, p_max integer, p_window_seconds integer) [AUTHENTICATED_CLIENT_CALLABLE]
revoke all on function public.document_capture_rate_limit_check(p_operation text, p_max integer, p_window_seconds integer) from public, anon, authenticated, service_role;
grant execute on function public.document_capture_rate_limit_check(p_operation text, p_max integer, p_window_seconds integer) to authenticated;

-- document_capture_storage_object_allowed(p_object_name text, p_op text) [AUTHENTICATED_CLIENT_CALLABLE]
revoke all on function public.document_capture_storage_object_allowed(p_object_name text, p_op text) from public, anon, authenticated, service_role;
grant execute on function public.document_capture_storage_object_allowed(p_object_name text, p_op text) to authenticated;

-- enqueue_search_rebuild(p_entity_type text, p_entity_id uuid) [CRON_ONLY]
revoke all on function public.enqueue_search_rebuild(p_entity_type text, p_entity_id uuid) from public, anon, authenticated, service_role;
grant execute on function public.enqueue_search_rebuild(p_entity_type text, p_entity_id uuid) to service_role;

-- execute_rename_job_complete(p_job_id uuid, p_metrics jsonb, p_health jsonb, p_entity_snapshot jsonb) [AUTHENTICATED_CLIENT_CALLABLE]
revoke all on function public.execute_rename_job_complete(p_job_id uuid, p_metrics jsonb, p_health jsonb, p_entity_snapshot jsonb) from public, anon, authenticated, service_role;
grant execute on function public.execute_rename_job_complete(p_job_id uuid, p_metrics jsonb, p_health jsonb, p_entity_snapshot jsonb) to authenticated;

-- execute_rename_job_start(p_job_id uuid, p_actor uuid) [AUTHENTICATED_CLIENT_CALLABLE]
revoke all on function public.execute_rename_job_start(p_job_id uuid, p_actor uuid) from public, anon, authenticated, service_role;
grant execute on function public.execute_rename_job_start(p_job_id uuid, p_actor uuid) to authenticated;

-- expire_import_files(p_uploaded_ttl interval, p_processed_ttl interval, p_failed_ttl interval) [SERVER_ONLY]
revoke all on function public.expire_import_files(p_uploaded_ttl interval, p_processed_ttl interval, p_failed_ttl interval) from public, anon, authenticated, service_role;
grant execute on function public.expire_import_files(p_uploaded_ttl interval, p_processed_ttl interval, p_failed_ttl interval) to service_role;

-- expire_pending_document_captures(p_ttl interval) [SERVER_ONLY]
revoke all on function public.expire_pending_document_captures(p_ttl interval) from public, anon, authenticated, service_role;
grant execute on function public.expire_pending_document_captures(p_ttl interval) to service_role;

-- get_activity_feed(p_limit integer, p_days integer) [AUTHENTICATED_CLIENT_CALLABLE]
revoke all on function public.get_activity_feed(p_limit integer, p_days integer) from public, anon, authenticated, service_role;
grant execute on function public.get_activity_feed(p_limit integer, p_days integer) to authenticated;
grant execute on function public.get_activity_feed(p_limit integer, p_days integer) to service_role;

-- get_audit_retention_config() [AUTHENTICATED_CLIENT_CALLABLE]
revoke all on function public.get_audit_retention_config() from public, anon, authenticated, service_role;
grant execute on function public.get_audit_retention_config() to authenticated;
grant execute on function public.get_audit_retention_config() to service_role;

-- handle_new_user() [SERVER_ONLY]
revoke all on function public.handle_new_user() from public, anon, authenticated, service_role;
grant execute on function public.handle_new_user() to service_role;

-- import_file_begin_processing(p_file_id uuid) [AUTHENTICATED_CLIENT_CALLABLE]
revoke all on function public.import_file_begin_processing(p_file_id uuid) from public, anon, authenticated, service_role;
grant execute on function public.import_file_begin_processing(p_file_id uuid) to authenticated;

-- import_file_cancel(p_file_id uuid) [AUTHENTICATED_CLIENT_CALLABLE]
revoke all on function public.import_file_cancel(p_file_id uuid) from public, anon, authenticated, service_role;
grant execute on function public.import_file_cancel(p_file_id uuid) to authenticated;

-- import_file_complete_processing(p_file_id uuid, p_outcome text, p_failed_reason_code text, p_last_error jsonb) [AUTHENTICATED_CLIENT_CALLABLE]
revoke all on function public.import_file_complete_processing(p_file_id uuid, p_outcome text, p_failed_reason_code text, p_last_error jsonb) from public, anon, authenticated, service_role;
grant execute on function public.import_file_complete_processing(p_file_id uuid, p_outcome text, p_failed_reason_code text, p_last_error jsonb) to authenticated;

-- import_file_create_upload_policy(p_file_id uuid, p_kind text, p_file_name text, p_expected_mime text, p_expected_size_bytes bigint, p_import_session_id uuid) [AUTHENTICATED_CLIENT_CALLABLE]
revoke all on function public.import_file_create_upload_policy(p_file_id uuid, p_kind text, p_file_name text, p_expected_mime text, p_expected_size_bytes bigint, p_import_session_id uuid) from public, anon, authenticated, service_role;
grant execute on function public.import_file_create_upload_policy(p_file_id uuid, p_kind text, p_file_name text, p_expected_mime text, p_expected_size_bytes bigint, p_import_session_id uuid) to authenticated;

-- import_file_finalize(p_file_id uuid, p_sha256 text, p_mime text, p_file_size_bytes bigint) [AUTHENTICATED_CLIENT_CALLABLE]
revoke all on function public.import_file_finalize(p_file_id uuid, p_sha256 text, p_mime text, p_file_size_bytes bigint) from public, anon, authenticated, service_role;
grant execute on function public.import_file_finalize(p_file_id uuid, p_sha256 text, p_mime text, p_file_size_bytes bigint) to authenticated;

-- import_file_storage_object_allowed(p_object_name text, p_op text) [AUTHENTICATED_CLIENT_CALLABLE]
revoke all on function public.import_file_storage_object_allowed(p_object_name text, p_op text) from public, anon, authenticated, service_role;
grant execute on function public.import_file_storage_object_allowed(p_object_name text, p_op text) to authenticated;

-- inventory_receiving_apply(p_document_id uuid, p_lines jsonb, p_user_id uuid) [AUTHENTICATED_CLIENT_CALLABLE]
revoke all on function public.inventory_receiving_apply(p_document_id uuid, p_lines jsonb, p_user_id uuid) from public, anon, authenticated, service_role;
grant execute on function public.inventory_receiving_apply(p_document_id uuid, p_lines jsonb, p_user_id uuid) to authenticated;
grant execute on function public.inventory_receiving_apply(p_document_id uuid, p_lines jsonb, p_user_id uuid) to service_role;

-- invoice_apply_transition(p_invoice_id uuid, p_transition text, p_payload jsonb, p_actor_id uuid) [AUTHENTICATED_CLIENT_CALLABLE]
revoke all on function public.invoice_apply_transition(p_invoice_id uuid, p_transition text, p_payload jsonb, p_actor_id uuid) from public, anon, authenticated, service_role;
grant execute on function public.invoice_apply_transition(p_invoice_id uuid, p_transition text, p_payload jsonb, p_actor_id uuid) to authenticated;
grant execute on function public.invoice_apply_transition(p_invoice_id uuid, p_transition text, p_payload jsonb, p_actor_id uuid) to service_role;

-- invoice_apply_transition(p_invoice_id uuid, p_transition text, p_payload jsonb, p_actor_id uuid, p_expected_version integer) [AUTHENTICATED_CLIENT_CALLABLE]
revoke all on function public.invoice_apply_transition(p_invoice_id uuid, p_transition text, p_payload jsonb, p_actor_id uuid, p_expected_version integer) from public, anon, authenticated, service_role;
grant execute on function public.invoice_apply_transition(p_invoice_id uuid, p_transition text, p_payload jsonb, p_actor_id uuid, p_expected_version integer) to authenticated;
grant execute on function public.invoice_apply_transition(p_invoice_id uuid, p_transition text, p_payload jsonb, p_actor_id uuid, p_expected_version integer) to service_role;

-- invoice_insert_event(p_entity_type text, p_entity_id uuid, p_aggregate_type text, p_aggregate_id uuid, p_invoice_id uuid, p_event_category text, p_event_type text, p_correlation_id uuid, p_causation_id uuid, p_payload jsonb, p_actor_id uuid) [AUTHENTICATED_CLIENT_CALLABLE]
revoke all on function public.invoice_insert_event(p_entity_type text, p_entity_id uuid, p_aggregate_type text, p_aggregate_id uuid, p_invoice_id uuid, p_event_category text, p_event_type text, p_correlation_id uuid, p_causation_id uuid, p_payload jsonb, p_actor_id uuid) from public, anon, authenticated, service_role;
grant execute on function public.invoice_insert_event(p_entity_type text, p_entity_id uuid, p_aggregate_type text, p_aggregate_id uuid, p_invoice_id uuid, p_event_category text, p_event_type text, p_correlation_id uuid, p_causation_id uuid, p_payload jsonb, p_actor_id uuid) to authenticated;

-- invoice_legacy_status_audit_report() [AUTHENTICATED_CLIENT_CALLABLE]
revoke all on function public.invoice_legacy_status_audit_report() from public, anon, authenticated, service_role;
grant execute on function public.invoice_legacy_status_audit_report() to authenticated;

-- invoice_payment_reconciliation_report() [AUTHENTICATED_CLIENT_CALLABLE]
revoke all on function public.invoice_payment_reconciliation_report() from public, anon, authenticated, service_role;
grant execute on function public.invoice_payment_reconciliation_report() to authenticated;

-- invoice_preventivo_allocated_total(p_preventivo_id uuid, p_exclude_invoice_id uuid) [SERVER_ONLY]
revoke all on function public.invoice_preventivo_allocated_total(p_preventivo_id uuid, p_exclude_invoice_id uuid) from public, anon, authenticated, service_role;
grant execute on function public.invoice_preventivo_allocated_total(p_preventivo_id uuid, p_exclude_invoice_id uuid) to service_role;

-- invoice_status_backfill_snapshot() [AUTHENTICATED_CLIENT_CALLABLE]
revoke all on function public.invoice_status_backfill_snapshot() from public, anon, authenticated, service_role;
grant execute on function public.invoice_status_backfill_snapshot() to authenticated;

-- invoice_status_migration_report() [AUTHENTICATED_CLIENT_CALLABLE]
revoke all on function public.invoice_status_migration_report() from public, anon, authenticated, service_role;
grant execute on function public.invoice_status_migration_report() to authenticated;

-- invoice_write_status_axes(p_invoice_id uuid, p_document_status text, p_payment_status text, p_sdi_status text, p_correlation_id uuid, p_causation_id uuid, p_emit_event boolean, p_actor_id uuid, p_transition text) [SERVER_ONLY]
revoke all on function public.invoice_write_status_axes(p_invoice_id uuid, p_document_status text, p_payment_status text, p_sdi_status text, p_correlation_id uuid, p_causation_id uuid, p_emit_event boolean, p_actor_id uuid, p_transition text) from public, anon, authenticated, service_role;
grant execute on function public.invoice_write_status_axes(p_invoice_id uuid, p_document_status text, p_payment_status text, p_sdi_status text, p_correlation_id uuid, p_causation_id uuid, p_emit_event boolean, p_actor_id uuid, p_transition text) to service_role;

-- is_ddt_visible_to_client(p_ddt_id uuid) [PORTALE_CLIENT_CALLABLE]
revoke all on function public.is_ddt_visible_to_client(p_ddt_id uuid) from public, anon, authenticated, service_role;
grant execute on function public.is_ddt_visible_to_client(p_ddt_id uuid) to authenticated;

-- is_preventivo_visible_to_client(p_preventivo_id uuid) [PORTALE_CLIENT_CALLABLE]
revoke all on function public.is_preventivo_visible_to_client(p_preventivo_id uuid) from public, anon, authenticated, service_role;
grant execute on function public.is_preventivo_visible_to_client(p_preventivo_id uuid) to authenticated;

-- log_app_settings_update_audit() [AUTHENTICATED_CLIENT_CALLABLE]
revoke all on function public.log_app_settings_update_audit() from public, anon, authenticated, service_role;
grant execute on function public.log_app_settings_update_audit() to authenticated;
grant execute on function public.log_app_settings_update_audit() to service_role;

-- maintenance_plans_v1_db_enabled() [AUTHENTICATED_CLIENT_CALLABLE]
revoke all on function public.maintenance_plans_v1_db_enabled() from public, anon, authenticated, service_role;
grant execute on function public.maintenance_plans_v1_db_enabled() to authenticated;
grant execute on function public.maintenance_plans_v1_db_enabled() to service_role;

-- mark_ddt_consegnato(p_ddt_id uuid) [AUTHENTICATED_CLIENT_CALLABLE]
revoke all on function public.mark_ddt_consegnato(p_ddt_id uuid) from public, anon, authenticated, service_role;
grant execute on function public.mark_ddt_consegnato(p_ddt_id uuid) to authenticated;
grant execute on function public.mark_ddt_consegnato(p_ddt_id uuid) to service_role;

-- mark_ddt_stampato(p_ddt_id uuid) [AUTHENTICATED_CLIENT_CALLABLE]
revoke all on function public.mark_ddt_stampato(p_ddt_id uuid) from public, anon, authenticated, service_role;
grant execute on function public.mark_ddt_stampato(p_ddt_id uuid) to authenticated;
grant execute on function public.mark_ddt_stampato(p_ddt_id uuid) to service_role;

-- mark_preventivo_viewed_by_client(p_preventivo_id uuid) [PORTALE_CLIENT_CALLABLE]
revoke all on function public.mark_preventivo_viewed_by_client(p_preventivo_id uuid) from public, anon, authenticated, service_role;
grant execute on function public.mark_preventivo_viewed_by_client(p_preventivo_id uuid) to authenticated;

-- notification_cliente_inbox_eligible() [AUTHENTICATED_CLIENT_CALLABLE]
revoke all on function public.notification_cliente_inbox_eligible() from public, anon, authenticated, service_role;
grant execute on function public.notification_cliente_inbox_eligible() to authenticated;

-- notification_staff_inbox_eligible() [AUTHENTICATED_CLIENT_CALLABLE]
revoke all on function public.notification_staff_inbox_eligible() from public, anon, authenticated, service_role;
grant execute on function public.notification_staff_inbox_eligible() to authenticated;

-- notification_visible_to_auth_user(p_n notifications) [AUTHENTICATED_CLIENT_CALLABLE]
revoke all on function public.notification_visible_to_auth_user(p_n notifications) from public, anon, authenticated, service_role;
grant execute on function public.notification_visible_to_auth_user(p_n notifications) to authenticated;

-- open_attrezzatura_assignment(p_attrezzatura_id uuid, p_mezzo_id uuid, p_change_reason assignment_change_reason, p_note text, p_actor_id uuid, p_valid_from timestamp with time zone) [AUTHENTICATED_CLIENT_CALLABLE]
revoke all on function public.open_attrezzatura_assignment(p_attrezzatura_id uuid, p_mezzo_id uuid, p_change_reason assignment_change_reason, p_note text, p_actor_id uuid, p_valid_from timestamp with time zone) from public, anon, authenticated, service_role;
grant execute on function public.open_attrezzatura_assignment(p_attrezzatura_id uuid, p_mezzo_id uuid, p_change_reason assignment_change_reason, p_note text, p_actor_id uuid, p_valid_from timestamp with time zone) to authenticated;
grant execute on function public.open_attrezzatura_assignment(p_attrezzatura_id uuid, p_mezzo_id uuid, p_change_reason assignment_change_reason, p_note text, p_actor_id uuid, p_valid_from timestamp with time zone) to service_role;

-- ordine_fornitore_receive_delivery(p_ordine_id uuid, p_batch_id text, p_lines jsonb, p_apply_stock boolean) [AUTHENTICATED_CLIENT_CALLABLE]
revoke all on function public.ordine_fornitore_receive_delivery(p_ordine_id uuid, p_batch_id text, p_lines jsonb, p_apply_stock boolean) from public, anon, authenticated, service_role;
grant execute on function public.ordine_fornitore_receive_delivery(p_ordine_id uuid, p_batch_id text, p_lines jsonb, p_apply_stock boolean) to authenticated;
grant execute on function public.ordine_fornitore_receive_delivery(p_ordine_id uuid, p_batch_id text, p_lines jsonb, p_apply_stock boolean) to service_role;

-- process_search_rebuild_queue(p_batch_size integer) [CRON_ONLY]
revoke all on function public.process_search_rebuild_queue(p_batch_size integer) from public, anon, authenticated, service_role;
grant execute on function public.process_search_rebuild_queue(p_batch_size integer) to service_role;

-- prune_app_settings_audit_retention() [CRON_ONLY]
revoke all on function public.prune_app_settings_audit_retention() from public, anon, authenticated, service_role;
grant execute on function public.prune_app_settings_audit_retention() to service_role;

-- prune_log_modifiche_dashboard_window() [CRON_ONLY]
revoke all on function public.prune_log_modifiche_dashboard_window() from public, anon, authenticated, service_role;
grant execute on function public.prune_log_modifiche_dashboard_window() to service_role;

-- prune_log_modifiche_per_entity() [CRON_ONLY]
revoke all on function public.prune_log_modifiche_per_entity() from public, anon, authenticated, service_role;
grant execute on function public.prune_log_modifiche_per_entity() to service_role;

-- prune_log_modifiche_retention() [SERVER_ONLY]
revoke all on function public.prune_log_modifiche_retention() from public, anon, authenticated, service_role;
grant execute on function public.prune_log_modifiche_retention() to service_role;

-- prune_maintenance_audit_events_retention() [CRON_ONLY]
revoke all on function public.prune_maintenance_audit_events_retention() from public, anon, authenticated, service_role;
grant execute on function public.prune_maintenance_audit_events_retention() to service_role;

-- prune_mezzo_anagrafica_history_retention() [CRON_ONLY]
revoke all on function public.prune_mezzo_anagrafica_history_retention() from public, anon, authenticated, service_role;
grant execute on function public.prune_mezzo_anagrafica_history_retention() to service_role;

-- rbac_auth_uid() [AUTHENTICATED_CLIENT_CALLABLE]
revoke all on function public.rbac_auth_uid() from public, anon, authenticated, service_role;
grant execute on function public.rbac_auth_uid() to authenticated;

-- rbac_bunder_can(p_op text) [AUTHENTICATED_CLIENT_CALLABLE]
revoke all on function public.rbac_bunder_can(p_op text) from public, anon, authenticated, service_role;
grant execute on function public.rbac_bunder_can(p_op text) to authenticated;

-- rbac_can_delete(p_resource text) [AUTHENTICATED_CLIENT_CALLABLE]
revoke all on function public.rbac_can_delete(p_resource text) from public, anon, authenticated, service_role;
grant execute on function public.rbac_can_delete(p_resource text) to authenticated;

-- rbac_can_read(p_resource text) [AUTHENTICATED_CLIENT_CALLABLE]
revoke all on function public.rbac_can_read(p_resource text) from public, anon, authenticated, service_role;
grant execute on function public.rbac_can_read(p_resource text) to authenticated;

-- rbac_can_read_app_settings(p_module text) [AUTHENTICATED_CLIENT_CALLABLE]
revoke all on function public.rbac_can_read_app_settings(p_module text) from public, anon, authenticated, service_role;
grant execute on function public.rbac_can_read_app_settings(p_module text) to authenticated;

-- rbac_can_read_lavorazione_row(p_mezzo_id uuid) [AUTHENTICATED_CLIENT_CALLABLE]
revoke all on function public.rbac_can_read_lavorazione_row(p_mezzo_id uuid) from public, anon, authenticated, service_role;
grant execute on function public.rbac_can_read_lavorazione_row(p_mezzo_id uuid) to authenticated;

-- rbac_can_read_log(p_entita text, p_entita_id uuid) [AUTHENTICATED_CLIENT_CALLABLE]
revoke all on function public.rbac_can_read_log(p_entita text, p_entita_id uuid) from public, anon, authenticated, service_role;
grant execute on function public.rbac_can_read_log(p_entita text, p_entita_id uuid) to authenticated;

-- rbac_can_read_log_row(p_entita text, p_entita_id uuid) [AUTHENTICATED_CLIENT_CALLABLE]
revoke all on function public.rbac_can_read_log_row(p_entita text, p_entita_id uuid) from public, anon, authenticated, service_role;
grant execute on function public.rbac_can_read_log_row(p_entita text, p_entita_id uuid) to authenticated;

-- rbac_can_read_operational() [AUTHENTICATED_CLIENT_CALLABLE]
revoke all on function public.rbac_can_read_operational() from public, anon, authenticated, service_role;
grant execute on function public.rbac_can_read_operational() to authenticated;

-- rbac_can_read_row(p_resource text, p_row_id uuid) [AUTHENTICATED_CLIENT_CALLABLE]
revoke all on function public.rbac_can_read_row(p_resource text, p_row_id uuid) from public, anon, authenticated, service_role;
grant execute on function public.rbac_can_read_row(p_resource text, p_row_id uuid) to authenticated;

-- rbac_can_read_storage() [AUTHENTICATED_CLIENT_CALLABLE]
revoke all on function public.rbac_can_read_storage() from public, anon, authenticated, service_role;
grant execute on function public.rbac_can_read_storage() to authenticated;

-- rbac_can_write(p_resource text) [AUTHENTICATED_CLIENT_CALLABLE]
revoke all on function public.rbac_can_write(p_resource text) from public, anon, authenticated, service_role;
grant execute on function public.rbac_can_write(p_resource text) to authenticated;

-- rbac_can_write_app_settings_row(p_module text, p_key text) [AUTHENTICATED_CLIENT_CALLABLE]
revoke all on function public.rbac_can_write_app_settings_row(p_module text, p_key text) from public, anon, authenticated, service_role;
grant execute on function public.rbac_can_write_app_settings_row(p_module text, p_key text) to authenticated;

-- rbac_can_write_operational() [AUTHENTICATED_CLIENT_CALLABLE]
revoke all on function public.rbac_can_write_operational() from public, anon, authenticated, service_role;
grant execute on function public.rbac_can_write_operational() to authenticated;

-- rbac_can_write_storage() [AUTHENTICATED_CLIENT_CALLABLE]
revoke all on function public.rbac_can_write_storage() from public, anon, authenticated, service_role;
grant execute on function public.rbac_can_write_storage() to authenticated;

-- rbac_cliente_ref() [AUTHENTICATED_CLIENT_CALLABLE]
revoke all on function public.rbac_cliente_ref() from public, anon, authenticated, service_role;
grant execute on function public.rbac_cliente_ref() to authenticated;

-- rbac_has_capability(p_user_id uuid, p_capability text) [AUTHENTICATED_CLIENT_CALLABLE]
revoke all on function public.rbac_has_capability(p_user_id uuid, p_capability text) from public, anon, authenticated, service_role;
grant execute on function public.rbac_has_capability(p_user_id uuid, p_capability text) to authenticated;

-- rbac_is_admin() [AUTHENTICATED_CLIENT_CALLABLE]
revoke all on function public.rbac_is_admin() from public, anon, authenticated, service_role;
grant execute on function public.rbac_is_admin() to authenticated;

-- rbac_is_cliente() [AUTHENTICATED_CLIENT_CALLABLE]
revoke all on function public.rbac_is_cliente() from public, anon, authenticated, service_role;
grant execute on function public.rbac_is_cliente() to authenticated;

-- rbac_is_operatore() [AUTHENTICATED_CLIENT_CALLABLE]
revoke all on function public.rbac_is_operatore() from public, anon, authenticated, service_role;
grant execute on function public.rbac_is_operatore() to authenticated;

-- rbac_is_operatore_or_admin() [AUTHENTICATED_CLIENT_CALLABLE]
revoke all on function public.rbac_is_operatore_or_admin() from public, anon, authenticated, service_role;
grant execute on function public.rbac_is_operatore_or_admin() to authenticated;

-- rbac_is_ospite() [AUTHENTICATED_CLIENT_CALLABLE]
revoke all on function public.rbac_is_ospite() from public, anon, authenticated, service_role;
grant execute on function public.rbac_is_ospite() to authenticated;

-- rbac_lavorazione_visible_to_cliente(p_lavorazione_id uuid) [AUTHENTICATED_CLIENT_CALLABLE]
revoke all on function public.rbac_lavorazione_visible_to_cliente(p_lavorazione_id uuid) from public, anon, authenticated, service_role;
grant execute on function public.rbac_lavorazione_visible_to_cliente(p_lavorazione_id uuid) to authenticated;

-- rbac_lifecycle_mezzo_id(p_table text, p_record_id uuid) [AUTHENTICATED_CLIENT_CALLABLE]
revoke all on function public.rbac_lifecycle_mezzo_id(p_table text, p_record_id uuid) from public, anon, authenticated, service_role;
grant execute on function public.rbac_lifecycle_mezzo_id(p_table text, p_record_id uuid) to authenticated;

-- rbac_maintenance_plans_mezzi_write() [AUTHENTICATED_CLIENT_CALLABLE]
revoke all on function public.rbac_maintenance_plans_mezzi_write() from public, anon, authenticated, service_role;
grant execute on function public.rbac_maintenance_plans_mezzi_write() to authenticated;

-- rbac_maintenance_plans_settings_write() [AUTHENTICATED_CLIENT_CALLABLE]
revoke all on function public.rbac_maintenance_plans_settings_write() from public, anon, authenticated, service_role;
grant execute on function public.rbac_maintenance_plans_settings_write() to authenticated;

-- rbac_mezzo_visible_to_cliente(p_mezzo_id uuid) [AUTHENTICATED_CLIENT_CALLABLE]
revoke all on function public.rbac_mezzo_visible_to_cliente(p_mezzo_id uuid) from public, anon, authenticated, service_role;
grant execute on function public.rbac_mezzo_visible_to_cliente(p_mezzo_id uuid) to authenticated;

-- rbac_module_can(p_module text, p_op text) [AUTHENTICATED_CLIENT_CALLABLE]
revoke all on function public.rbac_module_can(p_module text, p_op text) from public, anon, authenticated, service_role;
grant execute on function public.rbac_module_can(p_module text, p_op text) to authenticated;

-- rbac_module_from_page_access(p_user_id uuid, p_module text, p_op text) [SERVER_ONLY]
revoke all on function public.rbac_module_from_page_access(p_user_id uuid, p_module text, p_op text) from public, anon, authenticated, service_role;
grant execute on function public.rbac_module_from_page_access(p_user_id uuid, p_module text, p_op text) to service_role;

-- rbac_normalized_role() [AUTHENTICATED_CLIENT_CALLABLE]
revoke all on function public.rbac_normalized_role() from public, anon, authenticated, service_role;
grant execute on function public.rbac_normalized_role() to authenticated;

-- rbac_operational_diary_dashboard_read() [AUTHENTICATED_CLIENT_CALLABLE]
revoke all on function public.rbac_operational_diary_dashboard_read() from public, anon, authenticated, service_role;
grant execute on function public.rbac_operational_diary_dashboard_read() to authenticated;

-- rbac_operational_diary_dashboard_write() [AUTHENTICATED_CLIENT_CALLABLE]
revoke all on function public.rbac_operational_diary_dashboard_write() from public, anon, authenticated, service_role;
grant execute on function public.rbac_operational_diary_dashboard_write() to authenticated;

-- rbac_operator_global_settings_db_enabled() [AUTHENTICATED_CLIENT_CALLABLE]
revoke all on function public.rbac_operator_global_settings_db_enabled() from public, anon, authenticated, service_role;
grant execute on function public.rbac_operator_global_settings_db_enabled() to authenticated;

-- rbac_pilot_operator_global_settings_enabled() [AUTHENTICATED_CLIENT_CALLABLE]
revoke all on function public.rbac_pilot_operator_global_settings_enabled() from public, anon, authenticated, service_role;
grant execute on function public.rbac_pilot_operator_global_settings_enabled() to authenticated;

-- rbac_report_page_read() [AUTHENTICATED_CLIENT_CALLABLE]
revoke all on function public.rbac_report_page_read() from public, anon, authenticated, service_role;
grant execute on function public.rbac_report_page_read() to authenticated;

-- rbac_report_page_write() [AUTHENTICATED_CLIENT_CALLABLE]
revoke all on function public.rbac_report_page_write() from public, anon, authenticated, service_role;
grant execute on function public.rbac_report_page_write() to authenticated;

-- rbac_resource_module_can(p_resource text, p_op text) [AUTHENTICATED_CLIENT_CALLABLE]
revoke all on function public.rbac_resource_module_can(p_resource text, p_op text) from public, anon, authenticated, service_role;
grant execute on function public.rbac_resource_module_can(p_resource text, p_op text) to authenticated;

-- rbac_role() [AUTHENTICATED_CLIENT_CALLABLE]
revoke all on function public.rbac_role() from public, anon, authenticated, service_role;
grant execute on function public.rbac_role() to authenticated;

-- rbac_role_for_user(p_user_id uuid) [SERVER_ONLY]
revoke all on function public.rbac_role_for_user(p_user_id uuid) from public, anon, authenticated, service_role;
grant execute on function public.rbac_role_for_user(p_user_id uuid) to service_role;

-- rbac_role_has_permission(p_role_key text, p_permission_key text) [AUTHENTICATED_CLIENT_CALLABLE]
revoke all on function public.rbac_role_has_permission(p_role_key text, p_permission_key text) from public, anon, authenticated, service_role;
grant execute on function public.rbac_role_has_permission(p_role_key text, p_permission_key text) to authenticated;

-- rbac_scope_cliente(p_table text, p_record_id uuid) [AUTHENTICATED_CLIENT_CALLABLE]
revoke all on function public.rbac_scope_cliente(p_table text, p_record_id uuid) from public, anon, authenticated, service_role;
grant execute on function public.rbac_scope_cliente(p_table text, p_record_id uuid) to authenticated;

-- rbac_scope_cliente_lavorazioni_mezzo(p_mezzo_id uuid) [AUTHENTICATED_CLIENT_CALLABLE]
revoke all on function public.rbac_scope_cliente_lavorazioni_mezzo(p_mezzo_id uuid) from public, anon, authenticated, service_role;
grant execute on function public.rbac_scope_cliente_lavorazioni_mezzo(p_mezzo_id uuid) to authenticated;

-- rbac_scope_log_modifiche(p_entita text, p_entita_id uuid) [AUTHENTICATED_CLIENT_CALLABLE]
revoke all on function public.rbac_scope_log_modifiche(p_entita text, p_entita_id uuid) from public, anon, authenticated, service_role;
grant execute on function public.rbac_scope_log_modifiche(p_entita text, p_entita_id uuid) to authenticated;

-- rbac_staff_has_any_module_read() [AUTHENTICATED_CLIENT_CALLABLE]
revoke all on function public.rbac_staff_has_any_module_read() from public, anon, authenticated, service_role;
grant execute on function public.rbac_staff_has_any_module_read() to authenticated;

-- rbac_staff_has_any_module_write() [AUTHENTICATED_CLIENT_CALLABLE]
revoke all on function public.rbac_staff_has_any_module_write() from public, anon, authenticated, service_role;
grant execute on function public.rbac_staff_has_any_module_write() to authenticated;

-- rbac_storage_documenti_path_allowed(p_object_name text) [AUTHENTICATED_CLIENT_CALLABLE]
revoke all on function public.rbac_storage_documenti_path_allowed(p_object_name text) from public, anon, authenticated, service_role;
grant execute on function public.rbac_storage_documenti_path_allowed(p_object_name text) to authenticated;

-- rbac_storage_images_path_allowed(p_object_name text) [AUTHENTICATED_CLIENT_CALLABLE]
revoke all on function public.rbac_storage_images_path_allowed(p_object_name text) from public, anon, authenticated, service_role;
grant execute on function public.rbac_storage_images_path_allowed(p_object_name text) to authenticated;

-- rbac_user_company_id() [AUTHENTICATED_CLIENT_CALLABLE]
revoke all on function public.rbac_user_company_id() from public, anon, authenticated, service_role;
grant execute on function public.rbac_user_company_id() to authenticated;

-- rbac_user_effective_permission(p_user_id uuid, p_permission_key text) [AUTHENTICATED_CLIENT_CALLABLE]
revoke all on function public.rbac_user_effective_permission(p_user_id uuid, p_permission_key text) from public, anon, authenticated, service_role;
grant execute on function public.rbac_user_effective_permission(p_user_id uuid, p_permission_key text) to authenticated;

-- rbac_user_page_access_level(p_user_id uuid, p_page_key text) [SERVER_ONLY]
revoke all on function public.rbac_user_page_access_level(p_user_id uuid, p_page_key text) from public, anon, authenticated, service_role;
grant execute on function public.rbac_user_page_access_level(p_user_id uuid, p_page_key text) to service_role;

-- reassign_attrezzatura_mezzo(p_attrezzatura_id uuid, p_new_mezzo_id uuid, p_change_reason assignment_change_reason, p_note text, p_actor_id uuid) [AUTHENTICATED_CLIENT_CALLABLE]
revoke all on function public.reassign_attrezzatura_mezzo(p_attrezzatura_id uuid, p_new_mezzo_id uuid, p_change_reason assignment_change_reason, p_note text, p_actor_id uuid) from public, anon, authenticated, service_role;
grant execute on function public.reassign_attrezzatura_mezzo(p_attrezzatura_id uuid, p_new_mezzo_id uuid, p_change_reason assignment_change_reason, p_note text, p_actor_id uuid) to authenticated;
grant execute on function public.reassign_attrezzatura_mezzo(p_attrezzatura_id uuid, p_new_mezzo_id uuid, p_change_reason assignment_change_reason, p_note text, p_actor_id uuid) to service_role;

-- recalc_compliance_rule_due(p_rule_id uuid) [SERVER_ONLY]
revoke all on function public.recalc_compliance_rule_due(p_rule_id uuid) from public, anon, authenticated, service_role;
grant execute on function public.recalc_compliance_rule_due(p_rule_id uuid) to service_role;

-- refresh_invoice_search_document(p_id uuid) [CRON_ONLY]
revoke all on function public.refresh_invoice_search_document(p_id uuid) from public, anon, authenticated, service_role;
grant execute on function public.refresh_invoice_search_document(p_id uuid) to service_role;

-- refresh_lavorazione_search_document(p_lavorazione_id uuid) [CRON_ONLY]
revoke all on function public.refresh_lavorazione_search_document(p_lavorazione_id uuid) from public, anon, authenticated, service_role;
grant execute on function public.refresh_lavorazione_search_document(p_lavorazione_id uuid) to service_role;

-- refresh_magazzino_search_document(p_id uuid) [CRON_ONLY]
revoke all on function public.refresh_magazzino_search_document(p_id uuid) from public, anon, authenticated, service_role;
grant execute on function public.refresh_magazzino_search_document(p_id uuid) to service_role;

-- refresh_mezzo_search_document(p_id uuid) [CRON_ONLY]
revoke all on function public.refresh_mezzo_search_document(p_id uuid) from public, anon, authenticated, service_role;
grant execute on function public.refresh_mezzo_search_document(p_id uuid) to service_role;

-- refresh_ordine_fornitore_search_document(p_id uuid) [CRON_ONLY]
revoke all on function public.refresh_ordine_fornitore_search_document(p_id uuid) from public, anon, authenticated, service_role;
grant execute on function public.refresh_ordine_fornitore_search_document(p_id uuid) to service_role;

-- refresh_preventivo_search_document(p_id uuid) [CRON_ONLY]
revoke all on function public.refresh_preventivo_search_document(p_id uuid) from public, anon, authenticated, service_role;
grant execute on function public.refresh_preventivo_search_document(p_id uuid) to service_role;

-- register_customer_payment_multi(p_payload jsonb) [AUTHENTICATED_CLIENT_CALLABLE]
revoke all on function public.register_customer_payment_multi(p_payload jsonb) from public, anon, authenticated, service_role;
grant execute on function public.register_customer_payment_multi(p_payload jsonb) to authenticated;
grant execute on function public.register_customer_payment_multi(p_payload jsonb) to service_role;

-- register_invoice_payment(p_payload jsonb) [AUTHENTICATED_CLIENT_CALLABLE]
revoke all on function public.register_invoice_payment(p_payload jsonb) from public, anon, authenticated, service_role;
grant execute on function public.register_invoice_payment(p_payload jsonb) to authenticated;
grant execute on function public.register_invoice_payment(p_payload jsonb) to service_role;

-- register_maintenance_execution_v2(p_config_id uuid, p_mezzo_id uuid, p_plan_id uuid, p_performed_at date, p_ore_at_service numeric, p_km_at_service numeric, p_mezzo_ore_snapshot numeric, p_note text, p_anomaly_note text, p_lavorazione_id uuid, p_scheda_lavorazione_id uuid, p_preset_version_id uuid, p_interval_type maintenance_interval_type, p_interval_value_at_execution numeric, p_execution_type maintenance_execution_type, p_preset_snapshot jsonb, p_parts jsonb, p_forecast jsonb, p_checklist jsonb) [AUTHENTICATED_CLIENT_CALLABLE]
revoke all on function public.register_maintenance_execution_v2(p_config_id uuid, p_mezzo_id uuid, p_plan_id uuid, p_performed_at date, p_ore_at_service numeric, p_km_at_service numeric, p_mezzo_ore_snapshot numeric, p_note text, p_anomaly_note text, p_lavorazione_id uuid, p_scheda_lavorazione_id uuid, p_preset_version_id uuid, p_interval_type maintenance_interval_type, p_interval_value_at_execution numeric, p_execution_type maintenance_execution_type, p_preset_snapshot jsonb, p_parts jsonb, p_forecast jsonb, p_checklist jsonb) from public, anon, authenticated, service_role;
grant execute on function public.register_maintenance_execution_v2(p_config_id uuid, p_mezzo_id uuid, p_plan_id uuid, p_performed_at date, p_ore_at_service numeric, p_km_at_service numeric, p_mezzo_ore_snapshot numeric, p_note text, p_anomaly_note text, p_lavorazione_id uuid, p_scheda_lavorazione_id uuid, p_preset_version_id uuid, p_interval_type maintenance_interval_type, p_interval_value_at_execution numeric, p_execution_type maintenance_execution_type, p_preset_snapshot jsonb, p_parts jsonb, p_forecast jsonb, p_checklist jsonb) to authenticated;
grant execute on function public.register_maintenance_execution_v2(p_config_id uuid, p_mezzo_id uuid, p_plan_id uuid, p_performed_at date, p_ore_at_service numeric, p_km_at_service numeric, p_mezzo_ore_snapshot numeric, p_note text, p_anomaly_note text, p_lavorazione_id uuid, p_scheda_lavorazione_id uuid, p_preset_version_id uuid, p_interval_type maintenance_interval_type, p_interval_value_at_execution numeric, p_execution_type maintenance_execution_type, p_preset_snapshot jsonb, p_parts jsonb, p_forecast jsonb, p_checklist jsonb) to service_role;

-- register_maintenance_execution_v2(p_config_id uuid, p_mezzo_id uuid, p_plan_id uuid, p_performed_at date, p_ore_at_service numeric, p_km_at_service numeric, p_mezzo_ore_snapshot numeric, p_note text, p_anomaly_note text, p_lavorazione_id uuid, p_scheda_lavorazione_id uuid, p_preset_version_id uuid, p_interval_type maintenance_interval_type, p_interval_value_at_execution numeric, p_parts jsonb, p_forecast jsonb) [AUTHENTICATED_CLIENT_CALLABLE]
revoke all on function public.register_maintenance_execution_v2(p_config_id uuid, p_mezzo_id uuid, p_plan_id uuid, p_performed_at date, p_ore_at_service numeric, p_km_at_service numeric, p_mezzo_ore_snapshot numeric, p_note text, p_anomaly_note text, p_lavorazione_id uuid, p_scheda_lavorazione_id uuid, p_preset_version_id uuid, p_interval_type maintenance_interval_type, p_interval_value_at_execution numeric, p_parts jsonb, p_forecast jsonb) from public, anon, authenticated, service_role;
grant execute on function public.register_maintenance_execution_v2(p_config_id uuid, p_mezzo_id uuid, p_plan_id uuid, p_performed_at date, p_ore_at_service numeric, p_km_at_service numeric, p_mezzo_ore_snapshot numeric, p_note text, p_anomaly_note text, p_lavorazione_id uuid, p_scheda_lavorazione_id uuid, p_preset_version_id uuid, p_interval_type maintenance_interval_type, p_interval_value_at_execution numeric, p_parts jsonb, p_forecast jsonb) to authenticated;
grant execute on function public.register_maintenance_execution_v2(p_config_id uuid, p_mezzo_id uuid, p_plan_id uuid, p_performed_at date, p_ore_at_service numeric, p_km_at_service numeric, p_mezzo_ore_snapshot numeric, p_note text, p_anomaly_note text, p_lavorazione_id uuid, p_scheda_lavorazione_id uuid, p_preset_version_id uuid, p_interval_type maintenance_interval_type, p_interval_value_at_execution numeric, p_parts jsonb, p_forecast jsonb) to service_role;

-- replace_ddt_for_preventivo(p_payload jsonb) [AUTHENTICATED_CLIENT_CALLABLE]
revoke all on function public.replace_ddt_for_preventivo(p_payload jsonb) from public, anon, authenticated, service_role;
grant execute on function public.replace_ddt_for_preventivo(p_payload jsonb) to authenticated;
grant execute on function public.replace_ddt_for_preventivo(p_payload jsonb) to service_role;

-- resolve_auth_email_for_login(p_identifier text) [PUBLIC_SAFE]
revoke all on function public.resolve_auth_email_for_login(p_identifier text) from public, anon, authenticated, service_role;
-- security-allowlist: PUBLIC_SAFE manifest entry
grant execute on function public.resolve_auth_email_for_login(p_identifier text) to anon;
grant execute on function public.resolve_auth_email_for_login(p_identifier text) to service_role;

-- security_set_user_role(p_user_id uuid, p_role_key text) [SERVER_ONLY]
revoke all on function public.security_set_user_role(p_user_id uuid, p_role_key text) from public, anon, authenticated, service_role;
grant execute on function public.security_set_user_role(p_user_id uuid, p_role_key text) to service_role;

-- soft_delete_dashboard_promemoria(p_id uuid, p_scope text) [AUTHENTICATED_CLIENT_CALLABLE]
revoke all on function public.soft_delete_dashboard_promemoria(p_id uuid, p_scope text) from public, anon, authenticated, service_role;
grant execute on function public.soft_delete_dashboard_promemoria(p_id uuid, p_scope text) to authenticated;
grant execute on function public.soft_delete_dashboard_promemoria(p_id uuid, p_scope text) to service_role;

-- soft_delete_lavorazione(p_lavorazione_id uuid) [AUTHENTICATED_CLIENT_CALLABLE]
revoke all on function public.soft_delete_lavorazione(p_lavorazione_id uuid) from public, anon, authenticated, service_role;
grant execute on function public.soft_delete_lavorazione(p_lavorazione_id uuid) to authenticated;
grant execute on function public.soft_delete_lavorazione(p_lavorazione_id uuid) to service_role;

-- soft_delete_operational_diary_entry(p_id uuid) [AUTHENTICATED_CLIENT_CALLABLE]
revoke all on function public.soft_delete_operational_diary_entry(p_id uuid) from public, anon, authenticated, service_role;
grant execute on function public.soft_delete_operational_diary_entry(p_id uuid) to authenticated;
grant execute on function public.soft_delete_operational_diary_entry(p_id uuid) to service_role;

-- soft_delete_workshop_schedule_event(p_id uuid) [AUTHENTICATED_CLIENT_CALLABLE]
revoke all on function public.soft_delete_workshop_schedule_event(p_id uuid) from public, anon, authenticated, service_role;
grant execute on function public.soft_delete_workshop_schedule_event(p_id uuid) to authenticated;
grant execute on function public.soft_delete_workshop_schedule_event(p_id uuid) to service_role;

-- sync_mezzo_km_from_reading() [SERVER_ONLY]
revoke all on function public.sync_mezzo_km_from_reading() from public, anon, authenticated, service_role;
grant execute on function public.sync_mezzo_km_from_reading() to service_role;

-- trg_ai_part_searches_invoke_worker() [INTERNAL_ONLY]
revoke all on function public.trg_ai_part_searches_invoke_worker() from public, anon, authenticated, service_role;
grant execute on function public.trg_ai_part_searches_invoke_worker() to service_role;

-- trg_attrezzature_outbox() [INTERNAL_ONLY]
revoke all on function public.trg_attrezzature_outbox() from public, anon, authenticated, service_role;
grant execute on function public.trg_attrezzature_outbox() to service_role;

-- trg_clienti_anagrafiche_outbox() [INTERNAL_ONLY]
revoke all on function public.trg_clienti_anagrafiche_outbox() from public, anon, authenticated, service_role;
grant execute on function public.trg_clienti_anagrafiche_outbox() to service_role;

-- trg_communication_outbox_invoke_worker() [INTERNAL_ONLY]
revoke all on function public.trg_communication_outbox_invoke_worker() from public, anon, authenticated, service_role;
grant execute on function public.trg_communication_outbox_invoke_worker() to service_role;

-- trg_communication_send_queue_invoke_worker() [INTERNAL_ONLY]
revoke all on function public.trg_communication_send_queue_invoke_worker() from public, anon, authenticated, service_role;
grant execute on function public.trg_communication_send_queue_invoke_worker() to service_role;

-- trg_compliance_record_recalc_rule() [INTERNAL_ONLY]
revoke all on function public.trg_compliance_record_recalc_rule() from public, anon, authenticated, service_role;
grant execute on function public.trg_compliance_record_recalc_rule() to service_role;

-- trg_delivery_queue_invoke_worker() [INTERNAL_ONLY]
revoke all on function public.trg_delivery_queue_invoke_worker() from public, anon, authenticated, service_role;
grant execute on function public.trg_delivery_queue_invoke_worker() to service_role;

-- trg_document_ai_index_invoke_worker() [INTERNAL_ONLY]
revoke all on function public.trg_document_ai_index_invoke_worker() from public, anon, authenticated, service_role;
grant execute on function public.trg_document_ai_index_invoke_worker() to service_role;

-- trg_documenti_outbox() [INTERNAL_ONLY]
revoke all on function public.trg_documenti_outbox() from public, anon, authenticated, service_role;
grant execute on function public.trg_documenti_outbox() to service_role;

-- trg_fanout_client_portal_lavorazione_completata() [INTERNAL_ONLY]
revoke all on function public.trg_fanout_client_portal_lavorazione_completata() from public, anon, authenticated, service_role;
grant execute on function public.trg_fanout_client_portal_lavorazione_completata() to service_role;

-- trg_fanout_client_portal_lavorazione_ingresso() [INTERNAL_ONLY]
revoke all on function public.trg_fanout_client_portal_lavorazione_ingresso() from public, anon, authenticated, service_role;
grant execute on function public.trg_fanout_client_portal_lavorazione_ingresso() to service_role;

-- trg_invoices_outbox() [INTERNAL_ONLY]
revoke all on function public.trg_invoices_outbox() from public, anon, authenticated, service_role;
grant execute on function public.trg_invoices_outbox() to service_role;

-- trg_lavorazioni_assign_codice() [INTERNAL_ONLY]
revoke all on function public.trg_lavorazioni_assign_codice() from public, anon, authenticated, service_role;
grant execute on function public.trg_lavorazioni_assign_codice() to service_role;

-- trg_lavorazioni_outbox_archived() [INTERNAL_ONLY]
revoke all on function public.trg_lavorazioni_outbox_archived() from public, anon, authenticated, service_role;
grant execute on function public.trg_lavorazioni_outbox_archived() to service_role;

-- trg_lavorazioni_outbox_completed() [INTERNAL_ONLY]
revoke all on function public.trg_lavorazioni_outbox_completed() from public, anon, authenticated, service_role;
grant execute on function public.trg_lavorazioni_outbox_completed() to service_role;

-- trg_lavorazioni_outbox_created() [INTERNAL_ONLY]
revoke all on function public.trg_lavorazioni_outbox_created() from public, anon, authenticated, service_role;
grant execute on function public.trg_lavorazioni_outbox_created() to service_role;

-- trg_lavorazioni_outbox_deleted() [INTERNAL_ONLY]
revoke all on function public.trg_lavorazioni_outbox_deleted() from public, anon, authenticated, service_role;
grant execute on function public.trg_lavorazioni_outbox_deleted() to service_role;

-- trg_lavorazioni_outbox_updated() [INTERNAL_ONLY]
revoke all on function public.trg_lavorazioni_outbox_updated() from public, anon, authenticated, service_role;
grant execute on function public.trg_lavorazioni_outbox_updated() to service_role;

-- trg_lavorazioni_refresh_search_document() [INTERNAL_ONLY]
revoke all on function public.trg_lavorazioni_refresh_search_document() from public, anon, authenticated, service_role;
grant execute on function public.trg_lavorazioni_refresh_search_document() to service_role;

-- trg_magazzino_outbox_stock_crossing() [INTERNAL_ONLY]
revoke all on function public.trg_magazzino_outbox_stock_crossing() from public, anon, authenticated, service_role;
grant execute on function public.trg_magazzino_outbox_stock_crossing() to service_role;

-- trg_magazzino_refresh_search_document() [INTERNAL_ONLY]
revoke all on function public.trg_magazzino_refresh_search_document() from public, anon, authenticated, service_role;
grant execute on function public.trg_magazzino_refresh_search_document() to service_role;

-- trg_magazzino_ricambi_outbox_created() [INTERNAL_ONLY]
revoke all on function public.trg_magazzino_ricambi_outbox_created() from public, anon, authenticated, service_role;
grant execute on function public.trg_magazzino_ricambi_outbox_created() to service_role;

-- trg_magazzino_ricambi_outbox_deleted() [INTERNAL_ONLY]
revoke all on function public.trg_magazzino_ricambi_outbox_deleted() from public, anon, authenticated, service_role;
grant execute on function public.trg_magazzino_ricambi_outbox_deleted() to service_role;

-- trg_mezzi_enqueue_lavorazioni_search_rebuild() [INTERNAL_ONLY]
revoke all on function public.trg_mezzi_enqueue_lavorazioni_search_rebuild() from public, anon, authenticated, service_role;
grant execute on function public.trg_mezzi_enqueue_lavorazioni_search_rebuild() to service_role;

-- trg_mezzi_outbox() [INTERNAL_ONLY]
revoke all on function public.trg_mezzi_outbox() from public, anon, authenticated, service_role;
grant execute on function public.trg_mezzi_outbox() to service_role;

-- trg_mezzi_refresh_search_document() [INTERNAL_ONLY]
revoke all on function public.trg_mezzi_refresh_search_document() from public, anon, authenticated, service_role;
grant execute on function public.trg_mezzi_refresh_search_document() to service_role;

-- trg_movimenti_ricambi_outbox() [INTERNAL_ONLY]
revoke all on function public.trg_movimenti_ricambi_outbox() from public, anon, authenticated, service_role;
grant execute on function public.trg_movimenti_ricambi_outbox() to service_role;

-- trg_notification_outbox_invoke_worker() [INTERNAL_ONLY]
revoke all on function public.trg_notification_outbox_invoke_worker() from public, anon, authenticated, service_role;
grant execute on function public.trg_notification_outbox_invoke_worker() to service_role;

-- trg_ordini_fornitori_assign_numero() [INTERNAL_ONLY]
revoke all on function public.trg_ordini_fornitori_assign_numero() from public, anon, authenticated, service_role;
grant execute on function public.trg_ordini_fornitori_assign_numero() to service_role;

-- trg_ordini_fornitori_outbox() [INTERNAL_ONLY]
revoke all on function public.trg_ordini_fornitori_outbox() from public, anon, authenticated, service_role;
grant execute on function public.trg_ordini_fornitori_outbox() to service_role;

-- trg_preventivi_assign_numero() [INTERNAL_ONLY]
revoke all on function public.trg_preventivi_assign_numero() from public, anon, authenticated, service_role;
grant execute on function public.trg_preventivi_assign_numero() to service_role;

-- trg_preventivi_communication_outbox() [INTERNAL_ONLY]
revoke all on function public.trg_preventivi_communication_outbox() from public, anon, authenticated, service_role;
grant execute on function public.trg_preventivi_communication_outbox() to service_role;

-- trg_preventivi_outbox() [INTERNAL_ONLY]
revoke all on function public.trg_preventivi_outbox() from public, anon, authenticated, service_role;
grant execute on function public.trg_preventivi_outbox() to service_role;

-- trg_preventivi_refresh_search_document() [INTERNAL_ONLY]
revoke all on function public.trg_preventivi_refresh_search_document() from public, anon, authenticated, service_role;
grant execute on function public.trg_preventivi_refresh_search_document() to service_role;

-- trg_scheda_lavorazione_refresh_parent_search() [INTERNAL_ONLY]
revoke all on function public.trg_scheda_lavorazione_refresh_parent_search() from public, anon, authenticated, service_role;
grant execute on function public.trg_scheda_lavorazione_refresh_parent_search() to service_role;

-- update_ddt_draft(p_ddt_id uuid, p_payload jsonb) [AUTHENTICATED_CLIENT_CALLABLE]
revoke all on function public.update_ddt_draft(p_ddt_id uuid, p_payload jsonb) from public, anon, authenticated, service_role;
grant execute on function public.update_ddt_draft(p_ddt_id uuid, p_payload jsonb) to authenticated;
grant execute on function public.update_ddt_draft(p_ddt_id uuid, p_payload jsonb) to service_role;

-- update_invoice_draft_with_rows(p_invoice_id uuid, p_payload jsonb) [AUTHENTICATED_CLIENT_CALLABLE]
revoke all on function public.update_invoice_draft_with_rows(p_invoice_id uuid, p_payload jsonb) from public, anon, authenticated, service_role;
grant execute on function public.update_invoice_draft_with_rows(p_invoice_id uuid, p_payload jsonb) to authenticated;
grant execute on function public.update_invoice_draft_with_rows(p_invoice_id uuid, p_payload jsonb) to service_role;

-- update_ordine_fornitore_draft(p_id uuid, p_payload jsonb, p_expected_updated_at timestamp with time zone) [AUTHENTICATED_CLIENT_CALLABLE]
revoke all on function public.update_ordine_fornitore_draft(p_id uuid, p_payload jsonb, p_expected_updated_at timestamp with time zone) from public, anon, authenticated, service_role;
grant execute on function public.update_ordine_fornitore_draft(p_id uuid, p_payload jsonb, p_expected_updated_at timestamp with time zone) to authenticated;
grant execute on function public.update_ordine_fornitore_draft(p_id uuid, p_payload jsonb, p_expected_updated_at timestamp with time zone) to service_role;

-- user_effective_can(p_module text, p_op text) [AUTHENTICATED_CLIENT_CALLABLE]
revoke all on function public.user_effective_can(p_module text, p_op text) from public, anon, authenticated, service_role;
grant execute on function public.user_effective_can(p_module text, p_op text) to authenticated;

-- wse_write_history(p_event_id uuid, p_revision integer, p_action text, p_before jsonb, p_after jsonb) [SERVER_ONLY]
revoke all on function public.wse_write_history(p_event_id uuid, p_revision integer, p_action text, p_before jsonb, p_after jsonb) from public, anon, authenticated, service_role;
grant execute on function public.wse_write_history(p_event_id uuid, p_revision integer, p_action text, p_before jsonb, p_after jsonb) to service_role;

notify pgrst, 'reload schema';
